### ISSUE TITLE
Create project from URL

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#100]
For now we can only provide input as uploaded files or manually add them in the project directory using a shell.
Instead I would like to be able to pass a URL that would be fetched with either FetchCode or the container-inspector fetch module or some other download mechanism (when you may require auth) TBD.

**Comment by tdruez** [comment]
Related to https://github.com/nexB/scancode.io/issues/35
@pombredanne can you point me to a working release of FetchCode?

**Comment by tdruez** [comment]
Input files can now be added to projects providing URLs:
1. Command line: `–input-url` see https://scancodeio.readthedocs.io/en/latest/scanpipe-command-line.html#scanpipe-add-input-project-project-input-file-files-input-url-urls

2. Create project form: 
  <img width="541" alt="Screenshot 2021-03-15 at 8 54 34 AM" src="https://user-images.githubusercontent.com/489057/111105779-23979c00-856d-11eb-8b7b-484aab53d137.png">

3. REST API: 
  <img width="1028" alt="Screenshot 2021-03-15 at 8 56 28 AM" src="https://user-images.githubusercontent.com/489057/111105796-2c886d80-856d-11eb-8c32-5656baec4941.png">
