### ISSUE TITLE
Move the "Execute pipeline now" now checkbox to the top of window

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1000]
In the pipeline popup I would like to have the " Execute pipeline now " moved towards to the so this is always visible. Ideally it would be right next to the "Add pipeline" header, on the same line.
This way it would always be visible even when scrolling down to see other pipelines.

![Screenshot_2023-11-03 ScanCode io](https://github.com/nexB/scancode.io/assets/675997/1a0019d5-a594-4230-b56a-23be93fcab67)

**Comment by tdruez** [comment]
See https://github.com/nexB/scancode.io/commit/6873047fdf6c63380d36dab0037bcc4195becd29
