### ISSUE TITLE
Cannot queue pipeline if a first pipeline runs

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1001]
I have a project with two non-started pipelines. I start the first one. I would like to queue the run of the second one, but " Run Pipeline: Not available until previous pipelines have completed. " shows in the pipeline pop-up and I can queue it for running.

**Comment by tdruez** [comment]
As a note, you do not need to manually queue the "second" pipelines as it will be executed automatically once the first one completes.

The UI is not great at the moment regarding the pipeline execution and should be improved, see https://github.com/nexB/scancode.io/issues/997

I think the user should only be able to start/stop a workflow (ie a combination of pipelines where the execution sequence matters) and not act on a single pipeline.

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/issues/997
