### ISSUE TITLE
scan_codebase_package should generate skinny packages from PURLs

### ISSUE THREAD

**Issue by keshav-space** [nexB/scancode.io#1006]
As of now, `scan_codebase_package` keeps the PURLs without assembling full packages/dependencies. Instead, we should create a skinny package out of these PURLs.

**Comment by tdruez** [comment]
@AyanSinhaMahapatra is this solved with the recent migration from scan_codebase_package to inspect_packages?

**Comment by AyanSinhaMahapatra** [comment]
Yes, both this, and the related issue linked above (#1007) has been completed in https://github.com/nexB/scancode.io/pull/1074

We now have `process_package_data` in the `scancode` pipe running after the `scan_for_application_packages` without assembling, where we have skinny packages (and dependencies) added from them.
See https://github.com/nexB/scancode.io/pull/1074/files#diff-f656ec70d95986a2e28afcc9bcfc1b9b834f998673a6570c0f56870fdb2e1b90L39 where we deleted the function which used to collect purls from package data, instead, we collect these from the packages/dependencies directly, which are now populated correctly.

**Comment by keshav-space** [comment]
Thanks, @AyanSinhaMahapatra, for addressing this. Closing now.
