### ISSUE TITLE
scan_package should not fail if there is an error in the scan

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1018]
When scanning https://codeload.github.com/ElinamLLC/SharpVectors/tar.gz/refs/tags/v1.8.2 with "scan_package" the pipeline fails with:
```
{'codebase/SharpVectors-1.8.2/Source/SharpVectorModel/Compressions/Brotli/Dictionary.cs': ['ERROR: for scanner: copyrights:\nERROR: Processing interrupted: timeout after 120 seconds.']}

Traceback:
  File "/opt/scancodeio/scanpipe/pipelines/__init__.py", line 121, in execute
    step(self)
  File "/opt/scancodeio/scanpipe/pipelines/scan_package.py", line 109, in run_scancode
    raise ScancodeError(errors)
```
This should not fail (since this is a recoverable error) but should instead be loaded with the errors as error messages and the scan as output. 

https://github.com/nexB/scancode-toolkit/issues/3614

**Comment by tdruez** [comment]
Improved in https://github.com/nexB/scancode.io/pull/1019
