### ISSUE TITLE
`make envfile` fails on `Mac ventura 13.1`

### ISSUE THREAD

**Issue by jayanth-kumar-morem** [nexB/scancode.io#1028]
**Describe the bug**
```
GET_SECRET_KEY=`base64 /dev/urandom | head -c50`
```
The above line fails while running `make envfile`

Here's the output of `make envfile`
```
(base) jayanth.kumar@Jayanths-MacBook-Pro scancode.io % make envfile
-> Create the .env file and generate a secret key
base64: invalid argument /dev/urandom
Usage:  base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
````

**System configuration**
- Which version of ScanCode.io are you running?
On latest main, last commit is `ce4cae0 (HEAD -> main, origin/main, origin/HEAD) Upgrade Django to version 5.0.0 #1020 (#1021)`

- Are you running the app using Docker?
NA
- On which OS?
MacOs ventura 13.1

- What inputs are you using?
NA
- Which pipeline are you running?
NA

**To Reproduce**
`make envfile`

**Expected behavior**
`.env` file should be created with a proper secret_key

**Screenshots**
NA

**Comment by armijnhemel** [comment]
The proposed solution actually creates a different sized key than the original on Linux:

```
$ base64 /dev/urandom | head -c50 > /tmp/orig
$ head -c50 /dev/urandom | base64 > /tmp/new
$ wc -c /tmp/orig /tmp/new 
 50 /tmp/orig
 69 /tmp/new
119 total
```

**Comment by jayanth-kumar-morem** [comment]
@armijnhemel thanks for pointing out, I updated it to trim to 50 chars

**Comment by tdruez** [comment]
@jayanth-kumar-morem Thanks for the fix.
