### ISSUE TITLE
Error on install: Cannot satisfy extractcode-libarchive/7z

### ISSUE THREAD

**Issue by cco3** [nexB/scancode.io#104]
Beginning with `434f7f9c9fca98f5842dd0f1cb56c008ec05802d`, I get errors related to extractcode when running `make dev`.

example from: `434f7f9c9fca98f5842dd0f1cb56c008ec05802d`
```
  Could not find a version that satisfies the requirement extractcode-libarchive==3.5.1.210122 (from scancodeio==1.0.7) (from versions: 3.1.4, 3.1.5)
No matching distribution found for extractcode-libarchive==3.5.1.210122 (from scancodeio==1.0.7)
```

example from `669b2b3ca1de81d0820e41de7568ec52040cb566`
```
  Could not find a version that satisfies the requirement extractcode-7z>=16.5.210122; extra == "full" (from extractcode[full]>=21.1.21; extra == "full"->scancode-toolkit[full]==21.2.9->scancodeio==1.1.0) (from versions: 9.38.3, 9.38.4)
No matching distribution found for extractcode-7z>=16.5.210122; extra == "full" (from extractcode[full]>=21.1.21; extra == "full"->scancode-toolkit[full]==21.2.9->scancodeio==1.1.0)
```

**Comment by pombredanne** [comment]
@cco3 sorry for that, that's likely some of the things I am battling against in scancode-toolkit.
Which OS do you there?

**Comment by pombredanne** [comment]
@tdruez IMHO https://github.com/nexB/scancode.io/blob/669b2b3ca1de81d0820e41de7568ec52040cb566/Makefile#L54 should have a `--upgrade` argument in all cases

**Comment by pombredanne** [comment]
I think all `pip` commands should be with a `--upgrade` since we work from pinned requirements.

**Comment by pombredanne** [comment]
@tdruez There is a problem though here where you should likely use the new `--constraint etc/requirements/base.txt` in https://github.com/nexB/scancode.io/blob/669b2b3ca1de81d0820e41de7568ec52040cb566/Makefile#L50
assuming you force the use of the latest pip.

I also tend to prefer fetching or bundling a virtualenv.pyz as `python -m venv` will work inconsistently across Python installations from distro. See https://github.com/nexB/scancode-toolkit/tree/develop/etc/thirdparty

**Comment by cco3** [comment]
> Which OS do you there?

I got this error on Debian (Buster).

**Comment by tdruez** [comment]
@cco3 I've implemented @pombredanne solution using the `virtualenv.pyz` app to bootstrap a consistent virtualenv across Python version and distro.

Could you try again with the latest `main` branch, commit `c05bc6e4036f1f3117015858fb2cea9bbe600ba7`, and le me know if it solve the installation issue on your side?

**Comment by cco3** [comment]
It works, thanks!
