### ISSUE TITLE
Using Swagger for API Documentation

### ISSUE THREAD

**Issue by hanif-ali** [nexB/scancode.io#106]
The root api view (`/api`) currently gives us the default view from Django Rest Framework. Would it be better if we use Swagger, like on vulnerablecode? If yes, I can make that change.

**Comment by tdruez** [comment]
@hanif-ali Before going ahead with that change, could you discuss some benefits of implementing Swagger in place of the current default?

**Comment by hanif-ali** [comment]
I think that would just provide a nicer formatted documentation for the API

**Comment by tdruez** [comment]
@hanif-ali PR welcome ;)

**Comment by ididitmyway** [comment]
I like swagger and you could also use the openapi generator 3.0 to automatically generate code for several languages, based on the api specifiation given by the swagger user interface!
