### ISSUE TITLE
Debian package is not extracted recursively

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1081]
I create a "scan_single_package" project using http://ftp.us.debian.org/debian/pool/main/e/elfutils/elfutils_0.188-2.1_amd64.deb as an input.
The package is not fully extracted recursively, even though the settings are to extract recursively

**Comment by tdruez** [comment]
@pombredanne Could you add the `recurse` option to the `extractcode.api.extract_archive` function?

**Comment by pombredanne** [comment]
`extractcode.api.extract_archive` cannot recurse
For this you need to use: `extractcode.api.extract_archives` instead

**Comment by tdruez** [comment]
@pombredanne The current implementation of extraction for the single package scan is to extract directly the single archive to the codebase work directory.
The `extractcode.api.extract_archives` extracts in place, so we need to copy the input archive first. This would change the scan root directory of 1 level.
Are you sure you want to apply this change?

Current:
![Screenshot 2024-02-19 at 22 05 38](https://github.com/nexB/scancode.io/assets/489057/671aed8a-e6a2-43ff-9a5e-0c4af202ebef)


Using extracts:
![Screenshot 2024-02-19 at 22 05 42](https://github.com/nexB/scancode.io/assets/489057/28b2f013-5ad2-4226-86b4-87b5f1b2ac7a)

**Comment by tdruez** [comment]
We could add a new step to run the `extract_archives` after extracting the single archive to the codebase dir.

**Comment by pombredanne** [comment]
Ok, then may be you could keep the extraction the way it is today and add a call to `extractcode.api.extract_archives()` afterwards to force recursion?

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/pull/1083
