### ISSUE TITLE
test_scanpipe_resolve_dependencies_pipeline_integration_misc takes over 2min to run

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#1087]
@AyanSinhaMahapatra The goal of those integration tests is to ensure the pipelines can run end to end, not to test the actual inspector on a large dataset. (those tests should exist in the inspector library).

Could you simplify the input to the minimum required for a fast execution?

**Comment by tdruez** [comment]
@AyanSinhaMahapatra could you confirm this is now fixed?

**Comment by AyanSinhaMahapatra** [comment]
@tdruez sorry about the late reply.

I've modified the test in the commit above ^, and it takes 0.3s now to run this test:
```
(scancode.io)
nexB/write_access/scancode.io  inspect-packages-only ✗                                      1h42m ⚑ ◒  ⍉
▶ python manage.py test scanpipe.tests.test_pipelines.PipelinesIntegrationTest.test_scanpipe_resolve_dependencies_pipeline_integration_misc
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.323s

OK
Destroying test database for alias 'default'...
```

This now has a single file and a single line of pinned dependency, does this work?
