### ISSUE TITLE
Add option to drag and drop files in the UI.

### ISSUE THREAD

**Issue by Abhirup-99** [nexB/scancode.io#109]
This would make it easier to drop a complete folder rather than individually clicking on the files to upload them. 
Check this out: https://www.dropzonejs.com/

**Comment by tdruez** [comment]
@Abhirup-99 PR welcome :)

**Comment by Abhirup-99** [comment]
Would push one shortly :).

**Comment by AvishrantsSh** [comment]
I am a little confused regarding this. So I'll just break it into parts.
1. How do you scan a complete folder? I mean is this feature supported, and if so how to do this?
2. Are there any plans to improve upon the UI of this project? If so, is it required to properly format and place the dropzone?

**Comment by tdruez** [comment]
> How do you scan a complete folder? I mean is this feature supported, and if so how to do this?

You can compress your folder in a zip archive (or any format supported by extract code) and upload it as an input file.
Alternatively, you can copy any content you want to scan in a project "work directory" directly on the file system. The "work directory" of a project is displayed in the header of the project detail view.

**Comment by tdruez** [comment]
> Are there any plans to improve upon the UI of this project?

Yes, the web UI is fairly new and constantly evolving. Any ideas on improving the UI are welcome.

> If so, is it required to properly format and place the dropzone?

Can you expand on your thoughts on this? I don't know what you mean by "properly format and place".

**Comment by tdruez** [comment]
@Abhirup-99 any progress on the Dropzone.js implementation?

**Comment by tdruez** [comment]
Drag and drop feature added for files input. Thanks @AvishrantsSh
