### ISSUE TITLE
Clarify and align supported CycloneDX versions in the AboutCode stack

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1103]
We should have a consistent support for versions we can import and export. My take is that this should be 1.4 and up and this may not be consistent?

- SCIO https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/cyclonedx.py 1.4? 1.5?
- SCTK https://github.com/nexB/scancode-toolkit/blob/develop/src/formattedcode/output_cyclonedx.py 1.3?
- DJCD https://github.com/nexB/dejacode/blob/badc0d68ec5e6535069c003e10676d230da8560d/dje/views.py#L2343 ? 

I am filing this issue here and we may need to break this down as needed in each repo.

**Comment by tdruez** [comment]
Dup https://github.com/nexB/scancode.io/issues/1104
