### ISSUE TITLE
ScanCode.io: Collect symbols in scan (from source code and store in scan results)

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode.io#1106]

**Comment by keshav-space** [comment]
Completed in https://github.com/nexB/scancode.io/pull/1116

The simple way to test this is to follow the below steps afteer instaling the ScanCode.io (https://scancodeio.readthedocs.io/en/latest/installation.html):

1. Creaete a new project along with source code archive/download url.
2. Add  and run `scan_codebase` pipeline.
3. Once the `scan_codebase` has completed add and run `collect_symbols` pipeline.
4. Once the `collect_symbols` has completed browse any resource and you will get the `source_symbols` in extra data tab.
