### ISSUE TITLE
ScanCode.io: Craft d2d pipeline steps for ELF

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1113]
The design is to extend the "map_deploy_to_develop" with an "Elf" option given the framework in:
- #1111

The process will be to:
- [x] Collect ELF DWARF symbols with the new elf-inspector. See https://github.com/nexB/elf-inspector
- [x] Create a pipeline to inspect ELF binaries https://github.com/nexB/scancode.io/blob/d6389b28841c4edf25075208eaf0708658650d06/scanpipe/pipelines/inspect_elf_binaries.py
- [x] Create D2D steps for ELFs using DWARF paths

**Comment by pombredanne** [comment]
Some status update:
- We have an ELF pipe wrapping the elf-inspector https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/elf.py
- We have a pipeline to inspect ELF binaries https://github.com/nexB/scancode.io/blob/d6389b28841c4edf25075208eaf0708658650d06/scanpipe/pipelines/inspect_elf_binaries.py
- We have an early prototype of ELF d2d in https://github.com/nexB/scancode.io/compare/main...812-d2d-elf-dwarf ( or https://github.com/nexB/scancode.io/compare/nexB:d6389b2...nexB:6a711f0 ) that can be reused as the base for the actual d2d steps

**Comment by TG1999** [comment]
This is now done and we have a set of proper steps grouped and tagged for JavaScript "binary/webpacked" analysis that can be selectively used in the context of:
- https://github.com/nexB/scancode.io/issues/1111

The actual JavaScript-specific pipeline steps look like this:

![Image](https://github.com/nexB/scancode.io/assets/34160672/d338434d-4e31-4bb9-b708-db952a03d634)

To test the feature:
- Install ScanCode.io
- Create a new project
- Add these two `Download URLs` exactly as below using these webpacked examples:
  - source:  https://github.com/nexB/scancode.io/raw/main/scanpipe/tests/data/d2d-elfs/from-data.zip#from
  - binary: https://github.com/nexB/scancode.io/raw/main/scanpipe/tests/data/d2d-elfs/from-data.zip#from
- Select and execute the "map_deploy_to_develop" pipeline, clicking on the Elf option

Here is how the project creation looks like:

![Image](https://github.com/nexB/scancode.io/assets/34160672/8b852b04-5568-468d-87ce-2e556ac2fc5d)


- When pipeline run is finished, refresh


![Image](https://github.com/nexB/scancode.io/assets/34160672/67014257-7a7d-403f-8798-75fb8bd23f88)





- and click on the "relations" , and you can see the mapping between source and binaries:


![Image](https://github.com/nexB/scancode.io/assets/34160672/c42ff037-4d05-4fd4-ba24-865609df78d7)




- At the resource page, there are also file-level mappings details:
 


![Image](https://github.com/nexB/scancode.io/assets/34160672/f6995025-ab75-40b7-9503-d1f8509e053f)
