### ISSUE TITLE
ScanCode.io: Craft d2d pipeline steps for Go

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1114]
The design is to extend the "map_deploy_to_develop" with a "Go" option  given the framework in:
- #1111

The process will be to:
- [x] Collect Go symbols with the new go-inspector. Completed in https://github.com/nexB/go-inspector/issues/2
- [x] Integrate the Go symbols collection in ScanCode.io
- [x] Create steps in the D2D pipeline to use the Go data for paths-based d2d
- [x] Create reusable pipes to create Go packages inferred from the Go binary data

**Comment by TG1999** [comment]
This is now done and we have a set of proper steps grouped and tagged for Go "binary" analysis that can be selectively used in the context of:
- https://github.com/nexB/scancode.io/issues/1111

The actual Go-specific pipeline steps look like this:

![Image](https://github.com/nexB/scancode.io/assets/34160672/d338434d-4e31-4bb9-b708-db952a03d634)

To test the feature:
- Install ScanCode.io
- Create a new project
- Add these two `Download URLs` exactly as below using these webpacked examples:
  - source:  https://github.com/nexB/scancode.io/raw/main/scanpipe/tests/data/d2d-elf/from-data.zip#from
  - binary: https://github.com/nexB/scancode.io/raw/main/scanpipe/tests/data/d2d-elf/to-data.zip#to
- Select and execute the "map_deploy_to_develop" pipeline, clicking on the Elf option

Here is how the project creation looks like:



![Image](https://github.com/nexB/scancode.io/assets/34160672/4d453ddb-3af3-4470-b6ae-d6251c731d99)




- When pipeline run is finished, refresh




![Image](https://github.com/nexB/scancode.io/assets/34160672/1d080401-3512-478f-9dfd-99b94fca5f73)







- and click on the "relations" , and you can see the mapping between source and binaries:




![Image](https://github.com/nexB/scancode.io/assets/34160672/d28b0b83-3760-49d6-aa98-6f09826a42e6)






- At the resource page, there are also file-level mappings details:
 




![Image](https://github.com/nexB/scancode.io/assets/34160672/38c59bb5-96c5-40ca-b229-95a63dc2c556)
