### ISSUE TITLE
Add quick start in readme

### ISSUE THREAD

**Issue by Aayush-hub** [nexB/scancode.io#113]
Add a clear and concise quick start section in Project Readme itself for beginners to setup project on their local machines.

**Comment by Aayush-hub** [comment]
@tdruez Can I work on adding steps in Readme itself on how to run project on their machines. It will be beneficial for beginners to setup project and contribute to it.

**Comment by mjherzog** [comment]
Our standard is to use RTD for documentation - otherwise you have duplicate information which is likely to be incorrect in at least one location. It is also cleaner to synch code with doc using RTD.

**Comment by majurg** [comment]
There is adequate starting documentation here: https://scancodeio.readthedocs.org/, closing this.

**Comment by Aayush-hub** [comment]
@majurg @mjherzog Sure, will look into it. Looking forward for more contributions.
