### ISSUE TITLE
Failed to import SPDX "PACKAGE-MANAGER" vs. "PACKAGE_MANAGER"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1130]
We cannot import some SPDX docs because of a small mess between 2.3 and 2.3.1 schemas in JSON and other parts.
We also need to decide on the best format for output.

We should accept PACKAGE-MANAGER and PACKAGE_MANAGER on export.

See the mini mess here:
- https://github.com/spdx/spdx-spec/issues/792

Basically thanks to this, both should be supported on reading. 

I am not sure which one is the best to export/write as a standard.

- The JSON schema at https://github.com/nexB/scancode.io/blob/30c1d8ef8ba2fba01d9549e8b1a3a254a91c2ea2/scanpipe/pipes/schemas/spdx-schema-2.3.json#L325 is using dash

- 2.3.1 supports both.
https://github.com/spdx/spdx-spec/blob/8a595028b0386138c84f7188237787c374f6a6cf/schemas/spdx-schema.json#L332

In all cases we would need to support both 2.3 and 2.3.1 import and decide on the most popular output string to use.

**Comment by tdruez** [comment]
Schema updated in https://github.com/nexB/scancode.io/pull/1139
Both "PACKAGE-MANAGER" and "PACKAGE_MANAGER" are now valid.
