### ISSUE TITLE
Delete modal close button not working and cancel button working as delete

### ISSUE THREAD

**Issue by Sagarsangwan** [nexB/scancode.io#116]
Steps to reproduce - 
1. Go to scanpipe project details page "/project/<PROJECT_ID>"
2. Press delete/trash button below project name.
3. ISSUE 1 - Try closing modal using close button. It doesn't work.
4. ISSUE 2 - Press "No, Cancel". It deletes the project.

**Comment by Sagarsangwan** [comment]
Issue fixed in this PR https://github.com/nexB/scancode.io/pull/115

**Comment by tdruez** [comment]
@Sagarsangwan thanks for reporting those issues and for providing a PR. Much appreciated.
See https://github.com/nexB/scancode.io/commit/2b31db6c7bfc536d554b8fe8a0c5671e4f2180b4 for a solution that does not require inline JS.
