### ISSUE TITLE
Project name can have any number of spaces in between words.

### ISSUE THREAD

**Issue by sagarsangwan** [nexB/scancode.io#117]
When creating a new project, this appears to be valid project name - <pre>demo           123       project</pre>

**Issue appears when** - 
- It is shown as `demo 123 project` on UI
- And user try to search using `demo 123 project`. It can't be searched because of extra spaces in project name. Which can not be seen on UI, but is saved in database

""Possible fixes"" - 
- Prevent user from entering multiple spaces in project_name or
- Save cleaned project_name in DB, where extra spaces are removed

**Comment by Sagarsangwan** [comment]
Not sure about the implementation of Fix 1. Tried to fix using 2nd one. PR for this fix https://github.com/nexB/scancode.io/pull/118
