### ISSUE TITLE
SCIO: Lock and resolve locked npm dependencies from yarn and npm

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1201]
We should be able to:
- [x] Resolve locked npm dependencies from yarn and npm lockfiles https://github.com/nexB/scancode.io/pull/1244
- [x] Generate lockfiles for npm and yarn if they are missing https://github.com/nexB/dependency-inspector/pull/7
- [x] Also support pnpm lockfiles resolution https://github.com/nexB/scancode-toolkit/issues/3766

**Comment by AyanSinhaMahapatra** [comment]
This is completed, see [this comment](https://github.com/nexB/scancode.io/issues/1201#issue-2280203996) for the details.
