### ISSUE TITLE
If I search for a resource and prefix the search string with a single quote, I get a 500 error

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1203]
If I search for a resource and prefix the search string with a single quote, I get a 500 error
Same with a double quote

**Comment by tdruez** [comment]
Dup of https://github.com/nexB/scancode.io/issues/1183 ?

**Comment by tdruez** [comment]
Add validation in https://github.com/nexB/scancode.io/pull/1210
An error message is now displayed in place of the 500 error.
