### ISSUE TITLE
CDX SBOM output appends &uuid to the purl field

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#1224]
**Describe the bug**
All version of the CDX SBOM (1.4, 1.5, 1.6) output from SCIO append the package_uid from a Scan to the purl - an example is: pkg:deb/ubuntu/libkrb5support0@1.17-6ubuntu4.4?arch=amd64&uuid=3ee6bb6c-8a74-470c-900b-378f48e70b70. The same value is used for bom-ref and in the dependsOn section of the SBOM.
This format probably makes sense for the bom-ref field, but it is a bug for the purl field because it is an internal "document" reference. I am not sure about the dependency information.
I do not see this bug in the SPDX output.

**System configuration**
- Which version of ScanCode.io are you running? v34.4.0
- Are you running the app using Docker? Yes

**Expected behavior**
SCIO should report a correct purl for a package without scan-specific data.

**Comment by DennisClark** [comment]
See the Project `sh-ubuntu1-docker` for a good example.  When you view the Packages in the SCIO UI, there is no uuid at the end of the purl, but a generated CDX SBOM appends one at the end of the purl for each package.

**Comment by DennisClark** [comment]
Also if you download the (very large) scan results of sh-ubuntu1-docker to xlsx or json, the purl values are what you might expect, without the appended uuid value.

**Comment by tdruez** [comment]
There was a bug where the `bom_ref` value was also used to set the `package_url` field in the CycloneDX output.
Fixed in https://github.com/nexB/scancode.io/pull/1225
