### ISSUE TITLE
Support storing scancode-config.yml files in the scanned codebase

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1236]
We need to allow storing scancode-config.yml files in the scanned codebase and used when running a pipeline.

There are many small edge cases to support:
- when there multiple scancode-config.yml in multiple input archives (multiple "codebases")
- when there are multiple scancode-config.yml inside an input archive
- when there is a direct input scancode-config.yml and other scancode-config.yml in input archives

For now we should support only these cases:
1. If there is a direct input scancode-config.yml file provided, it should be taken and have precedence and all other scancode-config.yml ignored.
2. If there is a single archive input and it has a scancode-config.yml file at the root, it should be used
3. If there are any other scancode-config.yml files elsewhere or more than one file in a single or multiple inputs, we should just report an error, and also in any other cases. 

See also:
- https://github.com/nexB/scancode.io/issues/1197

**Comment by pombredanne** [comment]
And also update the doc accordingly

**Comment by pombredanne** [comment]
@tdruez and I had a chat earlier today to discuss the topic of recursive extraction which is a config option.
If the `scancode-config.yml` is inside an input archive we would to extract it first to determine how we should extract. This is chicken and egg problem.


`recursive extraction` is the default and rarely to never makes sense to disable, therefore we are going remove `recursive extraction` as a `scancode-config.yml` option, and make this issue go away. `recursive extraction` will always take place. 

Therefore we are going to have this revised and refined behavior:

1. If there is a direct input `scancode-config.yml` file provided, it should have precedence and any other `scancode-config.yml` found in the codebase are **ignored**. Same if the config options were provided in the UI.
2. Then if there is a single archive input and it has a `scancode-config.yml` file at the root, it should be used. 
3. Then if there are any other `scancode-config.yml` files elsewhere or more than one file in a single or multiple inputs, we should just report a warning stating that we ignore these config files.

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/1243
