### ISSUE TITLE
SCIO: Resolve npm dependencies based on lockfiles

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1237]
I would like to have a pipeline (likely an addon pipeline) that can resolve the dependencies given this context:
- We have a project with a package.json and a package-lock.json or yarn.lock (and the future pnpm)
- We should be able to create the new "resolved" packages and the relationship using the new models and this data
  - nexB/scancode.io#1066

We also need the same elsewhere:
- [x] nexB/scancode-toolkit#3780

**Comment by AyanSinhaMahapatra** [comment]
This is completed in https://github.com/nexB/scancode.io/pull/1244, closing.
