### ISSUE TITLE
Resource list is not filtered the same way as in the charts

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#124]
I have a project (based on the centos:latest Docker image) and there is a small number of files (86) that are not in a package.
In the main project page, I can select if Codebase Resources are in a package or NOT in a package, and the graphics will be update accordingly. Yet when I click on some graphic (say one of the types in the mime types chart) the list of resources that is displayed is not what I would expect: all the resources are listed for that type. I would expect to see only the list of files not in package with that type.

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/commit/193548b1d671db66d167d47aae55eabed8fa7094
