### ISSUE TITLE
SCIO: Detect frozen Python requirements locked with deplock

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1262]
To support:
- https://github.com/nexB/dependency-inspector/issues/8
- https://github.com/nexB/dependency-inspector/issues/2 

... we need to detect the Python frozen requirements that will be generated. We likely want to define a conventional file name like "frozen-requirements.txt" so we can distinguish this from other standard requirements files. 

This would go in the inspect package pipeline

**Comment by pombredanne** [comment]
There are two ways to approach this:
- just parse the requirements.deplock and use "built-in" dependency resolution as for npm
- or use the Python inspector requirements.deplock

**Comment by pombredanne** [comment]
This is now based in pip inspect... @AyanSinhaMahapatra @TG1999  any update?

**Comment by AyanSinhaMahapatra** [comment]
This was done with:
* SCTK update: https://github.com/nexB/scancode-toolkit/pull/3757 and https://github.com/nexB/scancode.io/pull/1305
* SCIO update: https://github.com/nexB/scancode.io/pull/1244
* deplock update: https://github.com/nexB/dependency-inspector/pull/25 and https://github.com/nexB/dependency-inspector/pull/20 from @keshav-space 
Also added as tests with https://github.com/nexB/scancode.io/blob/main/scanpipe/tests/data/dependencies/resolved_dependencies_pip.json and https://github.com/nexB/scancode.io/blob/main/scanpipe/tests/data/dependencies/resolved_dependencies_poetry_inspect_packages.json
