### ISSUE TITLE
PurlDB package scan worker fails to get next download url from PurlDB

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#1264]
I am running scancode.io using Docker with the `docker-compose.package-scan-worker.yml` config. This Compose file defines a package scan worker that runs this management command (https://github.com/nexB/scancode.io/blob/main/scanpipe/management/commands/purldb-scan-worker.py) This is intended to be run in a loop, but it seems to stop after retrieving one download URL. Looking closer, I see that we do a `sys.exit(0)` (https://github.com/nexB/scancode.io/blob/main/scanpipe/management/commands/__init__.py#L399)

**Comment by JonoYang** [comment]
Changing `sys.exit(0)` to `return` did not immediately fix things. I will delve into this.

**Comment by tdruez** [comment]
`sys.exit(0)` does not make sense in that function, using return instead is fine.

Also, this should have been caught by the CI, we are missing a test for the failing loop.

**Comment by JonoYang** [comment]
Using `return` works here. The issue was I did not rebuild the `package_scan_worker` service when I updated the code, so it was using the previous code that exited out of the program. Running `docker compose -f docker-compose.purldb-scan-worker.yml build web worker purldb_scan_worker` resolves things.

**Comment by JonoYang** [comment]
@tdruez 

The `sys.exit(0)` is in the `run_async` if statement (https://github.com/nexB/scancode.io/blob/main/scanpipe/management/commands/__init__.py#L390). Since we do not run tests with async enabled, this code is never executed. Do you have any suggestions on the best way to test for this case?

**Comment by tdruez** [comment]
@JonoYang unit test added in https://github.com/nexB/scancode.io/pull/1265
