### ISSUE TITLE
Extend scancode-config.yml to ignore some vulnerabilities

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1271]
The same way we can ignore paths and package scopes, it could be useful to ignore certain vulnerabilities in the context of a project. The ignore could be based either on a CVE or in a VCID. It could be useful to also have a comment that explain why we ignore this.

**Comment by tdruez** [comment]
Merged and documented at https://scancodeio.readthedocs.io/en/latest/project-configuration.html#ignored-vulnerabilities
