### ISSUE TITLE
Add notes to a project

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#129]
When I create a project I would like to add some descriptive notes stored with the project and I could not find a way to do that

**Comment by DhruviJ17** [comment]
@pombredanne can I work on this?

**Comment by pombredanne** [comment]
@DhruviJ17 Thank you!
you sure can... can you describe what would be your approach and design here first?

**Comment by DhruviJ17** [comment]
@pombredanne Sure! Firstly I'll add notes attribute in project model and make sure it is accessible from the UI along with making changes in the APIs wherever required.

**Comment by DhruviJ17** [comment]
@pombredanne @tdruez can I go ahead with this?

**Comment by tdruez** [comment]
@DhruviJ17 Sure, PR welcome.

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/756
