### ISSUE TITLE
Enhance documentation to reference new pipeline "options"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1302]
We are adding new "static_resolver" option (aka. group) to the "inspect_package" pipeline and the documentation needs to be updated

This is a follow up of:
- https://github.com/nexB/scancode.io/issues/1066

**Comment by AyanSinhaMahapatra** [comment]
This there now on the docs (with updates in the run command to support this from @tdruez ) with https://github.com/nexB/scancode.io/commit/f56daa287194bea415fbe921ecb5330a9aac0ed4, closing!
