### ISSUE TITLE
Include `libpq-dev` in the installation prerequisties

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#133]
From https://scancodeio.readthedocs.io/en/latest/installation.html , it refer  ScanCode-toolkit Prerequisites (https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#prerequisites) , but it's missing the `libpq-dev` which is required for scancodeio

**Comment by tdruez** [comment]
Added in the docuementation.
