### ISSUE TITLE
Implement timeout on the scan functions

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#135]
Process can get stuck forever at the moment.

**Comment by cco3** [comment]
I started a root_filesystem scan yesterday on a 1GB image (using 21.4.14) and it's still running.  Is this possibly still the same issue?

**Comment by tdruez** [comment]
@cco3 Yes, it's most likely related to multiprocessing, 1GB image should not take more than 1h max.
We are looking into solving those issues at the moment.
In the mean time, could you try to turn off multiprocessing a run the scan again (as a new project)?
See https://scancodeio.readthedocs.io/en/latest/scancodeio-settings.html#scancodeio-processes

**Comment by cco3** [comment]
Hasn't finished after about 5 hours.  There's a report, but the "running" progress indicator is still going and the log is stuck at `Step [scan_for_files] starting`
