### ISSUE TITLE
Extract base pipeline code for reuse in other projects 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#1351]
I would like to reuse the pipeline approach in VulnerableCode and possibly PurlDB as a common way to structure code that imports, improves, collects, visits and maps package and vulnerability data in these tools.

Reusing the pipeline approach will help structure similar code the same way and enable more reuse and easier switch coding between each projects.

See these issues:
- [ ] https://github.com/nexB/vulnerablecode/issues/1509
- [ ] https://github.com/nexB/purldb/issues/521

**Comment by tdruez** [comment]
@pombredanne @keshav-space @TG1999 

`aboutcode.pipeline` 0.1 published to PyPI at https://pypi.org/project/aboutcode.pipeline/
