### ISSUE TITLE
Ensure that ScanCode.io can be installed offline without internet access

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#136]
We have some code to help installation offline but there are sometimes issues in particular with the underlying scancode-toolkit.
This needs to be qualified and should work flawlessly

**Comment by tdruez** [comment]
See also https://github.com/nexB/scancode.io/issues/169

**Comment by tdruez** [comment]
Tested and fixed in https://github.com/nexB/scancode.io/issues/169
