### ISSUE TITLE
meta-issue: design-needed: Finding and acting on issues and exceptions to review in scan

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#137]
Once a scan is completed, I want to be able to efficiently review "issues and exception" in my scan such as:
1. files or packages under a certain license (e.g. possibly in relation with policies #90 )
2. inconclusive detections (such as unknown licenses and similar)
and possibly a few more.

It could take the form of filtered lists or some dashboard that I could "zoom" to and needs design.

The outcome is to identify a number of related files or packages that share some origin and license exception, issues or policy problem.

Once I "zoom in" a problem, I would to be able to act on this such as:
1. changing or setting some status that would state that these resources or packages have been reviewed
2. changing or setting and updated license and or copyright or origin
3. mark a bunch files with some detected clues are having non-relevant clues (say for instance because of an http://example.com URLs)
4. tag files or packages for future extra review or action (something like a TODO list) 
and possibly a few more.

**Comment by tdruez** [comment]
See also https://github.com/nexB/scancode.io/issues/190

**Comment by DennisClark** [comment]
Moving this initiative to a different software project and closing this ticket.
