### ISSUE TITLE
Provide documentation for using a remote database

### ISSUE THREAD

**Issue by cco3** [nexB/scancode.io#139]
It seems the steps would be something like:

- edit scancodeio/settings/base.py to specify the DB info (It would be nice if this imported a json file or something smaller to edit)
- remove db from the services in docker-compose.yml

Not sure if there's more that is needed.

**Comment by tdruez** [comment]
> edit scancodeio/settings/base.py to specify the DB info (It would be nice if this imported a json file or something smaller to edit)

The `.env` file is available to configure the settings, you should never have to edit the `base.py` file. https://scancodeio.readthedocs.io/en/latest/scancodeio-settings.html#scancode-io-settings
You can configure the DB with the following variable in your env:
```
SCANCODEIO_DB_ENGINE
SCANCODEIO_DB_HOST
SCANCODEIO_DB_NAME
SCANCODEIO_DB_USER
SCANCODEIO_DB_PASSWORD
```

**Comment by cco3** [comment]
Thanks!

**Comment by cco3** [comment]
Actually, reopening because this doesn't appear to be explicitly documented.

**Comment by tdruez** [comment]
Added in https://github.com/nexB/scancode.io/commit/8f72a820194155675f9b5af23372477fbac46fad
