### ISSUE TITLE
Embed version info in scancode web UI

### ISSUE THREAD

**Issue by cco3** [nexB/scancode.io#140]
It would be nice if one could tell which version of scancode (or at least which version of the web UI) were running from the web page itself.

Maybe this could just be a light gray number at the button of the page.

**Comment by tdruez** [comment]
Added in the header:
<img width="282" alt="Screenshot 2021-04-09 at 10 47 30 AM" src="https://user-images.githubusercontent.com/489057/114154798-15952b00-9921-11eb-940d-7dd945c5e29a.png">
