### ISSUE TITLE
Close buttons not working on pipeline view

### ISSUE THREAD

**Issue by cco3** [nexB/scancode.io#141]
Neither close button works for me in the pipeline view. (the upper right X and the lower left "close").  To close I have to click off of the popup.

![pipeline-view](https://user-images.githubusercontent.com/236057/114065097-24131200-984f-11eb-9535-05e7fcac5d0c.png)

Running version 21.4.5

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/commit/2b31db6c7bfc536d554b8fe8a0c5671e4f2180b4
