### ISSUE TITLE
CodebaseResourceDetailsView Page not found for scan_codebase pipeline results

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#147]
Note that this is not an issue for the docker and rootfs pipelines. 
Likely related to the codebase/ prefix in the resources path.

**Comment by AvishrantsSh** [comment]
I have been working on this, and yes, it is due to the *codebase/* prefix. The prefix *codebase/* appears twice in the url (line 2).

![Screenshot from 2021-04-09 20-13-16](https://user-images.githubusercontent.com/21276898/114258184-70428b80-99e2-11eb-8188-1f9eda3b2c47.png)

**Comment by AvishrantsSh** [comment]
@tdruez, I have been studying this bug for a while now and here are the possible solutions
1. In `scanpipe.py`, the results are stored in `CodebaseResource` model with `path = resource_data.pop("path")`. This path already contains `codebase` prefix in it. So one solution is to remove the prefix from here.
2. The other solution is to rewrite `codebase_path` property and remove `codebase` prefix from it.

**Comment by tdruez** [comment]
Hi @AvishrantsSh thanks for your input on this one. 

> In scanpipe.py, the results are stored in CodebaseResource model with path = resource_data.pop("path"). This path already contains codebase prefix in it. So one solution is to remove the prefix from here.

Yes that would work, but we also need to remove the prefix in other places such as in `create_discovered_packages` as the codebase resource is retrieve in the db using the path.

> The other solution is to rewrite codebase_path property and remove codebase prefix from it.

That would work as well, the problem with that approach is that we would keep storing the "codebase/" prefix for all codebase resource in the database to then clean it each time. It would be better to not store it in the first place.

----

Both of your solutions would work fine as workaround but a better approach would be to enhance the VirtualCodebase to offer an API that would return paths without the root. `VirtualCodebase.walk(skip_root=True)` is available to not include the root as a resource, but we should add a way to not include the root in all the returned paths.

I'll look at it with @pombredanne on the toolkit side.

**Comment by tdruez** [comment]
@AvishrantsSh see the fix at https://github.com/nexB/scancode.io/commit/4d46a386efcebb43d3413b8142353d33d37ac67d
