### ISSUE TITLE
ScanPipeModelsTransactionTest failure when using SQLite as DB

### ISSUE THREAD

**Issue by AvishrantsSh** [nexB/scancode.io#149]
ScanPipeModelsTransactionTest always fails with  `AssertionError` at `self.assertIsNone(package.id)`. It appears that the `max_length` attribute is not enforced in SQLite itself. This limitation is even mentioned in SQLite docs.
Link : http://www.sqlite.org/faq.html#q9

**Comment by tdruez** [comment]
@AvishrantsSh From https://scancodeio.readthedocs.io/en/latest/installation.html#database

> Choosing SQLite over PostgreSQL has some caveats. See https://docs.djangoproject.com/en/dev/ref/databases/#sqlite-notes for details.

> PostgreSQL is the preferred database backend and should always be used on production servers.

We do not actively run the tests against SQLite but a PR is welcome if you want to fix those failure on SQLite. Otherwise we can close this issue.

**Comment by tdruez** [comment]
@AvishrantsSh Those failing tests are now skip when running on SQLite, see https://github.com/nexB/scancode.io/commit/a7ee9632b54ced3dc53beb35891ac015994168ee
