### ISSUE TITLE
Add size of inputs to summary

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#152]
It would be useful to display the size of inputs to get a feel for the overall size of a codebase.

**Comment by tdruez** [comment]
Inputs size of each input files are already displayed in the UI:
<img width="459" alt="Screenshot 2021-04-19 at 7 28 47 PM" src="https://user-images.githubusercontent.com/489057/115278352-a354ef80-a145-11eb-8126-59ef051d5b52.png">

Are you talking about a different UI location?
