### ISSUE TITLE
Add ability to click from a slice of package type pie chart to navigate to filtered list  for package type

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#157]
Add ability to click from a slice of "Package Type" pie chart to navigate to filtered list  for package type. That would be a very nice addition

**Comment by tdruez** [comment]
This is already available, there was an issue with the display of the packages charts that was solved in https://github.com/nexB/scancode.io/commit/011076c1381dce859e23bf76e773a3cad82ed398
