### ISSUE TITLE
Scanpipe Web UI returns "Bad Request (400)" when accessed from another computer in the network

### ISSUE THREAD

**Issue by yuvarajsanthakumar** [nexB/scancode.io#160]
**Issue:**
I'm using the docker-compose file to build and run scanpipe. When I try to access this instance from another machine in the network by using the IP Address of the machine where scanpipe is running, I always get a "Bad Request (400)" error message. 

**Solution:**
To Solve this problem the Allowed_Hosts property must be modified by adding the domain name. In my case I added the IP Address as I'm access the web UI using the IP and not a domain name. More information about Allowed_Hosts property is available [here](https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-ALLOWED_HOSTS). 

**Code that needs modification:** 
    - https://github.com/nexB/scancode.io/blob/main/scancodeio/settings/base.py#L42
    - Add the domain name or the IP Address with which we are accessing the website.
    - Note: This modification is not required when accessing from the same machine using "http://localhost" or "127.0.0.1". Because this entry is already available.

Can we add this to the documentation if its not already there?

I'm not sure if there is a better solution which doesn't need code modification and can work it around by passing some environment variables. 

P.S: I'm facing this problem when running it in docker. But I think it's applicable when run natively as well.

**Comment by tdruez** [comment]
> I'm not sure if there is a better solution which doesn't need code modification and can work it around by passing some environment variables.

Yes, using the `.env` file and settings your ALLOWED_HOSTS value there. See https://scancodeio.readthedocs.io/en/latest/scancodeio-settings.html#scancode-io-settings

I'll add a note in the docs about the ALLOWED_HOSTS and Docker setup.

**Comment by tdruez** [comment]
Added a warning about ALLOWED_HOSTS in the docs: https://scancodeio.readthedocs.io/en/latest/docker-image.html#run-the-image
