### ISSUE TITLE
Failure of rootfs pipeline with error

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#161]
```
  File "/opt/scancodeio/scanpipe/pipelines/__init__.py", line 122, in save_errors
    yield
  File "/opt/scancodeio/scanpipe/pipelines/root_filesystems.py", line 82, in collect_and_create_system_packages
    rootfs.scan_rootfs_for_system_packages(self.project, rfs)
  File "/opt/scancodeio/scanpipe/pipes/rootfs.py", line 200, in scan_rootfs_for_system_packages
    raise DistroNotFound(f"Distro not found.")
```
This is a container-inspector issue too tracked here https://github.com/nexB/container-inspector/issues/25

**Comment by pombredanne** [comment]
from nexB/container-inspector#25:

> in all cases, checking for system-installed packages should not be dependent on the detected distro. We should try Debian, RPM, etc. and all supported types in all FS and/or layers analyzed in a scancode.io pipeline (which impacts the code here, in scancode-toolkit and in scancode.io)

**Comment by tdruez** [comment]
While the inspector detection issue nexB/container-inspector#25 is now fixed, we have another issue related with extraction.
For example on a qcow2 image, the current extracted content is directly layed out in the codebase/ directory instead of a subdirectory

```
$ ls input/
image.qcow2
```

After running the rootfs pipeline:
```
$ ls codebase/
boot/  
dev/ 
etc/
home/
[...]
```
