### ISSUE TITLE
Add support for Windows containers

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#163]
These are essentially similar to Docker containers with a few twists:
- they contains Windows the OS and Windows-based executables
- the overall footprint is typically larger than Linux
- the packaging is different, except for application packages

They can be seen in Docker hub such as at https://hub.docker.com/_/microsoft-windows-servercore

I think that the approach will be best handled at first in separate specialized pipeline.

Some high level items:
- these containers are hard to download from Linux. And since overall we want a feature to download any container they will benefit from this. This could be either in FetchCode or in Container-Inspector
- there are specific detection of the OS and container layout that might be best handled first in Container-Inspector
- the specific operations of dissecting Windows registries, WindowsPE and similar are likely best handled in ScanCode toolkit

**Comment by pombredanne** [comment]
The latest version of ScanCode Tk adds support for DLL and Windows executable data collection which should be available here anytime now.

**Comment by tdruez** [comment]
@JonoYang is this one completed?

**Comment by JonoYang** [comment]
@tdruez Closing this ticket as we have added Windows container docker pipeline and the associated scancode-toolkit improvements for Windows package detection.
