### ISSUE TITLE
Add documentation on the type of distros/images/OS recognized in specific Docker and rootfs pipelines

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#165]
It would be useful to have specific documentation (possibly pipeline-specific?) that shows explicitly which distros/images/OS are explicitly supported and how deep is the support in question. I could see some sort of table like this one which details our current status as of today:

--------------------

### Status of ScanCode.io docker images and rootfs/VM images pipelines support for operating systems and Linux distributions

Supported operating systems:

- Debian-based Linux distros: Debian, Ubuntu and Debian-derivative
- Alpine
- RPM-based Linux distros RHEL, Fedora, openSUSE/SUSE
- Distroless (Docker images only): partial support, work in progress. System packages do not have installed files details.
- Windows: work in progress for Docker images only.
- Yocto, OpenWRT: work in progress

There is work in progress to improve the quality of license detection for Debian.

For each support OS we collect in general this information:

- OS and image details-
- Installed system packages and their files
- Installed application packages and their files
- Details for files not part of a package

**Comment by hyounes4560** [comment]
@pombredanne Can we discuss this in more detail? Live session, maybe?

**Comment by mjherzog** [comment]
Since this is likely to be dynamic content for some time, we want to document in a separate Roadmap or similar document file inside the project.

**Comment by mjherzog** [comment]
@pombredanne @tdruez  Would it make sense to start by documenting this at the pipes level rather than pipelines? The current pipes in the RTD doc already have some platform/container-specific pipes so we could add this at the top of each pipe section.
Then we could summarize at a higher level in a new Status/Roadmap section. We need this in some structure where it will be easy to update bi-weekly or so for the near future.

**Comment by tdruez** [comment]
> Would it make sense to start by documenting this at the pipes level rather than pipelines?

It would be nice to start with an overview of the supported platform/distro/images in ScanCode.io without having to go deep in the pipes section.

Those support are generally not at the pipes level nor pipelines but rather depending on external apps like container-inspector and extractcode for example.

**Comment by pombredanne** [comment]
To reformulate, I think we need:
1. a high level summary of supported technologies combos some of which may be only for some pipelines. This should cover not only OS but also later the set programming languages and supported application packages we support
2. at a lower level, we need to get more detailed information about the specifics of how a technology is supported: for instance, for Debian, we collect installed packages, and for each package we collect installed files; we detect licenses in .., etc.

**Comment by tdruez** [comment]
@pombredanne I've started a branch and added a draft of the new chapter at https://github.com/nexB/scancode.io/commit/a46c9ef5ac349b4a223ce3aeb1081a89c0d2f95b

Could you take over to update, refine and format the content?

**Comment by hyounes4560** [comment]
@tdruez of course; Thank you

**Comment by tdruez** [comment]
@hyounes4560 This is actually for @pombredanne this time ;)

**Comment by hyounes4560** [comment]
my bad ;)
