### ISSUE TITLE
Improve RTD installation documentation

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#167]
https://scancodeio.readthedocs.io/en/latest/installation.html
it states "PostgreSQL" is optional, but if I follow the instruction without installing the postgreSQL, I will get the following error:
```
~/scancode.io$ make postgres
-> Configure PostgreSQL database
-> Create database user 'scancodeio'
sudo -u postgres createuser --no-createrole --no-superuser --login --inherit --createdb scancodeio || true
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
sudo -u postgres psql -c "alter user scancodeio with encrypted password 'scancodeio';" || true
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
-> Drop 'scancodeio' database
sudo -u postgres dropdb scancodeio || true
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
-> Create 'scancodeio' database
sudo -u postgres createdb --encoding=utf-8 --owner=scancodeio scancodeio
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
Makefile:95: recipe for target 'postgres' failed
make: *** [postgres] Error 1
```
Although it's obvious `make postgres` will fail as no postgres is installed, I found it somehow confusing with the "optional" word in the installation. Perhaps we should make some notes about the requrirement to have postgres or sqlite installed for the desire database?

**Comment by tdruez** [comment]
PostgreSQL installation is optional when using SQLite as a database. It is required for using PostgreSQL as the local database (but it may not be required neither if your database is located on another server for example).

Anyway, I agree with you, we should improve the documentation being more explicit to remove any confusions.

**Comment by pombredanne** [comment]
@hyounes4560 I would say that SQLite is a single user, single threaded database. Therefore it should only be used for small scale one-off testing IMHO. Any serious usage would need a PostgreSQL instance for production use.
