### ISSUE TITLE
Offline installation is not working for Ubuntu18.04

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#169]
https://scancodeio.readthedocs.io/en/latest/offline-installation.html

OS: Ubuntu 18.04.5

I got the following error when I do the `make install` with the offline installation guide.
```
  Could not find a version that satisfies the requirement pyinstrument-cext>=0.2.2 (from pyinstrument==3.4.1->scancodeio==21.4.28) (from versions: )
No matching distribution found for pyinstrument-cext>=0.2.2 (from pyinstrument==3.4.1->scancodeio==21.4.28)

  Could not find a version that satisfies the requirement MarkupSafe>=0.23 (from scancode-toolkit[packages]==21.3.31->scancodeio==21.4.28) (from versions: )
No matching distribution found for MarkupSafe>=0.23 (from scancode-toolkit[packages]==21.3.31->scancodeio==21.4.28)

  Could not find a version that satisfies the requirement pycryptodome>=3.4 (from scancode-toolkit[packages]==21.3.31->scancodeio==21.4.28) (from versions: )
No matching distribution found for pycryptodome>=3.4 (from scancode-toolkit[packages]==21.3.31->scancodeio==21.4.28)

  Could not find a version that satisfies the requirement extractcode-libarchive>=3.5.1.210223; extra == "full" (from extractcode[full]>=21.2.24->scancode-toolkit[packages]==21.3.31->scancodeio==21.4.28) (from versions: )
No matching distribution found for extractcode-libarchive>=3.5.1.210223; extra == "full" (from extractcode[full]>=21.2.24->scancode-toolkit[packages]==21.3.31->scancodeio==21.4.28)

etc...
```
(Note that the above list is not completed)
I resolved some of the above errors by downloading the following .whl files
```
https://files.pythonhosted.org/packages/96/df/f5bfb7cdfa7907b037f4fab6f9d18260b759f9184e2ce59bc5f45c5eef11/pyinstrument_cext-0.2.4-cp36-cp36m-manylinux1_x86_64.whl
https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
https://files.pythonhosted.org/packages/af/ef/bedde9b7a1f237b743eb307e6c247369c2ae5ca6a79b61c064698cfd78cd/pycryptodome-3.10.1-cp35-abi3-manylinux1_x86_64.whl
...
```

The error is likely caused by the `*-manylinux2010*.whl`, `*-manylinux2014*.whl` etc which were created during the `make package` while the tool doesn't recongize or doesn't like it when it moved to a offline machine and do the `make install`, but having the `*-manylinux1*.whl` seems to have it solved.

I don't know what's the porper to fix it, but it seems when one do the `make package`, the tool shoulds download the `*-manylinux1*.whl` instead of the  `*-manylinux2010*.whl`, `*-manylinux2014*.whl`

**Comment by tdruez** [comment]
@chinyeungli could you try to run `make virtualenv` before running the `make install`?

**Comment by chinyeungli** [comment]
@tdruez `make virtualenv` does the trick.
it runs well after doing the `make virtualenv`

**Comment by tdruez** [comment]
@chinyeungli Great, let me make the change in the Makefile.

**Comment by tdruez** [comment]
@chinyeungli Makefile and documentation updated. Could you retry the installation process from scratch following the update documentation to confirm the fixes?
https://scancodeio.readthedocs.io/en/latest/offline-installation.html#offline-packaging-and-installation

**Comment by chinyeungli** [comment]
@tdruez I confirm the installation process is now working smoothly. Thanks.
Re the doc:
https://scancodeio.readthedocs.io/en/latest/offline-installation.html#offline-upgrade
typo
```
Grab the installable archive in dist/scancodeio-21.4.28.tar.gz and move that to you offline install server.
```
should be 
```
move that to *your* offline install server.
```


In addition, seems like "python3-venv" should be included in the require package in the installation (https://scancodeio.readthedocs.io/en/latest/installation.html#system-dependencies)
```
thomas@thomas-VirtualBox:~/scancode-offline/scancodeio-21.4.28$ make install
-> Install and configure the Python env with base dependencies, offline
python3 -m venv .
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/thomas/scancode-offline/scancodeio-21.4.28/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Makefile:63: recipe for target 'install' failed
make: *** [install] Error 1
thomas@thomas-VirtualBox:~/scancode-offline/scancodeio-21.4.28$ 
```

**Comment by tdruez** [comment]
> In addition, seems like "python3-venv" should be included in the require package in the installation

The `python3 -m venv .` line was removed from the Make `install` command in favor of the `virtualenv` based on the bundled virtualenv.tgz
Can you make sure you are running the latest version of the code?

The goal of that change is to not depend on the `python3-venv` system package, as this one does not include that latest pip.

**Comment by chinyeungli** [comment]
@tdruez I've confirmed `python3-venv` is not needed. Thanks for the fix.
