### ISSUE TITLE
Support to give docker pull command to scan docker image

### ISSUE THREAD

**Issue by sameer1046** [nexB/scancode.io#174]
Currently it only support upload tar file.
The user should give the docker image name and tag while creating project and the tool should pull the image from backend if docker is already installed in the machine.

**Comment by tdruez** [comment]
@sameer1046 Good idea, PR welcome :)

**Comment by pombredanne** [comment]
@sameer1046 @tdruez actually there is a ticket for this and as it happens I am working on this.

This is going to be based in part on this https://github.com/nexB/container-inspector/blob/main/src/container_inspector/fetch/docker_image.py and https://github.com/containers/skopeo and the input will a `docker://` URL and it will not require to have docker installed locally nor to have root privileges. I thought I had a ticket for this, but this is only mentioned here https://github.com/nexB/fetchcode/issues/41

So I will use your ticket for tracking then.

Your use case would be for the server-side locally pulled Docker images? Can you elaborate a bit more?

**Comment by pombredanne** [comment]
@sameer1046 this is now part of the latest release https://github.com/nexB/scancode.io/releases/tag/v21.5.12 if you can try it.
Basically you can input a URL in this style: `docker://debian:buster-slim` like below. Just take anything you would `docker pull xxx` and use  `docker://xxx` instead.

![Screenshot from 2021-05-12 23-23-56](https://user-images.githubusercontent.com/675997/118046151-382fbf00-b379-11eb-9174-5c96f1957034.png)

**Comment by sameer1046** [comment]
NICE!!!

**Comment by sameer1046** [comment]
Feature Implemented
