### ISSUE TITLE
Failed install: OSError: [Errno 36]: filename too long

### ISSUE THREAD

**Issue by silverhook** [nexB/scancode.io#179]
I just tried to install following the [instructions](https://scancodeio.readthedocs.io/en/latest/installation.html#installation), but it fails at `make dev` with the following error

```
ERROR: Could not install packages due to an OSError: [Errno 36] Filename is too long: '/home/hook/Scanning/Tools/scancode.io/lib/python3.8/site-packages/licensedcode/data/rules/epl-2.0_or_apache-2.0_or_gpl-2.0_with_classpath-exception-2.0_and_gpl-2.0_with_openjdk-exception_and_bsd-new_and_mit_and_gpl-3.0-plus_with_autoconf-simple-exception_1.RULE'

make: *** [Makefile:50: conf] Error 1
```

**Comment by pombredanne** [comment]
@silverhook Hiya! The practical path length limitations of a Linux path is typically 4096 and a 255 bytes file name length limit. 

What is your filesystem setup?

The file "epl-2.0_or_apache-2.0_or_gpl-2.0_with_classpath-exception-2.0_and_gpl-2.0_with_openjdk-exception_and_bsd-new_and_mit_and_gpl-3.0-plus_with_autoconf-simple-exception_1.RULE" name is 171 characters and could be made smaller alright.

**Comment by silverhook** [comment]
> What is your filesystem setup?

ext4 on that machine

**Comment by pombredanne** [comment]
@silverhook are you using some non UTF-8 locale or some disk encryption?

**Comment by pombredanne** [comment]
@silverhook because ext4 should have no issue with this by default.

**Comment by silverhook** [comment]
It should be UTF-8, but the partition is encrypted, yes.

**Comment by pombredanne** [comment]
> It should be UTF-8, but the partition is encrypted, yes.

You likely are hitting this limit of 143 characters rather than 255.
Which distro and which version do you use? So we can add that to a FAQ.

See also:
https://askubuntu.com/questions/728465/how-can-i-increase-ubuntus-143-byte-file-name-limit-for-encrypted-directories
https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs/32834#32834

Note that I pushed some updates preventively in scancode-toolkit proper to shorten a few paths that were at play anyway https://github.com/nexB/scancode-toolkit/commit/22337a44cb501e829009f163eb407fe156a5f10c

**Comment by pombredanne** [comment]
https://github.com/nexB/scancode-toolkit/commit/22337a44cb501e829009f163eb407fe156a5f10c has landed in ScanCode TK develop branch now.

**Comment by silverhook** [comment]
> > .
> 
> You likely are hitting this limit of 143 characters rather than 255.

Just checked and it seems I actually have 255 characters supported:

```
➜  ~ getconf NAME_MAX /dev/sda
255
```

> Which distro and which version do you use? So we can add that to a FAQ.

KUbuntu 20.04 LTS

**Comment by pombredanne** [comment]
@silverhook the issue is encryption ... so we shortened all the long rule names in ScanCode TK and this has now landed here in v21.6.10

Do you mind to give it another try?

**Comment by silverhook** [comment]
The 21.6.7 release Linux tarball with Python 3.6 works, thanks :)

I haven’t tried installing from source again since, but feel free to close this issue.

**Comment by pombredanne** [comment]
@silverhook great! 21.6.7 would be ScanCode Toolkit... not the ScanCode.io web UI here. If you can test it too that would be great!

**Comment by silverhook** [comment]
:facepalm: my bad. Let me try that again.

**Comment by silverhook** [comment]
Works now, thanks. Can confirm that I can install and run 21.6.10 on (K)Ubuntu 20.04 LTS.
