### ISSUE TITLE
ProjectCodebase.root() fails when called on a project created using the scan_codebase pipeline

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#180]
I am implementing a `walk()` method on the `CodebaseResource` and `ProjectCodebase` models that is analogous to the `Resource` and `Codebase` models from commoncode. I decided to try the `walk()` methods on a Project that I created using the  `scan_codebase` pipeline. I created another pipeline that instantiates a `ProjectCodebase` instance and then tried using the `walk()` method, but I get the following exception: `Codebase root cannot be determined.` (https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/codebase.py#L71)

This is happening because the root is being stripped when the `CodebaseResource` is being created in the `scan_codebase` pipeline. I do not think the root should be stripped when scanning a codebase in order to preserve directory structure and to allow us to perform tree operations (for example, creating a Merkle tree from a Codebase).

**Comment by JonoYang** [comment]
After discussing with @tdruez and @pombredanne, the root CodebaseResource of a project has the path and name of ".". 

The "." CodebaseResource should be created when a pipeline is run. Ideally, "." should be created when a Project is created, but that can't happen since CodebaseResource requires the Project model.

**Comment by pombredanne** [comment]
@JonoYang do you think you can handle this for the next milestone? e.g. with an ETA sometimes next week?

**Comment by JonoYang** [comment]
This is pretty close to completion. We are failing the tests `test_scanpipe_pipes_codebase_get_tree` and `test_scanpipe_pipes_scancode_replace_root_path_and_name`. This is due to `replace_root_path_and_name` breaking whatever VirtualCodebase is passed into it. `replace_root_path_and_name` strips the root path segment from Resources and on the root resource, it renames it as ".". However, once the root is renamed to ".", we cannot walk the VirtualCodebase anymore since none of the Resources in the codebase start with ".".

An idea would be to remove `replace_root_path_and_name`, which is just used for the `get_tree` test, and then we just modify the expected test output for get_tree by removing the root path segment on non-root Resources and replacing the root path with "." on the root Resource. The only issue with this is that we wouldn't be able to import a JSON scan generated by scancode.io into scancode-toolkit using the `--from-json` option.

**Comment by JonoYang** [comment]
Thinking out loud, in the case where `strip_root` is true, if a Resource is a root Resource, then we can explicitly state the child Resources of the root rather than having the root determine its children from its own path.

**Comment by mjherzog** [comment]
The simplest use case here is to import an SCIO JSON file created on SCIO instance A into SCIO instance B (same SCIO versions). The immediate reason for this is to use the SCIO instance B Web UI when it is difficult to share access to the Web UI for SCIO instance A. I was hoping that it might be as simple as copying the data from one DB instance to the other without any other processing.

**Comment by JonoYang** [comment]
Closing this for now as #624 has been merged in.
