### ISSUE TITLE
Web UI workbench for manual review

### ISSUE THREAD

**Issue by sameer1046** [nexB/scancode.io#187]
fosslight is a new tool with nice UI and uses scancode-toolkit internally.

https://github.com/fosslight/fosslight

The audit UI in Foss lite can be reused to make a functional audit work bench

**Comment by pombredanne** [comment]
@sameer1046 Thanks... yet I see several issues there:
1. the license is AGPL-3.0 and not Apache-2.0
2. the app is written in Java and the UI in JSP which is somewhat far from a Django UI technology-wise

That said, what are the nice UI parts that you see could be integrated or reused in ScanCode.io>

**Comment by sameer1046** [comment]
Yes its not feasible technically as well as legally

**Comment by pombredanne** [comment]
@sameer1046 I would be interested to understand the specific aspects of the UI that you like though as we could learn from that for sure.

**Comment by sameer1046** [comment]
Hi @pombredanne 

We would like to have feature to correct unknown license reference in the UI.

**Comment by pombredanne** [comment]
@sameer1046 yes!
Actually we could do even better... in many cases these should not even be returned. May be we can automate most of it? It would be even better than having a correction UI (which we need too anyway: could you start a separate ticket so we can design this?)

See also #1675 where we have these several ideas of interest:

- Follow and resolve "See license in COPYING" and similar references to the actual license tracked in #1364
- Properly handle "intro texts" that are used generically to introduce license terms. We now have tagged with `is_license_intro` all such license detection rules and the usage would be to "merged" such license intro reference in the following detected license. This is already something applied in Debian copyright files in https://github.com/nexB/scancode-toolkit/blob/132e6b8cf3e173aaa1bfecbd624f228b8aa55b5b/src/packagedcode/debian_copyright.py#L1404 and this helps a lot!

**Comment by sameer1046** [comment]
Sure. I will create a issue. Closing this. Thanks 6

**Comment by sameer1046** [comment]
#102

**Comment by pombredanne** [comment]
OK, got it!
This is closed to the benefit of https://github.com/nexB/scancode.io/issues/102
