### ISSUE TITLE
Review and improve Docker Image (command line) Tutorial 

### ISSUE THREAD

**Issue by hyounes4560** [nexB/scancode.io#199]
A key question is how much we need to show sample results for most steps. This would require a commitment to a specific use case, but new users would appreciate some way to track that they are getting the expected results as they go. At a higher level, we need to confirm that the steps work.

**Comment by mjherzog** [comment]
Lets start with debian-buster-slim  - https://hub.docker.com/_/debian?tab=tags&page=1&name=buster-slim&ordering=last_updated

**Comment by tdruez** [comment]
@hyounes4560 @mjherzog I'm not convinced about the value of adding images in the docs to display the command lines features in the tutorials.

It takes a lot of space, will likely be quickly outdated, and will require some work to keep up to date, while not adding much value on top of the actual command text.

For examples:
<img width="727" alt="Screenshot 2021-06-24 at 6 00 58 PM" src="https://user-images.githubusercontent.com/489057/123276848-9b834400-d516-11eb-9d4f-9464b2a4af1c.png">

<img width="717" alt="Screenshot 2021-06-24 at 6 05 13 PM" src="https://user-images.githubusercontent.com/489057/123276978-be155d00-d516-11eb-9984-66a767ff50ee.png">

**Comment by mjherzog** [comment]
@tdruez I am not particularly fond of screenshots, but we need some to show the reader what the command output should look like, not just the input. Now is the time to figure out the best approach.

**Comment by hyounes4560** [comment]
> @tdruez I am not particularly fond of screenshots, but we need some to show the reader what the command output should look like, not just the input. Now is the time to figure out the best approach.

I think we should some sort of "**Agreement**" of should be added here! so that it can be used in other tutorials as well!

**Comment by tdruez** [comment]
In case of command line instructions, a screenshot does not add any value: it's hard to maintained and you cannot copy it's content. 
The layout of the commands rendered in the documentation is good enough to display the input commands and expected results.

It's ok to use screenshots to present specific part of the UI though, but let's try to keep those to a minimum and avoiding the trap of making screenshots of the whole app. 

Also, in some cases, a short video could be more valuable than many pages of screenshots.

A good reference for tutorials (and documentation in general) is the Django one: https://docs.djangoproject.com/en/3.2/intro/tutorial01/
Screenshots are used toward then end of tutorial 2 to present the admin UI but not needed for all the code and command line presented prior.

**Comment by tdruez** [comment]
@hyounes4560 I've replace the screenshot by simple console outputs. Your changes are merged and deployed.
Thanks for your contribution  :)

@mjherzog The latest update on the tutorial document are available at https://scancodeio.readthedocs.io/en/latest/scanpipe-tutorial-1.html
Let us know if we can close this one.
