### ISSUE TITLE
Add SCIO Output section for Tutorials

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#201]
The review of Scan results is logically separate from whether you use CLI or UI to run SCIO so we need a separate documentation section for SCIO Output. There are two logical subsets for this documentation element:
- Use the SCIO "console" to review Scan data or run reports
- Use files exported from SCIO - typically either JSON or the new Excel format. The Tutorial needs to cover the basics of creating these files and using them, but the primary data dictionary-level documentation should be in the Reference section

**Comment by tdruez** [comment]
@mjherzog The new "Output" documentation is available at https://scancodeio.readthedocs.io/en/latest/scanpipe-output.html for review.

**Comment by hyounes4560** [comment]
@tdruez @pombredanne I think this should be marked as closed.
