### ISSUE TITLE
Ability to "archive" projects

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#205]
Once the work is done a project, it could be marked as "archived":
- This would prevent any future modifications to that project (frozen state)
- Archived projects would not be displayed by default in the main project list (similar to closed GitHub issues for example)
- Several level of data cleanup would be possible during the "archive" operation: deletion of inputs, codebase, and database rows. This could address #154
- The archive mechanism will be available through the web UI, REST API, and the command line

**Comment by pombredanne** [comment]
@cco3 ^ FYI... this is a new design idea.
