### ISSUE TITLE
Failure to open project XLSX in MSFT  Excel on Windows

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#206]
I scan OK https://files.pythonhosted.org/packages/94/40/c396b5b212533716949a4d295f91a4c100d51ba95ea9e2d96b6b0517e5a5/urllib3-1.26.5.tar.gz  with the `scan_codebase` pipeline.
I then fetch the project XLSX and open it in a VM on Windows with MSFT Office and I get a message that the document is corrupted.
It is because the package description exceeds 32767 characters length which is a limit in Excel.
XlsxWriter should truncate these but does not here.
We should also report an error in anycase rather than truncate silently.

**Comment by pombredanne** [comment]
There is a bug in XlsxWriter tracked here: https://github.com/jmcnamara/XlsxWriter/issues/812

**Comment by tdruez** [comment]
@pombredanne This one is fixed, right?

**Comment by tdruez** [comment]
Fixed confirmed.
