### ISSUE TITLE
 Project data text box should be extensible

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#210]
The Project data text box size is fixed and IMHO it would help if it were:
1. extensible both in length and width
2. to help with looking at the data and possibly copy/paste or saving it, it would be great to have a way to open that text (may be raw) in a separate window

**Comment by ayushk26** [comment]
Hey, can I try this issue?

**Comment by pombredanne** [comment]
@ayushk26 It would be great. What's your approach for this?

**Comment by ayushk26** [comment]
I went through the code within the template folder, and I am not sure about where the input regarding project data was given. Could you please help me with it.

**Comment by prathamaror** [comment]
I was thinking about using tkinter to get the job done I have a pretty good idea how things are gonna transcend should I start working on this? I have some questions prior to that

**Comment by pombredanne** [comment]
@prathamaror we do not use tkinter .... this is a Django web page for the project details from https://github.com/nexB/scancode.io/blob/20e8057b46ee62066b940acc1753a49aa803b2e3/scanpipe/views.py#L150 and using this template https://github.com/nexB/scancode.io/blob/20e8057b46ee62066b940acc1753a49aa803b2e3/scanpipe/templates/scanpipe/project_detail.html#L84

**Comment by prathamaror** [comment]
[https://github.com/nexB/scancode.io/pull/392](url)

**Comment by prathamaror** [comment]
#392

**Comment by prathamaror** [comment]
#392 do review and let me know if there are any further changes needed

**Comment by prathamaror** [comment]
https://github.com/nexB/scancode.io/pull/392#issue-1113181502

**Comment by RishiPratap** [comment]
Hi there can you assign me this issue

**Comment by AyanSinhaMahapatra** [comment]
You don't need to be `assigned` for creating PRs for an issue, just us know how you're solving the issue and go for it.

**Comment by AkshayMuthal** [comment]
Hello, is this issue still open?

**Comment by AkshayMuthal** [comment]
Hi @pombredanne, I have raised a MR for this issue. Please do let me know if any changes/suggestions are there from your end.
https://github.com/nexB/scancode.io/pull/667

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/777
