### ISSUE TITLE
Cannot browse subset of problematic resources easily

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#217]
When I browser resources, I would like for instance to see only files that are  "NOT in a package" and with NOT the status  "ignored-not-interesting". And I cannot exclude with filters.

**Comment by tdruez** [comment]
You can now use the advanced search syntax:

https://scancodeio.readthedocs.io/en/latest/user-interface.html#search-syntax

1. Use the `Not in a package` filter from the table header
2. Use the "Negate" syntax to exclude the status with `-status=:ignored-empty-file` in the search bar

You can also exclude all the "ignored" statuses with `-status:ignored`.
