### ISSUE TITLE
`matched_rule` key error in custom pipelines

### ISSUE THREAD

**Issue by AvishrantsSh** [nexB/scancode.io#224]
Apparently, `get_annotation_text` method of `CodebaseResourceDetailsView` requires a key named `matched_rule` in the field `licenses`.
```
@staticmethod
    def get_annotation_text(entry, field_name, value_key):
        """
        Workaround to get the license_expression until the data structure is updated
        on the ScanCode-toolkit side.
        https://github.com/nexB/scancode-results-analyzer/blob/6c132bc20153d5c96929c
        f378bd0f06d83db9005/src/results_analyze/analyzer_plugin.py#L131-L198
        """
        if field_name == "licenses":
            return entry["matched_rule"]["license_expression"]
        return entry[value_key]
```

However, considering that some pipelines may or may not provide information in this format (like `glc_scan` pipeline in `glc` branch), is it necessary to do some sort of conversion to match the formatting?

The same goes for other fields like `start_line` and `end_line`.
A workaround to this error might be using Dict `get()` method to prevent such kind of errors.

**Comment by tdruez** [comment]
@AvishrantsSh thanks for reporting. That code was indeed not written to support other sources of results data.
Fix pushed in main branch https://github.com/nexB/scancode.io/commit/03093cdb4bacb2b233f5639e9b2df912d7b19a00
Let me know if that solve you issue.
