### ISSUE TITLE
Create pipe for filtering

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#232]
We want to create a new pipeline that queries the resource and license data to generate a list of proprietary & commercial licenses and the files associated with those licenses.

**Comment by tdruez** [comment]
@chinyeungli I've added a QuerySet filter method to lookup codebase resources by licenses categories.

You can now filter using the following:

```
categories = ["Commercial", "Proprietary Free"]  # Update this list with your needs
resources = project.codebaseresources.licenses_categories(categories)
```

**Comment by tdruez** [comment]
See also https://scancodeio.readthedocs.io/en/latest/custom-pipelines.html#custom-pipeline-example for more examples.
