### ISSUE TITLE
`make dev` in installation guide for non-dev install

### ISSUE THREAD

**Issue by Hritik14** [nexB/scancode.io#236]
The installation guide asks to do `make dev` (https://scancodeio.readthedocs.io/en/latest/installation.html#prerequisites). Is it really required for a non developmental installation ?

**Comment by hyounes4560** [comment]
@Hritik14 I run `make dev` when contributing to the documentation! SO I assume it's required!

**Comment by Hritik14** [comment]
@hyounes4560 Yes, it's required during development but ideally `make conf` should do from user perspective.

**Comment by tdruez** [comment]
@Hritik14 the installation docs https://scancodeio.readthedocs.io/en/latest/installation.html# was re-organized and the `make dev` is only required for the "developpement" installation.
