### ISSUE TITLE
Windows Docker image analysis techniques

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#238]
The Docker pipeline in scanpipe should be extended to analyze Windows Docker images in the same way we analyze Debian Docker images. Since Windows does not use a central package manager or any other type of system to manage installed packages, we must use a variety of techniques to find installed packages.

1. Report MSI installer files as packages. 
    - Package name and version can be obtained from metadata from MSI installers
    - https://github.com/nexB/scancode-toolkit/issues/2559 - PR: https://github.com/nexB/scancode-toolkit/pull/2582
2. Report installed programs from Windows registry files
    - Installed programs on Windows creates an entry in the `Add/Remove programs` part of the Control Panel. We can read the registry location where that information is stored to get package name and versions
    - https://github.com/nexB/scancode-toolkit/issues/2565 - PR: https://github.com/nexB/scancode-toolkit/pull/2582
3. Report Microsoft Update Manifest (.mum) files
    - These files contain information about Microsoft updates that are downloaded
    - PR: https://github.com/nexB/scancode-toolkit/pull/2582
4. Ignore uninteresting files
    - We should tag files like `desktop.ini`, `Thumbs.db`, registry files, etc. as uninteresting and something that can be ignored because they do not contain information about third-party packages
5. Check common file locations for third-party software
    - For example, Python installs itself to the root drive under the `Python27` or `Python<version>` directory. openjdk is similar. We can have a collection of these paths 
6. Use the NSRL (https://www.nist.gov/itl/ssd/software-quality-group/national-software-reference-library-nsrl) to match known files from software packages
    - We can check file hashes against this database
7. Parse swid files and swidtags

**Comment by JonoYang** [comment]
Regarding #6, the NSRL does not seem to index the container version of Windows. The latest version of Windows on record in the collection is the ISO contents of version 1903. Most of the indexed Windows system files are for versions released before 2019.

**Comment by tdruez** [comment]
@JonoYang can we close this one?

**Comment by JonoYang** [comment]
@tdruez Yep. These features have been merged in.
