### ISSUE TITLE
design-needed: Add GUI to review scanpipe results 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#24]
We should have some UI that's better than the JSON API and better than the Django Admin.
May be something such as the scancode-workbench?

**Comment by JonoYang** [comment]
I think using the scancode-workbench layout as a start is a good idea. It has the basics in terms of how we want to view/filter Resource data. I find using the tree view on the side to navigate/filter for the files under a certain directory to be a more intuitive/quicker way to navigate the rows of data.
