### ISSUE TITLE
Allow URL navigation with CodebaseResource path

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#242]
When I browse resources the browser URL looks like http://localhost:8080/project/6befcc5c-7ee5-4812-ab6d-a6c8070c3207/resources/390058/
It would be nice and useful if I could see (and possibly use and change) the actual path of the resource in the URL rather than just its id of `390058`

**Comment by tdruez** [comment]
Added in https://github.com/nexB/scancode.io/commit/db7749d020202f29b30ef02183dc8879ce2cace9
