### ISSUE TITLE
Consider better names for documentation than "Installation" and "Run with Docker"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#245]
The doc sections named "Installation" and "Run with Docker" may benefit of a better title.
- "Installation" is really about installing on a local server or a development/test installation
- "Run with Docker" is about using docker and docker images and docker compose and can also be used for testing or production.
Clarifying which to use when and why would be useful

**Comment by Hritik14** [comment]
I was just about to create a ticket for the first point. [`make run`](https://scancodeio.readthedocs.io/en/latest/installation.html#web-application) starts a development server which should be made explicit (either by a note or by mentioning directly that this is not the correct way to deploy in production. A reference to gunicorn or uwsgi could be added).

The docker option appears suited for production but yes, it should be made explicit as well.
Also, the first line in "Run with docker" says :
>Running ScanCode.io with Docker containers is the preferred setup and ensure that all the features are available and working properly.

 Is it really the case?
