### ISSUE TITLE
Queued scans do not run after deleting a running scan

### ISSUE THREAD

**Issue by cco3** [nexB/scancode.io#248]
To reproduce:

1. Upload image 1 / start scan
2. Upload image 2 / start scan
3. Delete image 1
4. Notice that image 2 is still queued

More details:
- In my instance both were `qcow` images running a rootfs scan.
- I performed all operations with the web UI
- Version: v21.6.10

**Comment by pombredanne** [comment]
@cco3 did you use the CLI or the UI to delete your project?

**Comment by cco3** [comment]
UI.

**Comment by cco3** [comment]
This is a distinct issue, but I imagine this will be fixed when #130 is fixed.

**Comment by tdruez** [comment]
@cco3 Project with currently running or queued pipelines cannot be deleted anymore.
There's also the ability to stop a running pipeline and delete queued pipeline https://github.com/nexB/scancode.io/issues/176

Those new features are available in the latest release:
https://github.com/nexB/scancode.io/releases/tag/v30.0.0

**Comment by cco3** [comment]
Sorry, by "instance" I mean the docker containers that run the queue/webserver.
