### ISSUE TITLE
Add a basic extract and scan pipeline 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#25]
This would eventually replace the scanner API.
- We have today an older "scanner" API that can scan a single package and this is NOT using the scanpipe pipelines. It would would make sense to use pipelines also for this

**Comment by tdruez** [comment]
New pipeline available:
<img width="672" alt="Screenshot 2021-07-08 at 1 56 34 PM" src="https://user-images.githubusercontent.com/489057/124902781-540bb600-dff4-11eb-8900-33ba77eec36d.png">
