### ISSUE TITLE
Revisit ignores and "junk" files tagging

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#252]
We should consider reusing commoncode ignores https://github.com/nexB/commoncode/blob/430cf8362d5055a72595410a5e10e61c1b492266/src/commoncode/ignore.py#L67 

In many case we should also attach a reason message on why we ignore a certain file

**Comment by JonoYang** [comment]
This has been added to scancode.io in `scanpipe.pipes.rootfs`
