### ISSUE TITLE
Consider adding test_file_path parameter while installation

### ISSUE THREAD

**Issue by AvishrantsSh** [nexB/scancode.io#253]
In continuation of https://github.com/nexB/scancode.io/pull/226, is it possible to have another installation parameter that points to **test files** for that pipeline? These tests can then be run alongside Django tests for simplicity. 

It would certainly help the installation of custom pipelines.

**Comment by AvishrantsSh** [comment]
One solution might be to add the module as an app within Django. So test cases will be automatically handled.

**Comment by tdruez** [comment]
@AvishrantsSh could you describe the issue. I see you have solution ideas but the problem you're facing is not clear.

**Comment by AvishrantsSh** [comment]
@tdruez, if we wish to make an add-on type functionality for newer pipelines in the form of python modules, I think it would be better to have test files in the module itself. 

To elaborate a bit, consider the same pipeline as in #226. Rather than having a python module that needs to be integrated into scancode.io by writing pipelines and pipes and test cases, we can have a similar setup by using a new module, say `scancode_glc_plugin`

![image](https://user-images.githubusercontent.com/21276898/126940880-51888f30-dd74-4f9f-9484-d2c049d280b3.png)

Now my question. Is it possible to integrate tests in a similar fashion? 

I have been able to do it by adding the module under `INSTALLED_APPS` settings in Django, but is there another cleaner way to do this?

**Comment by tdruez** [comment]
In case of pipelines installed as a library, the tests are run on the library side.

**Comment by AvishrantsSh** [comment]
In case of pipelines installed as a library, the tests are run on the library side.

@tdruez shouldn't the tests be run on the scancode.io side? For example, I'm using the following imports within my plugin module
```python
from scanpipe.pipelines import scan_codebase
from scanpipe.pipes import make_codebase_resource, rootfs
from scanpipe.pipes import scancode
```
and the following imports in the test file
```python
from scanpipe.models import CodebaseResource, Project
from scanpipe.pipes.input import copy_inputs
```

The tests for this plugin won't work until and unless it is used within scancode.io. That's why running tests on module side might not be possible.

I hope I'm able to explain the issue to you.

**Comment by tdruez** [comment]
> shouldn't the tests be run on the scancode.io side?

No. ScanCode.io is a dependency of the plugin, not the other way around.

> The tests for this plugin won't work until and unless it is used within scancode.io

That's right, those tests depends on ScanCode.io.

> That's why running tests on module side might not be possible.

Why not?

**Comment by AvishrantsSh** [comment]
@tdruez, I'm not quite able to understand a few things. First, how can I list scancode.io as a dependency? Does it mean that the pipeline will be wrapped along with scancode.io? If so, how can others use this pipeline? Can you elaborate a bit?

What I planned was to have a simple PyPI package, which can be installed in any scancode.io environment, add the entry point in setup.py, and done.

**Comment by tdruez** [comment]
> What I planned was to have a simple PyPI package, which can be installed in any scancode.io environment, add the entry point in setup.py, and done.

Yes that is exactly what we want to achieve.

> First, how can I list scancode.io as a dependency? 

In the context of **testing** the library, in the continuous integration for example, or local development, you can simply:
```
pip install git+https://github.com/nexb/scancode.io.git
```

Note that I'm talking about the "test" context, not the distribution of the library.

> Does it mean that the pipeline will be wrapped along with scancode.io?

No wrapping.

> how can others use this pipeline?

The library will be published on PyPI and can be installed with a simple pip command in any local ScanCode.io virtualenv:

```
pip install <library_name>
```

**Comment by tdruez** [comment]
Let's take an example:
`Django` is a framework while `django-filter` is a library that implement some filtering tools for a Django app.

`django-filter` requires `Django`: https://github.com/carltongibson/django-filter/tree/main#requirements
There's no reason to install this library if you are not using Django in the first place.

`Django` as a dependency is installed before running the `django-filter` tests, as its code "depends"  (ie: import code form) `Django`.
https://github.com/carltongibson/django-filter/blob/main/requirements/test.txt
