### ISSUE TITLE
Add labels in Docker image

### ISSUE THREAD

**Issue by Hritik14** [nexB/scancode.io#256]
We need to decide on consistent labels to use in our Docker images across all the projects. Same issue exists in VulnerableCode: https://github.com/nexB/vulnerablecode/issues/513

ScancodeIO could serve as a light to follow for a Dockerfile. Changes here could be propagated across all our projects.

**Comment by tdruez** [comment]
@Hritik14 could you provide a bit more context? What is the issue you're facing? How the "labels" solve it?

**Comment by Hritik14** [comment]
@tdruez, Sure. During the weekly meeting with @pombredanne regarding VulnerableCode review, we found out that ScanCodeIO doesn't ship with docker labels about the project hompage, license etc. 
Perhaps, @pombredanne could provide the more detailed context.

**Comment by tdruez** [comment]
Added in https://github.com/nexB/scancode.io/commit/4f00b1799ed7c005e61649964c4ce3fc54665b86
