### ISSUE TITLE
Improve Pipeline and Pipe library documentation docstrings

### ISSUE THREAD

**Issue by hyounes4560** [nexB/scancode.io#258]
1. Review and improve the documentation docstrings in code to ensure that they are correct and relevant. Also, update the corresponding introduction and overview documentation.
2. Improve the existing Pipe library reference API documentation (generated from code documentation "docstrings").

**Comment by tdruez** [comment]
While we're on the docstrings, it would be nice to have a round of update for the rest of the code as well.
To improve the wording and have some consistency with the improved docstrings in Pipelines and Pipes.

The files that could use a review for "docstrings" update:

- scancodeio/licenses.py
- scanpipe/api/serializers.py
- scanpipe/api/views.py
- scanpipe/admin.py
- scanpipe/apps.py
- scanpipe/filters.py
- scanpipe/forms.py
- scanpipe/models.py
- scanpipe/tasks.py
- scanpipe/views.py

@hyounes4560 let me know if you could take care of those as well :)

**Comment by hyounes4560** [comment]
@tdruez, I just saw this; working on them.
