### ISSUE TITLE
http://scancode.io/ shows the nginx landing page

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#266]
I went to http://scancode.io/ and I see the "Welcome to nginx!" message. I don't think this should show up when we go to scancode.io

**Comment by tdruez** [comment]
See https://github.com/nexB/scancode.io/issues/63

**Comment by pombredanne** [comment]
This has been fixed at the DNS level: we now redirect https://scancodeio.readthedocs.io

**Comment by tdruez** [comment]
Not fixed yet.
