### ISSUE TITLE
Add new documentation section on Pipeline packaging and publication to PyPI as a Wheel

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#267]
As a new section in the https://scancodeio.readthedocs.io/en/latest/custom-pipelines.html / https://github.com/nexB/scancode.io/blob/main/docs/custom-pipelines.rst chapter (could also be a separate chapter if needed).

The goal is to document how to package and publish one or more custom pipelines (along their pipes) as a library.

**Comment by AvishrantsSh** [comment]
@tdruez should I use RTD for my GSoC report, or a simple .md in a separate repo will work too?

**Comment by tdruez** [comment]
@AvishrantsSh you can start a .rst file in your pipeline repo for now. We can decide later to integrate it (or parts of it) in the ScanCode.io docs.

**Comment by AvishrantsSh** [comment]
> @AvishrantsSh you can start a .rst file in your pipeline repo for now. We can decide later to integrate it (or parts of it) in the ScanCode.io docs.

@tdruez In the mail that we received, it was mentioned that the final report must be placed in a relatively permanent location.

**Comment by tdruez** [comment]
@AvishrantsSh the current progress in the docs was merged. We still need a section about the "publication to PyPI as a Wheel".

**Comment by AvishrantsSh** [comment]
@tdruez, isn't publication to PyPI a standard procedure? I think it just includes
- Making an account on PyPI
- `twine` upload

Or do we need docs for the complete configuration? Like MANIFESTS, setup.cfg etc.

**Comment by tdruez** [comment]
> isn't publication to PyPI a standard procedure?

Yes, but a user reading the ScanCode.io docs may have no ideas about this procedure. Some explanation and links would be nice.

> Or do we need docs for the complete configuration? Like MANIFESTS, setup.cfg etc.

No need for that level of details (although a note and link to an external docs is useful), just the overview of steps needed to publish on PyPI and how to then pip install this package on any ScanCode.io instance.

**Comment by tdruez** [comment]
@AvishrantsSh thanks for the new documentation content. Well done.
Merged and published 🚀
