### ISSUE TITLE
Review all ScanCode.io "strings" for consistency,

### ISSUE THREAD

**Issue by hyounes4560** [nexB/scancode.io#268]
Review all ScanCode.io "strings" for consistency, for example:
- models help_text
- success/error messages
- command-line help
- logging messages

**Comment by tdruez** [comment]
@hyounes4560 a new DockerWindows pipeline and related pipes were merged. 

It would be great to review and adjust those 2 files are well (docstring + all string as described above) as part of this ticket.

Content in:
- scanpipe/pipelines/docker_windows.py
- scanpipe/pipes/windows.py

**Comment by hyounes4560** [comment]
@tdruez will do.
