### ISSUE TITLE
Improve the "Application Settings" section fo the docs

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#269]
This section needs to be enhanced and improved to better explain the settings: 
- Django
- .env file
- environment variables. 

How they can be changed and of course expand the list and details for each of the documented settings. 
We may be able  to generate some of this information from the Django settings in Python.

**Comment by hyounes4560** [comment]
@tdruez, I am afraid that I don't understand what you mean by Django and environment variables? Could you elaborate more on this? Thanks

**Comment by tdruez** [comment]
@hyounes4560 I've added the missing notes about Django settings in https://github.com/nexB/scancode.io/pull/273/commits/95b45ced43fadbc064fa051eb588cbf1c18f81d9
Could you review those and we'll be ready to merge.
