### ISSUE TITLE
Data Model documentation

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#283]
Create new Reference section to explain the structure of the ScanCode.io Data Model and each data field. 
We may be able to generate the field-level documentation from the ScanCode.io Django models definition. 
The actual structure of this new documentation could be a list or a table.

**Comment by mjherzog** [comment]
This Data Model documentation is critical for understanding what you can do in custom pipeline steps since any data output from the custom step will need to fit into the Data Model.
