### ISSUE TITLE
Get scancode.io version and scanpipe run errors in API

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#288]
I am updating the readme at https://github.com/nexB/scancode.io-reference-scans where I am placing scanpipe project statistics in a table. I would like to show the scancode.io version used and errors encountered for each project. However, I am unable to get the scancode.io version or number of errors encountered in a project from the `api/projects/<project uuid>` endpoint. It might make more sense to add the scancode.io version and scanpipe run errors count in the `api/runs/<run uuid>` endpoint, as scancode.io could be updated between different runs.

**Comment by tdruez** [comment]
@JonoYang did you have the chance to look at the PR https://github.com/nexB/scancode.io/pull/290?

**Comment by JonoYang** [comment]
@tdruez Everything looks good! I'm able to get the scancode.io version and error count from the API.
