### ISSUE TITLE
Web UI: incorrect file name displayed in resource details

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#295]
![Screenshot from 2021-08-18 12-12-37](https://user-images.githubusercontent.com/675997/129880977-3c39c9a1-ebec-4ea3-98bf-36f6057baa44.png)
In this project the file named: `README.txt` is displayed as
```
README.txt.txt | 1.3 KB |
opencv-master.zip-extract/opencv-master/modules/highgui/src/files_Qt/Milky/README.txt
```

The whole scans was a scan_codebase pipeline for https://github.com/opencv/opencv/archive/refs/heads/master.zip

**Comment by tdruez** [comment]
```
>>> resource.name
'README.txt'

>>> resource.extension
'.txt'

>>> resource.filename
'README.txt.txt'
```

**Comment by tdruez** [comment]
Issue fixed in https://github.com/nexB/scancode.io/commit/93ee15e5cf11295254b0bab2d07bfec82fc90aed

**Comment by pombredanne** [comment]
Thanks!
