### ISSUE TITLE
Clicking the "(No values detected)" slice of a project returns empty queryset

### ISSUE THREAD

**Issue by AvishrantsSh** [nexB/scancode.io#296]
Nothing is listed in the Resource listing UI when clicking the "(No values detected)" slice of a project. It is probably because we are substituting null and empty fields as **(No values detected)**. The case is similar to #294.

![image](https://user-images.githubusercontent.com/21276898/129887008-33eca41f-c656-40a1-bba3-b5ac2efd2247.png)

![image](https://user-images.githubusercontent.com/21276898/129887081-fac05851-b534-44c1-b28d-0ccfae763a29.png)

**Comment by pombredanne** [comment]
Closing #294 in favor of this ticket:

> When clicking the "Other" slices of a project license pie chart, nothing is listed in the Resource listing UI . I think that's because "Other" is not a license but a grab bag of small, other licenses that were detected in a small number?

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/487
