### ISSUE TITLE
Unable to run the application locally

### ISSUE THREAD

**Issue by Joe-Sin7h** [nexB/scancode.io#309]
I'm trying `python manage.py runserver` and getting this error. 

![Capture](https://user-images.githubusercontent.com/58473917/131205743-ec6bef6f-a779-4685-bec4-710706b943ac.JPG)

**Comment by pombredanne** [comment]
@Joe-Sin7h you seem to be running:
1. Windows
2. miniconda
3. Python 2.x: you have some extra package called "environ" that runs only on Python 2.x  https://pypi.org/project/environ/ which is the one that fails.

We never tested and do not support any of these individually or in combination.
You should instead either:
- run on Linux in a VM
- use Docker and docker compose

I would be interested if out of this we could have instructions for Docker install on Windows BTW :)

**Comment by Joe-Sin7h** [comment]
Thanks for your response @pombredanne . I don't know how to use docker yet but I will definitely try once I have completed learning it.
For now, I'll try running it on my Ubuntu.
