### ISSUE TITLE
Add ScanCode.io Dependencies section to Reference Documentation

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#310]
Converted from @mjherzog card:

Add ScanCode/AboutCode Dependencies section to Reference Documentation - we need to explain more clearly the "internal" dependencies of ScanCode.io on ScanCode Toolkit, container-inspector and other nexB-sponsored projects. One purpose is to help users understand the release pipeline for a new version of SCIO.

**Comment by tdruez** [comment]
This could be a new section in the "ScanCode.io Overview" chapter, or maybe in the FAQ.
@hyounes4560 what's your take on the location of this new content?

**Comment by hyounes4560** [comment]
@tdruez both would work; however, it would make more sense to include this section/subsection under the "ScanCode.io Overview" chapter.
