### ISSUE TITLE
design-needed: Create app to display licenses and license rules

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#32]
These should be the scancode-toolkit licenses.
Ideally we should also have an easy to add new records which should then trigger a PR in scancode-toolkit
There should also ideally be a simple API that could be use d by aboutcde-toolkit to fetch license texts for attribution generation

**Comment by tdruez** [comment]
For a local Webserver available in ScanCode-toolkit to consult license data:
```
$ pip install bottle
```

```
from bottle import route, run, template

from licensedcode.models import load_licenses

licenses = load_licenses()

@route('/license/<license_key>')
def index(license_key):
    try:
        license_text = licenses[license_key].text
    except KeyError:
        return f'License {license_key} not found.'
    return template('<pre>{{license_text}}</pre>', license_text=license_text)

run(host='localhost', port=8080)
# open http://localhost:8080/license/apache-2.0
```

This could also be a new Django app module in ScanCode.io with publicly available views.

**Comment by pombredanne** [comment]
Here is an updated version:
```Python
import saneyaml
import webbrowser
from bottle import route, run, template
from licensedcode.models import load_licenses

licenses = load_licenses()

webbrowser.open("http://localhost:8080/license")

@route('/license')
def license_list():
    return '<br>'.join([f'<a href="/license/{key}">{key}</a>' for key in licenses.keys()])

@route('/license/<key>')
def license_text(key):
    try:
        data = saneyaml.dump(licenses[key].to_dict())
        text = licenses[key].text
    except KeyError:
        return template('License {{key}} not found.', key=key)
    return template('<pre>{{data}}</pre>\n=====================\n<pre>{{text}}</pre>', data=data, text=text)

run(host='localhost', port=8080)

```

**Comment by tdruez** [comment]
A similar approach generating a static HTML site that could be available through  GitHub pages for example:

```
# pip install dominate

import pathlib
import saneyaml
from licensedcode.models import load_licenses
from dominate.tags import *

licenses = load_licenses()

output_path = pathlib.Path("static/")
output_path.mkdir(parents=False, exist_ok=True)

index = html(body(ul(li(a(key, href=f"{key}.html")) for key in licenses.keys())))
(output_path / "index.html").open('w').write(index.render())

for license in licenses.values():
    data = saneyaml.dump(license.to_dict())
    content = html(body(pre(data), hr(), pre(license.text)))
    (output_path / f"{license.key}.html").open('w').write(content.render())
```

**Comment by tdruez** [comment]
@pombredanne This PR about making the licenses data available from the ScanCode.io server UI is ready for review: https://github.com/nexB/scancode.io/pull/47

For the publicly available license data, see an example using the GitHub pages feature with a generated static HTML from the load_licenses():
Code @ https://github.com/tdruez/licenses and rendered @ https://tdruez.github.io/licenses/

Let me know your take on those 2 approches and if we should migrate the GitHub pages app into a reference nexB repo.

**Comment by pombredanne** [comment]
@tdruez IMHO both approaches are worthy. The statically generated pages are easy and can make deployment as Github pages or else with minimal fuss quite easy. And the Django mini app allows clean integration in scancode.io in one step.

**Comment by tdruez** [comment]
Minimal license views are now available in ScanCode.io.
Also, the new LicenseDB is published at https://scancode-licensedb.aboutcode.org/ from the code at https://github.com/nexB/scancode-licensedb
