### ISSUE TITLE
Improve docker extra_data

### ISSUE THREAD

**Issue by aalexanderr** [nexB/scancode.io#323]
- history part is clipped at first line, it would be nice to have full history string
- based on parent hash & history part of a layer compute hashes for each layer (this would follow how justone/dockviz does it) and store them in extra_data for a project

Those hashes should identify unique layers and could be used in future to limit rescans of already scanned stuff.
This would also help towards implementing a pipeline that would create a dot-graph for a given subset of dockers.

**Comment by tdruez** [comment]
> history part is clipped at first line, it would be nice to have full history string

Can you provide an example? Which inputs, clipped part, expected results?
The history looks fine on my local projects.

**Comment by tdruez** [comment]
The clipping issue cannot be reproduce.
The layers data was added in https://github.com/nexB/scancode.io/issues/175
