### ISSUE TITLE
Need a way to support offline installation

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#332]
Users may want to install and upgrade scancode.io in a local machine which has no internet connection. We need a way and documentation on how to do that.

**Comment by pombredanne** [comment]
We have a "package" make target but this is not working good enough IMHO. 
The outline of a better script to support this would be:
- build the docker images locally first, with `docker-compose build`, then
- `docker save` .... all images at once to export a tarball of docker images
- (optional) you can scan that in scancode alright ;) if you need origin and license details for redistribution
- assume somehow that docker compose and docker  are pre-installed on the target machine (or we provide them?)
- on this target machine, `docker load ` the image(s) tarball
- run docker-compose up

**Comment by tdruez** [comment]
> docker save .... all images at once to export a tarball of docker images

@pombredanne should we add a Makefile command like:
```
docker save nginx postgres redis scancodeio_web scancodeio_worker -o scancodeio_images.tar
```

**Comment by pombredanne** [comment]
@tdruez that would be great as a start.  :+1: 
You may want to output this not something that would contain the version + commit like
`docker save nginx postgres redis scancodeio_web scancodeio_worker -o scancodeio-images-$(git describe).tar`

And we could later add this to a package with docker-compose, its deps and virtualenv.pyz and a minimal readme or boostrap script  to get a complete thing.
