### ISSUE TITLE
Server error 500 when clicking on some files

### ISSUE THREAD

**Issue by ddmesh** [nexB/scancode.io#344]
Hi,

when I start a scan via curl + REST API the scan runs successfully. When I then select some files in GUI
I get a server error 500 (http). Most other files can be opened, but few not.

I then run a bash on container "web" and could locate the file within the workspace/project directory and view it.
It has exactly the same and correct path as displayed in the tables via GUI (website).
It seems that URL (.../resources/123456/) does not resolve to the file's path correclty. 
The path does not have any white spaces or risky characters.

Hope this can be solved easily.

Another questions: When there are some archives within the archive that I have uploaded, those are analysed. But I can also not display it. In workspace project directory there is no directory _extract and compliance alert says "missing".  Any Idea how I can view those files too? I thought the default is that all archives within others are extracted.

Thanks a lot

**Comment by tdruez** [comment]
> I thought the default is that all archives within others are extracted.

Which pipeline are you running?  scan_codebase is not extracting recursively for example, see https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/scan_codebase.py#L53

> compliance alert says "missing"

That's a different issue, what are the licenses on the resource for which the "missing" is returned? Do you have defined a policy for all of the licenses?

> It has exactly the same and correct path as displayed in the tables via GUI (website).
> It seems that URL (.../resources/123456/) does not resolve to the file's path correclty.

We need a bit more data to be able to debug this.

**Comment by pombredanne** [comment]
> I use pipeline "scan_codebase" because I could't determine exactly the differences to the other ;-)
> What pipeline should I use instead to have recursive extractions ?

We should consider these options:
1. be explicit that this pipeline extraction is "shallow" and have an alternative pipeline with "recursive" extraction
2. make this pipeline with "recursive" extraction by default
3. improve the way extraction is handled, such that we have progressive extraction as needed as opposed to blanket extraction

There are some things to consider when doing always recursive extraction with these existing issues in ScanCode toolkit:
- https://github.com/nexB/scancode-toolkit/issues/14
- https://github.com/nexB/scancode-toolkit/issues/218
- https://github.com/nexB/scancode-toolkit/issues/1279

And some of the pending issues in https://github.com/nexB/extractcode/issues

I think this is worth making recursive the default (option 2) while we will work towards option 3.

@ddmesh What do you think?

**Comment by ddmesh** [comment]
Hi,
what about providing a configuration variable in file .env that controls extracting? so the user may choose as he needs?

**Comment by ddmesh** [comment]
I changed `extract_recursively` in my local copy of scancode-io.
Do you have already an idea about my findings in post  https://github.com/nexB/scancode.io/issues/344#issuecomment-940988414 ?

**Comment by tdruez** [comment]
> Do you have already an idea about my findings in post #344 (comment) ?

@ddmesh yes, I'll provide a fix for this, we should never return 500 in any cases. Thanks for the investigation.

**Comment by ddmesh** [comment]
> @ddmesh yes we'll provide a better way to control extracting. Until then, you can edit your local scan_codebase and set the `extract_recursively` argument to True.

@tdruez have your already created a separate issue for better configuration of extract_recursively by user?
