### ISSUE TITLE
Use extractcode for archive extraction

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#358]
There are archives that SCIO fails to do the extraction correctly. However, `tar` command and `extractcode` work. Unfortunately, I cannot attached a test/sample files as it contains customer data.

**Comment by tdruez** [comment]
The `docker` and `root_filesystems` pipelines are leveraging the `container-inspector` `extract_tar` function.
This function was recently refactored and fixed, see https://github.com/nexB/container-inspector/commit/63ed384ed543aefcb416959725b2b091ec31bc62

The `scan_codebase` and `scan_package` pipelines are using `extractcode `.
