### ISSUE TITLE
When creating a project from the command, launch background execution

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#361]
Today the CLI `create-project` command with the `--execute` option does execute immediately a project's pipelines in the foreground. I would like to have an option where I can instead request queuing of the execution without actually performing the pipeline run in the current shell and that at once without having to separately run the `execute --async` command. May be a new option such as `--execute-async` to be conistent in the `execute` command?

**Comment by tdruez** [comment]
@pombredanne the --async option is now available in the `create-project` command. See https://scancodeio.readthedocs.io/en/latest/command-line-interface.html#scanpipe-create-project-name and https://github.com/nexB/scancode.io/pull/363
