### ISSUE TITLE
Improve doc for CLI project creation: with Docker, we need a "volume" to add local files to project input files

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#362]
The doc recommends using Docker for installation, but all the CLI examples assume that the runs are not done with a Docker installation.

1. we should separate non-Docker, debug and development-style CLI runs from the regular production CLI runs where the installation was done with Docker
2. in order to add local input files to a project using the CLI, extra arguments needs to be passed to docker-compose

For instance with `--volume  /absolute/source/path/on/host:/absolute/target/path/in/container:ro` this mounts and makes available `/absolute/source/path/on/host` on host to the `/absolute/target/path/in/container` path inside the container (and :ro means read only)

For instance a full command to create a project with my local file at `/home/foo/code/image.tar` could be:

```bash
$ docker-compose run \
    --volume /home/foo/code:/foo:ro web \
    ./manage.py create-project my-project \
    --pipeline docker \
    --input-file="/foo/image.tar" 
```

**Comment by tdruez** [comment]
The docs were improved. The rewriting of the tutorials base don Docker is happening in https://github.com/nexB/scancode.io/issues/440
