### ISSUE TITLE
Add new pipeline for basic codebase scan

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#37]
The input to that pipeline would be code archive(s).
The pipeline would:
1. extract the archives (not recursively at first)
2. run the equivalent of scancode `-clipeu` scan on that code
3. create one or more inventory analysis "workfile" report as CSV, JSON (or XLS TBD) listing all the captured resources and packages in a format TBD.

The reports would be created by the pipeline and stored on disk to be retrieved by the API

**Comment by tdruez** [comment]
New ScanCodebase Pipeline available at https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/scan_codebase.py
Documented in https://scancodeio.readthedocs.io/en/latest/scanpipe-pipelines.html#scan-codebase and https://scancodeio.readthedocs.io/en/latest/scanpipe-tutorial-2.html
