### ISSUE TITLE
Report the breakdown of resources by status

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#370]
This is not visible in the UI today and would be very useful

**Comment by tdruez** [comment]
It is visible in the run status modal. It was initially added there to help track the progress of a pipeline run:
<img width="315" alt="Screenshot 2021-12-01 at 8 37 40 AM" src="https://user-images.githubusercontent.com/489057/144172773-ea2b342c-1f8f-4976-afe8-bdc59bf01613.png">

We could move it to the main projet details UI.

**Comment by tdruez** [comment]
Status panel moved to the main project details view.
