### ISSUE TITLE
The scancode status logs are not getting updated if new pipelines are not added

### ISSUE THREAD

**Issue by Pratikrocks** [nexB/scancode.io#379]
Let's create a pipeline for scanning a docker image. The logs in the below image will show it as `running` even though its completed.
<img width="447" alt="Screenshot 2021-12-08 at 9 11 43 PM" src="https://user-images.githubusercontent.com/44219625/145238266-7a2bc69b-5019-4e9e-82b5-1a56ae6a5883.png">

However on creating a new pipeline only the previous logs will get updated.

<img width="447" alt="Screenshot 2021-12-08 at 9 14 07 PM" src="https://user-images.githubusercontent.com/44219625/145238369-f9db0a9b-cc4e-462a-acaa-33642438e6a9.png">

Like here we can see the previous logs has been changed to `success` status

**Comment by tdruez** [comment]
@Pratikrocks could you provide steps to reproduce this issue?

**Comment by Pratikrocks** [comment]
Hi @tdruez
 I meant to highlight that dynamic part actually as it would seem much better to have that part dynamic

**Comment by tdruez** [comment]
Automatic refresh implemented in https://github.com/nexB/scancode.io/issues/390#issuecomment-1101450130
