### ISSUE TITLE
Create/generate documentation for "pipes"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#38]
To help a pipeline creator, knowing which are the "pipes" available, what they do and how to use them would be mighty useful.
Since a "pipe" is just a plain Python function (that we organize by module for clarity), the best approach would be to use docstrings and generate a clean doc from that.

**Comment by tdruez** [comment]
New docs available at https://scancodeio.readthedocs.io/en/latest/scanpipe-pipelines.html and https://scancodeio.readthedocs.io/en/latest/scanpipe-pipes.html
