### ISSUE TITLE
Can we generate a notice file from the scan

### ISSUE THREAD

**Issue by sameer1046** [nexB/scancode.io#388]
From  Scancode.io is it possible to generate a notice file which will contain the details licence text and copyright of the files?

**Comment by pombredanne** [comment]
@sameer1046 the data is present in the database and exposed in the API, though there is no pre-computed report yet available for this exposed yet.

**Comment by sameer1046** [comment]
HI @pombredanne , Thanks. Can we have this feature in the UI to get notice file in a json file/cycloneDX format.

**Comment by pombredanne** [comment]
@sameer1046 sure thing: Let's design it here: can you outline how you would want this to look like?

**Comment by tdruez** [comment]
@sameer1046 a new "Attribution" downloadable output is now available. Implemented in https://github.com/nexB/scancode.io/pull/712

You can provide a custom template according to your needs from the "Settings" of your Projects.

See also https://scancodeio.readthedocs.io/en/latest/output-files.html?highlight=attribution#attribution
