### ISSUE TITLE
Automatically refresh "Running" status

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#390]
The "Running" status for an SCIO pipeline does not automatically refresh in the Projects dashboard or the Project page. The problem is that you may think the pipeline is still running after it has finished.  A periodic refresh every 30 seconds could suffice.

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/428

From https://github.com/nexB/scancode.io/blob/main/CHANGELOG.rst

> Implement run status auto-refresh using the htmx JavaScript library. The statuses of queued and running pipeline are now automatically refreshed in the project list and project details views every 10 seconds. A new "toast" type of notification is displayed along the status update. 

@mjherzog "Running" and "Queued" are now refresh every 10s.
