### ISSUE TITLE
Close Buttons not working in Running Pipeline

### ISSUE THREAD

**Issue by OsmiumOP** [nexB/scancode.io#396]
Seems like there is still some problem with the Close Buttons in the Pipeline View. 
I encountered it only when the Pipeline was showing running status but had completed midway. 

![ScanCode](https://user-images.githubusercontent.com/71386574/152636184-f2cbdf5e-0a46-427b-bcc8-05f831e73237.gif)

I would also like to work on this issue, still need confirmation. @pombredanne

**Comment by tdruez** [comment]
@OsmiumOP could you provide some steps to reproduce the issue? I couldn't get the button to not work so far.

**Comment by tdruez** [comment]
The close buttons are working as expected in the current `main` branch.
