### ISSUE TITLE
Option for layer_id alias in path

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#404]
We should offer an option to show an alias for the layer_id in Codebase Resources because:
- The length of the full layer_ids make the Resource column hard to use in the Codebase Resources worksheet in an SCIO results file for a Docker image.
- The layer_id does not provide any information about the layer order. The layer order information can be especially useful when comparing Codebase Resources to the corresponding Dockerfile for an image.

Some ideas for an alias:

1. Truncate the layer_id to 5 to 10 characters (left to right). Theoretically there could be two layer_ids in the same image with the same first characters, but IRL I have never seen this and expect that it very rarely happens. We could also include an error check for this condition.
2. Substitute layer_001, layer_002 for the layer_ids in order from the Base layer.
3. Combine a layer number with a truncated layer_id - e.g., "layer_001-d30ff".

The simplest approach seems to be (optionally?) creating a new field named `path-alias` in addition to the current `path`.
The layer_001 suggestion was inspired by the display of Docker image layers in OpossumUI - https://github.com/opossum-tool/OpossumUI

**Comment by tdruez** [comment]
A new `tag` field addressing this `layer_id` value was implemented in https://github.com/nexB/scancode.io/issues/443
Closing.
