### ISSUE TITLE
Finish creating project before downloading image.

### ISSUE THREAD

**Issue by xerrni** [nexB/scancode.io#410]
Currently when project is created a `POST` request is sent.
Response for this request is sent after input is downloaded.

In my opinion it is wrong user experience as download can take long time (huge docker images). I propose that `web` container should return page with created project before image is downloaded.

Current behavior breaks some nginx configuration as timeout occurs in nginx before it receives response from `web` container and it returns 504 error code (gateway timeout) as response.

Furthermore when user hits refresh button request is resend and `web` re-downloads this input.

**Comment by pombredanne** [comment]
@xerrni 

> In my opinion it is wrong user experience as download can take long time (huge docker images). I propose that web container should return page with created project before image is downloaded.

I completely agree. Large images (including huge VM or Docker images that can routinely be 30 to 50GB big) are problematic.
There are a few behaviours possible:

1. download in the background after the project has been created
2. kick in only when the pipeline is executed, download as a pre-pipeline process if there are downloadable URLs 
3. kick in only when the pipeline is executed, download as a first explicit step of a pipeline if there are downloadable URLs. A pipeline without a download step would not download.

Which ones would be the better way?

@cco3 what's your take there?

**Comment by cco3** [comment]
option 1 makes the most sense to me...download could just be a stage in the pipeline.

**Comment by aalexanderr** [comment]
I think 3rd option is best - fetching is already a pipe and it would make scaling easier.

**Comment by pombredanne** [comment]
See also https://github.com/nexB/scancode.io/issues/372

**Comment by tdruez** [comment]
The download of Project's inputs now takes place in the pipeline run.
