### ISSUE TITLE
Enhance Project list view page

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#413]
When you have start to build up a library of Scans, it can be difficult to find a particular Scan or a set of Scans of interest on the Project summary page /scancode.io/project/. Search works pretty well if you know the name of the Scan or the Pipeline, but we can do better.

Some simple ideas to improve the usability are:

- Increase the default number of displayed rows from 10 to 20 or 25
- Add the Date Completed to the display 
- Enable column sort by Name, Date or Pipeline

**Comment by adii21-Ux** [comment]
@mjherzog added this 
![Screenshot from 2022-04-05 18-48-27](https://user-images.githubusercontent.com/88366673/161762890-cb0df8df-0e35-47aa-9c31-b5f6f491965a.png)
but and made some changes to models should I also migrate

**Comment by tdruez** [comment]
> Increase the default number of displayed rows from 10 to 20 or 25

We need to review the impact on performances before make this change.

> Add the Date Completed to the display

We need to define/clarify the concept of "Date Completed" which does not exists at the project level but at a Pipeline run level and multiple pipelines can be run a project.

**Comment by adii21-Ux** [comment]
@mjherzog that could work

**Comment by adii21-Ux** [comment]
So should I change Date Completed to Creation Date

**Comment by lf32** [comment]
@mjherzog @tdruez
 does this look good with default rows set to 20 and also if you think there is a need for better date format, just lemmino

![check](https://user-images.githubusercontent.com/96695352/173053174-355ada7f-44c5-4be9-a735-c5ae7cb6e20b.png)

**Comment by tdruez** [comment]
@mjherzog all those suggestions were implemented plus some extra filtering on pipeline type.
