### ISSUE TITLE
license/ web page fails with 500 error

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#424]
Accessing the license/ web page fails with a "500" error

**Comment by lf32** [comment]
yes noticed this few hrs ago

is it `license/`?

should it be changed to `licenses/` ?

and individual license with `licenses/<license-name>/` ?

changing from
https://github.com/nexB/scancode.io/blob/16644a60c6dbe81fa078fc6941fbd8be817fe935/scancodeio/urls.py#L53
to 
```
path('licenses/', include(licenses.urls)),
```
**works**

**Comment by lf32** [comment]
PR?

**Comment by tdruez** [comment]
@lf32 a better solution is to simply remove the "license_app" namespace during the registration at https://github.com/nexB/scancode.io/blob/main/scancodeio/urls.py#L53

Also, you new TestCase does not follow existing naming convention for tests: 

Suggestions:
- `get_licenses_test` -> `test_license_list_view`
- `get_license_details_test` -> `test_license_details_view`

Lastly, the code is not properly formatted, make sure to run `make valid` before committing changes.
