### ISSUE TITLE
Craft better documentation for tutorials that use a Docker installation

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#440]
Today all the tutorials (and in particular the "create pipeline from the command line" tutorials such as https://scancodeio.readthedocs.io/en/latest/tutorial_cli_analyze_docker_image.html) are assuming a virtualenv and development style checkout and installation.

They do not work well with a Docker -based deployment that we otherwise recommend.
The only place that provides some input on command line project creation with a Docker deployment is in https://scancodeio.readthedocs.io/en/latest/command-line-interface.html?highlight=volume#command-line-interface

I would like to have a simple step by step tutorial for creating a scan project from the command line using a Docker deployment.

**Comment by daredevil3435** [comment]
@pombredanne can you explain more? I would like to work on this

**Comment by tdruez** [comment]
@daredevil3435 I already have a patch for this ready, it just need a bit of cleanup. Please find another issue to work on ;)

**Comment by daredevil3435** [comment]
> @daredevil3435 I already have a patch for this ready, it just need a bit of cleanup. Please find another issue to work on ;)

Ok ok that's fine

**Comment by tdruez** [comment]
See also https://github.com/nexB/scancode.io/issues/362

**Comment by tdruez** [comment]
Done in https://github.com/nexB/scancode.io/pull/633
