### ISSUE TITLE
Report layer details in the docker pipeline

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#443]
We are reporting the layers makeup in the project, but we are cannot determine easily if a resource or package belongs to a certain layer (or a certain image when we scan a tarball with multiple images).

A possible solution would be to introduce a concept of tag that would be a single free text field in a CodebaseResource and a DiscoveredPackage that a pipeline could set. And this would be reported in the XLSX and JSON outputs.
Then the docker pipeline could set this "tag" field to a value that would structured using a short image id + layer id with proper prefixes so things sort out nicely.
For instance, given an image with an id 785df58b6b3e120f59bce6cd10169a0c58b8837b24f382e27593e2eea011a0d8 and two layers from bottom to top as 0690c89adf3e8c306d4ced085fc16d1d104dcfddd6dc637e141fa78be242a707 and 7a1d89d2653e8e4aa9011fd95034a4857109d6636f2ad32df470a196e5dd1585 we could get these two tags:

- img-785df5-layer-01-0690c8
- img-785df5-layer-02-7a1d89

This is not too long, clear and sortable.

(The length of the hex to keep could be fixed to 6 chars or computed to ensure unicity)

An alternative could be to generalize this approach to an arbitrary mapping of "extra_data" name/value pairs that would be then reported as extra columns in the XLSX output or as a plain mapping in the JSON output. This would allow to create new "columns" for an image id, a layer order and a layer id.

**Comment by pombredanne** [comment]
@mjherzog ping

**Comment by pombredanne** [comment]
See also https://github.com/nexB/scancode.io/issues/404

**Comment by mjherzog** [comment]
I would prefer the tag idea, especially if it would work with other types of containers. It would help to identify a use case beyond containers to identify the best approach.

**Comment by tdruez** [comment]
@mjherzog new `tag` field feature deployed on ScanCode.io Staging for review.

The new field on the resource is set during the `docker` pipeline run.
The value is then available in the resource list, the REST API, and both outputs: json, and xlsx.

Please give it a try and let me know if this implementation works for you.

https://nexb:jXTxRGOIu619FXVv8qy2DGNnF@staging.scancode.io/

You can run your own `docker` scans or have a look at this one I've created: https://nexb:jXTxRGOIu619FXVv8qy2DGNnF@staging.scancode.io/project/89a56139-c1da-414c-859c-770838f5c196/

**Comment by mjherzog** [comment]
@tdruez The data from your rabbitmq sample looks good!
I also noticed a new (?) compliance_alert column - is that based on a policy setting?

**Comment by tdruez** [comment]
> I also noticed a new (?) compliance_alert column - is that based on a policy setting?

@mjherzog Yes, it is computed from the license policies, not that "new" though ;)
See https://scancodeio.readthedocs.io/en/latest/tutorial_license_policies.html#license-policies-and-compliance-alerts 
and https://scancodeio.readthedocs.io/en/latest/scancodeio-settings.html#scancodeio-settings-policies-file
for the full details about this feature.
