### ISSUE TITLE
Create new model for dependencies 

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#447]
scancode-toolkit has a new model called `DependentPackage`, which models the dependencies detected for a Package from a package manifest. The `DependentPackage` data shows up in the scancode JSON results in the top-level `Dependencies` field. We should create a new model, `DiscoveredDependency` (or some other name) to represent this in scancode.io

**Comment by tdruez** [comment]
@JonoYang I remember you had committed a new model for the dependencies but we decided to postpone after the toolkit upgrade.
Could you start a new branch with this new model? This would be a good base for discussion.

**Comment by JonoYang** [comment]
@tdruez I started a new branch with the `DiscoveredDependency` model I had from earlier. The only change I made from my original commit is that I increased the size of the `package_uid` related fields to 1024.

**Comment by JonoYang** [comment]
DiscoveredDependencies should be related to the DiscoveredPackage they are from. This would be convenient to link the Dependencies to their Package in the Dependency detail view, similar to how we can get to the Package Resources from the Package detail view.

**Comment by pombredanne** [comment]
@JonoYang re:

> DiscoveredDependencies should be related to the DiscoveredPackage they are from. 

should this be rather  a Package Instance per #444 ?

**Comment by JonoYang** [comment]
@pombredanne I wanted to make something quick happen with the current models so I can start linking the packages and dependencies in the view.

**Comment by pombredanne** [comment]
Based on discussions in  https://github.com/nexB/scancode.io/issues/444#issuecomment-1204299961 and https://github.com/nexB/scancode.io/issues/444#issuecomment-1205448127 here is what I suggest:
- the Dependency has a UID is directly related to DiscoveredPackage as designed in https://github.com/nexB/scancode.io/issues/444#issuecomment-1205448127

Pkg -> Dep ( and -> Pkg for resolved package in the future)

1. What this means is the relationship between a Dep and a Package is a simple ForeignKey in Dep-> Package and not a manytomany. `for_package_uid` should be gone since this is what this FK is about. https://github.com/nexB/scancode.io/pull/482/files#diff-d71c8a8d98cec2c888bbf875d6a34a481041ba8a56656ec516aa53b0b7f6f194R1796 would no be needed since we would use a simpler FK.

2. `dependency_uid` would be unique in DiscoveredDependency aka. like a primary key... See https://github.com/nexB/scancode.io/pull/482/files#diff-d71c8a8d98cec2c888bbf875d6a34a481041ba8a56656ec516aa53b0b7f6f194R1814 This should be the first listed field of the model

3. Should `datafile_path` be an actual FK to a CodebaseResource? IMHO yes.

3.

**Comment by tdruez** [comment]
PR merged.
Thanks @JonoYang for the implementation 👍

**Comment by tdruez** [comment]
Actually getting an issue when applying the migrations on a production database.

```
web_1     | Running migrations:
web_1     |   Applying scanpipe.0022_rename_dependencies_discoveredpackage_dependencies_data_and_more... OK
web_1     | Traceback (most recent call last):
web_1     |   File "/app/./manage.py", line 6, in <module>
web_1     |     command_line()
web_1     |   File "/app/scancodeio/__init__.py", line 45, in command_line
web_1     |     execute_from_command_line(sys.argv)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
web_1     |     utility.execute()
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
web_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
web_1     |     self.execute(*args, **cmd_options)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
web_1     |     output = self.handle(*args, **options)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
web_1     |     res = handle_func(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle
web_1     |     post_migrate_state = executor.migrate(
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
web_1     |     state = self._migrate_all_forwards(
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
web_1     |     state = self.apply_migration(
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
web_1     |     state = migration.apply(state, schema_editor)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 130, in apply
web_1     |     operation.database_forwards(
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
web_1     |     self.code(from_state.apps, schema_editor)
web_1     |   File "/app/scanpipe/migrations/0023_migrate_dependencies.py", line 33, in migrate_dependencies_to_discovereddependencies
web_1     |     DiscoveredDependency.objects.create(
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1     |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 669, in create
web_1     |     obj = self.model(**kwargs)
web_1     |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 585, in __init__
web_1     |     raise TypeError(
web_1     | TypeError: DiscoveredDependency() got unexpected keyword arguments: 'requirement'
```

**Comment by tdruez** [comment]
Migration issues fixed in https://github.com/nexB/scancode.io/pull/514

**Comment by JonoYang** [comment]
Closing this now that #486 and #514 has been merged.
