### ISSUE TITLE
Generate standard JSON files from SCIO-DB

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#45]
When you use ScanPipe to analyze a codebase and load the Scan data into the SCIO-DB, you should also be able to extract the Scan data from the SCIO-DB according to any combination of the basic ScanCode runtime parameters:
--info
--copyright
--license
--package
--email
--url
The primary output format should be standard SCTK JSON.
I am not sure what we should put in the output file header, but we would at least want to know what version of SCTK was used for the original Scan. In any case this JSON file must be compatible with ScanCode Workbench since the primary use case is to view Scan data there.

**Comment by tdruez** [comment]
@mjherzog Those JSON results are already available and can be generated/gathered from the following places:

- As an output pipe `to_json`  that can be called from any Pipelines.
https://scancodeio.readthedocs.io/en/latest/scanpipe-pipes.html#scanpipe.pipes.outputs.to_json

- As an `output` command that will write the results into a provided `output_file` location or on the terminal standard output.
https://scancodeio.readthedocs.io/en/latest/scanpipe-command-line.html#scanpipe-output-project-project-output-file

- As `results` (stream) and `results_download` (attachment) views from the Browsable REST API
`Api Root` > `Project List` > `Project Instance` > `Results`

----

**Notes:** The JSON file content is standard ScanCode format and is fully compatible with ScanCode Workbench. The `tool_version` entry is included in the headers.
