### ISSUE TITLE
API create project with file

### ISSUE THREAD

**Issue by RaphaelHerd** [nexB/scancode.io#457]
I want to create a new project by using the API. In the documentation I could see how to do that with a path to a file to scan. I want to upload a file which should be scanned. I can do it in the UI by using drag and drop. What do I have to do to enable that by the API?
## upload_file here is not working

data='{
    "name": "core api",
    "upload_file": "/mnt/d/git/wsl/projects/murphy.zip",
    "pipeline": "scan_codebase",
    "execute_now": false
}'

curl -v --header "Authorization: Basic aabbcc" -X POST "http://mydomain.com/api/projects/" -H "Content-Type: application/json" -d "$data"

**Comment by tdruez** [comment]
Hi @RaphaelHerd , `upload_file` is a special type of field, it cannot be provided in the `data` but need to be submitted as a `file`.

You can use the Form emulation in cURL with the following syntax:
```
api_url="http://localhost/api/projects/""
upload_file="/path/to/the/archive.zip"

curl -F "name=project_name" \
     -F "pipeline=scan_package" \
     -F "execute_now=True" \
     -F "upload_file=@$upload_file" \
     "$api_url"
```

Let me know if that works for you and I'll add this to the documentation.

**Comment by RaphaelHerd** [comment]
@tdruez thx for the quick response. It works. You can close the issue. But before, you maybe can help me quickly with one other question:

Is it also possible to use scancode CLI for automation purposes (https://scancodeio.readthedocs.io/en/latest/command-line-interface.html)? If so, can you tell me if and how I can build scanpipe individually or simply use it as pip package? I saw that it is available if I build the entire solution in compose but is there an easy way to only build the scanpipe CLI?

Thanks in advance

**Comment by tdruez** [comment]
@RaphaelHerd thanks for reporting, I've added the details about `upload_file` in the documentation https://scancodeio.readthedocs.io/en/latest/rest-api.html#create-a-project

> simply use it as pip package?

ScanCode.io is not a library but a server. 
It requires a database, tasks worker, cache backend, and a webserver to work properly.
The "Local development installation" is the lightest setup you can have at the moment.
If you only want to run a scan from the command line, you can use the ScanCode-toolkit https://github.com/nexB/scancode-toolkit as a library.
