### ISSUE TITLE
Software configuration

### ISSUE THREAD

**Issue by RaphaelHerd** [nexB/scancode.io#460]
Dear,

is it possible to configure parts of the system? I'm currently refereing to the number of scans which can be performed in parallel? The default installatuion only allows one at a time. At scancode-toolkit, for instance, you can configure number of used threads or the properties you wwant to scan for (e.g. licenses, copyright, ...). Do I have something similar in scancode.io?

Thanks for your hel

Raphael

**Comment by tdruez** [comment]
> s it possible to configure parts of the system?

Yes, see the list of available settings at https://scancodeio.readthedocs.io/en/latest/scancodeio-settings.html

> At scancode-toolkit, for instance, you can configure number of used threads or the properties you wwant to scan for (e.g. licenses, copyright, ...)

You can configure the multiprocessing with https://scancodeio.readthedocs.io/en/latest/scancodeio-settings.html#scancodeio-processes
Note that this setting configure the number of CPUs available per scan.

> I'm currently refereing to the number of scans which can be performed in parallel? The default installatuion only allows one at a time.

By default, only one worker is started, you can start as many worker as you want (depending on your machine configuration) to perform multiple scans in parallel.

**Comment by tdruez** [comment]
Hi @RaphaelHerd did you manage to configure ScanCode.io as you wanted?

**Comment by tdruez** [comment]
@RaphaelHerd I'm closing, please re-open if you couldn't configure with the currently available settings.
