### ISSUE TITLE
"_extract_tar: skipping link with missing target:" in the docker pipeline

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#471]
While scanning docker://quay.io/wire/alpine-deps  I get this :
> _extract_tar: skipping link with missing target: <TarInfo 'bin/arch' at 0x7ffa99193d00>: Traceback (most recent call last):

> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
> File "/usr/local/lib/python3.9/tarfile.py", line 2418, in _find_link_target raise KeyError("linkname %r not found" % linkname) KeyError: "linkname 'bin//bin/busybox' not found" _extract_tar: skipping link with missing target: <TarInfo 'bin/ash' at 0x7ffa99193dc0>: Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
> File "/usr/local/lib/python3.9/tarfile.py", line 2418, in _find_link_target raise KeyError("linkname %r not found" % linkname) KeyError: "linkname 'bin//bin/busybox' not found" _extract_tar: skipping link with missing target: <TarInfo 'bin/base64' at 0x7ffa99193b80>: Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
> File "/usr/local/lib/python3.9/tarfile.py", line 2418, in _find_link_target raise KeyError("linkname %r not found" % linkname) KeyError: "linkname 'bin//bin/busybox' not found" _extract_tar: skipping link with missing target: <TarInfo 'bin/bbconfig' at 0x7ffa99193e80>: Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
>

**Comment by tdruez** [comment]
@pombredanne @JonoYang  should we create an issue on the `container_inspector` side then?

**Comment by pombredanne** [comment]
@tdruez if we were to treat and report these are warnings or info rather than errors, would there be a way to display these as such in the UI rather than as errors?

**Comment by tdruez** [comment]
We would have to refactor the "Error" system into a more global "Message" model with a new `level` type: info, warning, errors.
That would be a good improvements in any case, but this would not solve the actual extraction issues.
