### ISSUE TITLE
Cannot scroll down after adding inputs

### ISSUE THREAD

**Issue by lf32** [nexB/scancode.io#473]
When I try to input multiple files or a lengthy download URL, I can't scroll down to the bottom and submit the form.

![scroll](https://user-images.githubusercontent.com/96695352/180633984-dc68de17-35b2-4bcc-878e-28d648974798.png)

**Comment by tdruez** [comment]
@lf32 thanks for reporting, fixed in https://github.com/nexB/scancode.io/commit/083b4b84bf0256b3f4f3ed5f079fa981de80d9ff
