### ISSUE TITLE
Select codebase content from SCIO- DB for JSON or CSV output

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#48]
When we have a fully extracted codebase in SCIO-DB, we will need to be able to extract subsets of that codebase for (at least) two reasons:

1.  The size of output files - the current practical limits for the number of files that you can effectively manage (search, filter, etc.) in Excel/Calc (CSV) or SCWB (JSON) is about 500k and 150K respectively. These limits are also relative to the amount of column/field data in a file, but the primary constraint seems to be the number of rows.
2. The purpose of an analysis step - for the current D2D tracing of Deploy code to Devel code you need to create separate CSV files for the Deploy and Devel subsets of the codebase.

The general principle for defining the codebase file data (row) to be extracted is top-down - i.e. by specifying higher-level directories. It would be ideal to have some tree view of the codebase where you can check off the subsets of the codebase that you want to extract for analysis in Excel/Calc or SCWB.

**Comment by tdruez** [comment]
The ability to "Export current results as XLSX" for all list views was added in https://github.com/nexB/scancode.io/pull/496
The columns configuration will be implemented in https://github.com/nexB/scancode.io/issues/177
