### ISSUE TITLE
When displaying content of a binary CodebaseResource, say the strings are extracted

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#484]
When displaying content of a binary CodebaseResource, say the strings are extracted from binary.
This could came in the form a simple message after the filename such as `(text content isextracted from binary)` or an icon with this message as a hover.

**Comment by tdruez** [comment]
Resource flags (binary, archive, media) added in details view in https://github.com/nexB/scancode.io/commit/f44fd36091672e2f76ad71632d19d0851e82b087
