### ISSUE TITLE
Add archive, reset or delete from Projects list

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#488]
For a "project" or product with many SCIO Projects, you may need to delete many SCIO Projects. It would be helpful to be able to archive, reset or delete a project from the list on the Projects page rather than opening each SCIO Project to do that.

**Comment by moazzam07** [comment]
@tdruez @mjherzog is this issue is still open??

**Comment by tdruez** [comment]
@moazzam07 yes.

Make sure to read through the recently updated "contribution" section of the documentation first ;)
https://scancodeio.readthedocs.io/en/latest/contributing.html

**Comment by moazzam07** [comment]
ok

**Comment by moazzam07** [comment]
![image](https://user-images.githubusercontent.com/67731696/222375413-27734a76-78e0-40b5-8fdb-2fd1e0160765.png)
is it ok if i add dropdown after every project

**Comment by tdruez** [comment]
> is it ok if i add dropdown after every project

I think having the ability to run the action on multiple Projects at the time would be much more useful.

See https://github.com/nexB/scancode.io/issues for example:

![Screenshot 2023-03-02 at 09 50 54](https://user-images.githubusercontent.com/489057/222378656-a72c7a9d-33b4-44af-a84f-184905b77746.jpg)

**Comment by moazzam07** [comment]
Ok got it

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/924
