### ISSUE TITLE
Issue using web UI on deployed scancode.io docker container

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#489]
I've deployed scancode.io on a server using docker and I am accessing it through an ssh tunnel.

I am trying to create a project by setting a project name, uploading a file, and choosing a pipeline, but when I hit the create button, I am stuck at this screen 
![image](https://user-images.githubusercontent.com/6044800/183223864-260d7189-38ee-4f52-8ed3-7f90df74646e.png)

When I check the logs for the `scancodeio_web` container, there is a message
```
WARNING Forbidden (Origin checking failed - http://127.0.0.1:8001 does not match any trusted origins.): /project/add/
```

When I try to create an empty project, I get this message.
![image](https://user-images.githubusercontent.com/6044800/183224009-6b28c36c-0d78-4bc6-9147-bc5059928d76.png)

**Comment by tdruez** [comment]
We recently added support for the `CSRF_TRUSTED_ORIGINS` Django setting at https://github.com/nexB/scancode.io/blob/main/scancodeio/settings.py#L47

https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS

@JonoYang Could you try to set `CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8001` in your `docker.env` config file?

Let me know if that solve your issue and we'll add this to the documentation.

**Comment by JonoYang** [comment]
@tdruez Thanks, I've added `CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8001,http://localhost:8001` to `docker.env` and it fixed the issue!

**Comment by tdruez** [comment]
Ok great. Let's keep this one open until we add some notes to the documentation.

**Comment by tdruez** [comment]
Added in the docs.
