### ISSUE TITLE
Compressed docker image not recognized in docker pipeline

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#499]
I tried to scan this as a docker image: https://github.com/nyph-infosec/daggerboard/releases/download/v1.0.1/daggerboard_docker_image_v1-0-1.tgz and nothing happened. This is a docker "saved" image that's been gzipped and renamed to .tgz

**Comment by tdruez** [comment]
Looking at https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/docker.py#L48 and prior changes, it seems that we never supported the `.tgz` extension.

It should be fairly easy to update the glob pattern to capture `.tgz` along tars, assuming the `container_inspector.utils.extract_tar` supports `tgz` as well.
