### ISSUE TITLE
Ensure that the UI and JSON project reports contain a version that contains a commit and reflects which exact code is running

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#500]
Running the latest version of the tip of the main branch still reports a tag that's 6 months old.
It would be useful to have something that reflects the git commits status when I run from a checkout (or from an image built from a checkout).
Typically this is done with the output `git describe --tags`

**Comment by pombredanne** [comment]
See https://github.com/nexB/scancode-toolkit/blob/develop/.VERSION and https://github.com/nexB/scancode-toolkit/blob/develop/.gitattributes#L13 to get file file with version details populated when you pull a git archive.

**Comment by tdruez** [comment]
See https://github.com/nexB/scancode-toolkit/blob/8ed266372416a4e55cf739dadafa175214dca980/src/scancode_config.py#L70
