### ISSUE TITLE
Upgrade for fontawesome icons to v6

### ISSUE THREAD

**Issue by lf32** [nexB/scancode.io#509]
Can `scancode.io's` font awesome icons version be upgraded to `v6`? 

#### Reason
* A lot of icons are supported and can be used to replace `tags` in the project.

**Comment by pombredanne** [comment]
@lf32 a few questions for you:
1. what would be some of the icons that are in v6 and not in v5? 
2. Are these in the "free" or "commercial" distribution?
3. Are there any other major change to be aware of between v5 and v6 that could impact SCIO? any license change?

**Comment by lf32** [comment]
The main reason is to have file type icons over tags in `resource_detail.html` page and if we can replace the `tags` with `file type icons` then it would look better.

* The icon needed that is only available in v6 is a binary file icon. There might be a need for more icons in the future and v6 of fontawesome icons has a bulk number of icons.
  * v6 `file-binary` for `is-binary`,
  * v5 `file-lines` or `file-word` for `is-text`,
  * v5 `file-archive` for `is-archive`, 
  * v5 `file-search` for `is-key-file`, 
  * v5 `photo-video` for `is-media`
* I think there is a major problem with switching to v6 as bulma mentions they only support v4, v5 of fontawesome for now.
* Now I think there is no need to upgrade to v6 of fontawesome. I'll try to use the svg's of icons directly because there are only few icons needed.
* There is no change in the license. Its the same `MIT`, `ofl-1.1`, `cc-by-4.0`.
