### ISSUE TITLE
Add new field `extracted_to` to `CodebaseResource`

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#510]
In #485, we have an issue where we get two DiscoveredPackages for the same package when we scan a pypi wheel using the `scan_codebase` pipeline. This is happening because we report a Package detected from the wheel itself, and then we create another Package from the extracted METADATA file from the wheel. A way to avoid this would be for scancode.io to know where archives were extracted to. This way, if we detect that an archive is a Package, then we can easily tag its extracted contents as being part of that package. Alternatively, if we detect that an extracted archive is a package itself, then we can easily tag the archive as part of the package.

**Comment by uzaxirr** [comment]
Hey can i work on this?
Also can you please describe what the `extracted_to` field would look like? will it be a ForeignKey or what?

**Comment by uzaxirr** [comment]
@pombredanne ^^

**Comment by uzaxirr** [comment]
@TG1999 ^^

**Comment by pombredanne** [comment]
You sure can work on this! You would need to get familiar on how extractcode works and how extraction works in SCanCode.io. It extracts files to a directory. Keep the extracted_to would be about keeping track of which an archive is extracted to.

**Comment by pombredanne** [comment]
Closed in favor of https://github.com/nexB/scancode.io/issues/827
