### ISSUE TITLE
Improve XLSX output 

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#511]
I want to suggest two changes to the XLSX output to make the data easier to use for analysis.
- Change the worksheet names:
 - Discovered Packages => PACKAGES
 - Discovered Dependencies => DEPENDENCIES
 - Codebase Resource => RESOURCES
 We have been following a convention to capitalize worksheet names to make them easier to recognize vs workbook names.

- Add package_type field in the DEPENDENCIES worksheet to avoid more complex filtering by purl to get quick information about Dependency items when you have mixed types from a Scan.

**Comment by tdruez** [comment]
@JonoYang I've implemented the name changes in https://github.com/nexB/scancode.io/commit/2eb75e786fe8f9e50a5787eaad5e3aab7ec509bd

Could you address the following in the dependencies branch?

> Add package_type field in the DEPENDENCIES worksheet to avoid more complex filtering by purl to get quick information about Dependency items when you have mixed types from a Scan.
