### ISSUE TITLE
Error creating Docker images: "error while creating mount source path '/host_mnt/private/etc/scancodeio'"

### ISSUE THREAD

**Issue by ospaarmann** [nexB/scancode.io#513]
I tried the Docker installation following the docs on a MacBook Pro (Apple Silicon) with macOS Monterrey 12.5.1:

```
git clone https://github.com/nexB/scancode.io.git && cd scancode.io
make envfile
docker-compose build
docker-compose up
```

I encountered this error, and I'm wondering what the reason is. Did I miss a step? 

```
Status: Downloaded newer image for nginx:latest
Creating scancodeio_db_1    ... done
Creating scancodeio_redis_1 ... done
Creating scancodeio_web_1   ... error

ERROR: for scancodeio_web_1  Cannot start service web: error while creating mount source path '/host_mnt/private/etc/scancodeio': mkdir /host_mnt/private/etc/scancodeio: operation not permitted

ERROR: for web  Cannot start service web: error while creating mount source path '/host_mnt/private/etc/scancodeio': mkdir /host_mnt/private/etc/scancodeio: operation not permitted
ERROR: Encountered errors while bringing up the project.
```

When I try to create the folder manually, I also get an error: 

```
🤷 ❯ mkdir /host_mnt
mkdir: /host_mnt: Read-only file system
```

I could do that `sudo`, but I'm not sure that's the right way...

**Comment by tdruez** [comment]
@ospaarmann could you try to restart your Docker daemon, or alternatively your whole system, and try again?

**Comment by ospaarmann** [comment]
@tdruez I restarted both the system and Docker but the problem persists.

**Comment by ospaarmann** [comment]
@tdruez deleting the images, restarting docker and then building again did the trick. Thanks.
