### ISSUE TITLE
Scanning iperf with codebase pipeline has an empty "other" licenses list depiste showing 10 resources

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#526]
Take https://sourceforge.net/code-snapshots/svn/i/ip/iperf/code/iperf-code-r82-tags-2.0.5.zip
Scan with scan_codebase pipeline
The license pie chart shows 10 as a number of resources with "other" licenses, but clicking on the pie slice shows and empty list of resources

**Comment by tdruez** [comment]
Added support for filtering by "Other" values.
