### ISSUE TITLE
Package assembly issues with AboutFileHandler

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#530]
@JonoYang I'm getting 6 "DiscoveredPackage matching query does not exist" errors in the `assemble_package` step running the `scan_codebase` pipeline with the following input:
https://files.pythonhosted.org/packages/63/a8/f1566bfa76158f1088baf2b3e37bf0aba43666e182d63cd066ceed61699c/python_inspector-0.6.4-py3-none-any.whl

Those errors seems to all be related to the AboutFileHandler:
![Screenshot 2022-09-23 at 15 27 28](https://user-images.githubusercontent.com/489057/191950771-e8a08a1b-9d27-4060-b66a-ede87414a193.jpg)

**Comment by JonoYang** [comment]
@tdruez Looks like `AboutFileHandler.assemble()` is trying to assign a Resource to a Package before the Package is created in scancode.io. I've updated the code in `AboutFileHandler.assemble()` to yield Packages before assigning them to a Resource in https://github.com/nexB/scancode-toolkit/pull/3115

**Comment by tdruez** [comment]
@JonoYang thanks for the fix! Could you double check all the `FileHandler.assemble()` to make sure the Packages are properly yield before Resources?

**Comment by JonoYang** [comment]
@tdruez All `assemble()` methods of Package handlers in packagedcode yields Packages before Dependencies and Resources. Closing this now that we are using a scancode-toolkit version with these changes.
