### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by jayvdb** [nexB/scancode.io#550]
https://pypi.org/project/scancodeio/ is 404.

While PyPI may not be the recommended way to install this software, publishing to PyPI allows SCA tools to inspect this software (even basic tools like https://www.wheelodex.org/projects/plugincode/rdepends/ are useful), and Python distro packaging tools use PyPI as a source.

**Comment by pombredanne** [comment]
This makes perfect sense. Scheduling for v33

**Comment by tdruez** [comment]
Latest release published on pypi at https://pypi.org/project/scancodeio/
