### ISSUE TITLE
Getting error while trying to run Scancode.io in Gitpod.

### ISSUE THREAD

**Issue by 35C4n0r** [nexB/scancode.io#554]
I tried running Scancode.io in Gitpod but i was getting error on my port port 80 link:
```Bad Request (400)```

Refrence image
![image](https://user-images.githubusercontent.com/70096901/199739427-afda46e8-adb6-4789-aef4-394e9db42402.png)

**Comment by 35C4n0r** [comment]
The correct steps to run Scancode.io on gitpod is:

1. Create a new workspace for scancode.io

2. Open the workspace in your preferred IDE or VSCode Browser.

4. Open the terminal and run ```make envfile```.

5. An .env file will be created, and add  
          ```ALLOWED_HOSTS=.gitpod.io,127.0.0.1```
          ```CSRF_TRUSTED_ORIGINS=https://*.gitpod.io,http://127.0.0.1:8001```

6. Run 
            ```docker compose build```
            ```docker compose up```

7. Done.

**Comment by tdruez** [comment]
Let's add content from https://github.com/nexB/scancode.io/issues/554#issuecomment-1302164656 in the documentation ;)
