### ISSUE TITLE
Web app not working on any of servers!

### ISSUE THREAD

**Issue by swastkk** [nexB/scancode.io#557]
On the Fresh setup of the Project on Arch Linux, getting this error,
Followed each and every step carefully!!
Getting this error after writing command `` make run  ``

![error-scancode](https://user-images.githubusercontent.com/81990329/200193822-65804f19-6f7e-49c6-b9e6-9ef684939058.jpg)

Signed-off-by- swastkk@gmail.com

**Comment by tdruez** [comment]
Hi @swastkk looking at the error log it seems that the PostgresSQL database is not reachable by the app.
My guess is that Postgres is not running on your machine while it is a pre-requisite for running the app, see https://scancodeio.readthedocs.io/en/latest/installation.html#pre-installation-checklist

**Comment by swastkk** [comment]
I followed each steps correctly but still not able to use the PostgreSQL, but able to use the Web App with SQLlite Database, but wanted to know, whether there is any privation not using "psql" and using " sqlite"?

![Arch Linux_2022-11-07_23-46-53](https://user-images.githubusercontent.com/81990329/200384902-040c5063-c25f-4b98-a023-e0ef340331b9.jpg)

**Comment by tdruez** [comment]
See https://scancodeio.readthedocs.io/en/latest/installation.html#database and https://docs.djangoproject.com/en/dev/ref/databases/#sqlite-notes for the details about SQLite.

> I followed each steps correctly but still not able to use the PostgreSQL
Is PostgreSQL installed? Is the service running? Can you access the DB through a `psql` command?

**Comment by tdruez** [comment]
@swastkk Did you manage to figure out the PostgreSQL setup?

**Comment by swastkk** [comment]
@tdruez sir, actually I was unable to do so but project was working smoothly with MySQLiteDB so I decided to use it, but whenever I'll have time, I will surely use PostgreSQL database.
