### ISSUE TITLE
Applying filters on Project list should reset the current pagination

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#563]
To reproduce:
- Go to page 2 or more of the Project list
- Apply a status filter with no or few results expected

Currently:
> Not Found, The requested resource was not found on this server.

We should instead reset the pagination to page 1.

**Comment by swastkk** [comment]
Can you attach the Screenshot of What is currently going on, and what is needed to be done since I am unable to understand what is being asked :")

**Comment by PankajJaisu** [comment]
@tdruez @pombredanne @AyanSinhaMahapat I want to work on this issue, but I am not able to get the issue!In the issue description is mentioned that go to page 2 or more of the Project list but As  I am adding more no.of project it is getting added on first page itself I mean second page is not getting created. So can anyone explain me this issue using screenshots

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/pull/635
