### ISSUE TITLE
Errors due to new update in spdx-tools==0.7.0rc0

### ISSUE THREAD

**Issue by swastkk** [nexB/scancode.io#577]
1. Getting errors in `cant import Algorithm from spdx.checksum` and resolved by changing `renaming Algorithm to ChecksumAlgorithm`
2. Secondly, the `from spdx.document import License ImportError:` and I found that actually spdx has changed the location of License to license.py itself and then resolved by doing  `from spdx.license import License` .

**Comment by swastkk** [comment]
getting this error while make a PR on this issue and this issue https://github.com/nexB/scancode.io/issues/576
![Screenshot_2023-01-02_11-26-11](https://user-images.githubusercontent.com/81990329/210202207-605cbeb3-31d8-46b1-86cc-e20e562a60dc.jpg)

**Comment by pombredanne** [comment]
We have a pending PR for this https://github.com/nexB/scancode-toolkit/pull/3173

**Comment by pombredanne** [comment]
Please update https://github.com/nexB/python-inspector instead
Also you will need to update requirements.txt and setup.cfg there to ensure we have both minimum and pinned version of both packaging and packvers

**Comment by swastkk** [comment]
https://github.com/nexB/scancode.io/pull/586 will solve this too :")

**Comment by AyanSinhaMahapatra** [comment]
@swastkk could you check this is solved on develop and close this? same for #576

**Comment by swastkk** [comment]
> @swastkk could you check this is solved on develop and close this? same for #576

Yes 🙌 working smooth now :P, we should close this now.
