### ISSUE TITLE
Add "layers" data sheet for the xlsx output

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#578]
The current SCIO's xlsx output generate 4 worksheets:
 * PACKAGES
 * DEPENDENCIES
 * RESOURCES
 * ERRORS

From a user's prespective, it'll be great if it can also generate a "LAYERS" worksheet that log the docker command for each layer.
This information is listed in the JSON's output under the `created_by` key:
```
"extra_data": {
   ...
   "layers": [
      {
         "os": null
          ...
         "created_by": <docker command>
          ...
       }
   ]
}
```
The desire output would be something like
| Seq  | layer_tag | Docker command | layer_id |
| ------------- | ------------- | ------------- | ------------- |
| 1 | img-abababa-layer-01-xyxyxyx | /bin/sh -c #(nop) ADD file: xxxxxxxxxx in / | xyxyxyxyxyxyxyyxyxyxyxyxyxyx |
| 2 | img-abababa-layer-02-cdcdcd | /bin/sh -c #(nop) COPY dir: yyyyyyyyyyy in / | cdcdcdcdcdcdcdcdcdccdcdc |

**Comment by mjherzog** [comment]
+1

**Comment by tdruez** [comment]
@chinyeungli the LAYERS sheet is now available in the .xlsx when the data is available on the project.
The following fields are included:
- `layer_tag`
- `created_by`
- `layer_id`
- `image_id`
- `created`
- `size`
- `author`
- `comment`
