### ISSUE TITLE
Allow local settings file

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#58]
Following https://github.com/nexB/scancode.io/issues/56#issuecomment-730387125

I would be great to have a local setting file that's not the main version-controlled one and that would override the base settings.

**Comment by tdruez** [comment]
I think we want to move toward using the `.env` file for custom settings. 
See https://django-environ.readthedocs.io/en/latest/
This approach is ment to replace the multi setting files approach that is usually a source of pain.
