### ISSUE TITLE
How to find the files without licenses/copyright using this tool? is there a flag for that?

### ISSUE THREAD

**Issue by vvscloud** [nexB/scancode.io#580]
### Description

> I want to find out the files **without** licenses/copyright content using scancode. How can I do that? Also if I want to put a filter exclusively for finding images inside the source code repo, is it possible?

### System configuration

> For bug reports, it really helps us to know:

* Linux
* What installation method was used to install/run scancode? source

**Comment by pombredanne** [comment]
@vvscloud this is an example screen shot from scancode.io
![Screenshot from 2023-01-06 09-21-46](https://user-images.githubusercontent.com/675997/210960129-aaf73aad-b27e-4af6-8fd0-64f69d105d53.png)

You can see how the files without licenses and without copyright are shown in the pie charts.
And clicking it leads to the list:
![Screenshot from 2023-01-06 09-23-22](https://user-images.githubusercontent.com/675997/210960381-3ff96260-59fb-4009-a311-dadf28fede78.png)

The same data is available through the API for integration in your workflow.

**Comment by tdruez** [comment]
A new "Resources detected license expressions" panel was added in the project details view.
You click on the "no licenses" entry to view the list of files without licenses.
![Screenshot 2023-09-11 at 14 32 42](https://github.com/nexB/scancode.io/assets/489057/c3e45239-dc59-4903-8437-cc822280070d)

Alternatively, you can use the "Detected license expression" filter in the resources list view.
