### ISSUE TITLE
[Question] What is the difference between scan_codebase and scan_package?

### ISSUE THREAD

**Issue by soimkim** [nexB/scancode.io#581]
1. What is the difference between scan_codebase and scan_package?
 When I run the analysis, both have results in the code base and the results are also output in dependencies.

2. What tool does scancode.io use to analyze docker in Pipeline?

**Comment by pombredanne** [comment]
Dear @soimkim you wrote: 

> 1. What is the difference between scan_codebase and scan_package?
> When I run the analysis, both have results in the code base and the results are also output in dependencies.

You can see the different steps in the web UI and in https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/scan_codebase.py and https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/scan_package.py

The key differences are that the scan_package pipeline treats the scan codebase as if it were a single package and computes a License clarity and a Scan summary to aggregate the package scan data.

 
![Screenshot from 2023-01-06 09-09-33](https://user-images.githubusercontent.com/675997/210958182-65532ed1-1aca-4bac-a8b4-c1617abebec9.png)

In contrast, the `scan_codebase` pipeline is more of a general purpose pipeline, and make no such single package assumption. (and does not compute such summary)

> 2. What tool does scancode.io use to analyze docker in Pipeline?

It uses scancode.io , https://github.com/nexB/scancode-toolkit , https://github.com/nexB/container-inspector https://github.com/nexB/debian-inspector https://github.com/nexB/extractcode and secondary libraries and plugins from https://github.com/nexB/scancode-plugins/tree/main/builtins 

- the core logic for handling containers and distros is in container-inspector and scancode.io
- the core logic to fetch containers is in fetchcode_container and scancode.io
- the core logic for application package scans and system package scans is in scancode-toolkit and in scancode.io (we handle Debian/Ubuntu, RPMs, distroless and Alpine distro for now)

Specific handling of windows containers is done in scancode-toolkit to process the windows registry.

The pipeline is at https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/docker.py and is hopefully designed to be simple and readable code.

I would value very much your feedback there!

@soimkim if you like we could have a call together and I could do a demonstration at some point of time!

**Comment by tdruez** [comment]
Added a new entries in the FAQ:
- https://scancodeio.readthedocs.io/en/latest/faq.html#what-is-the-difference-between-scan-codebase-and-scan-package-pipelines
- https://scancodeio.readthedocs.io/en/latest/faq.html#what-tool-does-scancode-io-use-to-analyze-docker-images
