### ISSUE TITLE
The following plugin(s) are referenced and cannot be loaded/imported: scancodeio-worker-1  | cannot import name 'Algorithm' from 'spdx.checksum' (/usr/local/lib/python3.9/site-packages/spdx/checksum.py)

### ISSUE THREAD

**Issue by Adarsh01** [nexB/scancode.io#582]
Getting this error after running  "docker compose up" command.

"scancodeio-worker-1  | ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
scancodeio-worker-1  | Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
scancodeio-worker-1  | The following plugin(s) are referenced and cannot be loaded/imported:
scancodeio-worker-1  | cannot import name 'Algorithm' from 'spdx.checksum' (/usr/local/lib/python3.9/site-packages/spdx/checksum.py)
"

**Comment by pombredanne** [comment]
@Adarsh01 Thanks for the report. This is because of a bug in ScanCode toolkit at https://github.com/nexB/scancode-toolkit/issues/3179 that is being fixed soon.

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne I think you meant https://github.com/nexB/scancode-toolkit/pull/3173

**Comment by pombredanne** [comment]
Good point! actually I pinned the SPDX library in Scancode Toolkit 31.2.3 so this is not really tracked anywhere. This was with https://github.com/nexB/scancode-toolkit/commit/b4f497c05fc4a04c75ed85aaacba2b452ca3004c and nexB/scancode-toolkit#3171 and nexB/scancode-toolkit#3177

**Comment by AyanSinhaMahapatra** [comment]
@Adarsh01  could you check this is solved on develop so we can close this?

**Comment by AyanSinhaMahapatra** [comment]
Closing this, as we've fixed this!
