### ISSUE TITLE
Add support for CycloneDX 1.4 to the "inspect-manifest" pipeline to import the SBOM into a Project

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode.io#583]
Add support for CycloneDX 1.4 to the "inspect-manifest" pipeline to import the SBOM into a Project

**Comment by DennisClark** [comment]
we need to provide a good example of an SPDX 2.3 import to indicate how this might best be done.

**Comment by pombredanne** [comment]
This may depend on https://github.com/CycloneDX/cyclonedx-python-lib/pull/290
@madpah gentle ping

**Comment by tdruez** [comment]
@keshav-space re-opening as the `validate_document` function as a dependency on internet access that need to be removed.

To reproduce, turn-off your internet connection and the following unit test will fail:
- test_scanpipe_inspect_manifest_pipeline_cyclonedx_integration_test
- test_scanpipe_cyclonedx_validate_document

The seems to be an issue with the validate_document function. That code and the tests should never depend on having internet connectivity.

**Comment by keshav-space** [comment]
@tdruez turns out RefResolver was not using the local file path provided in `base_uri`.
Its been fixed in #634 and now it works offline.

**Comment by tdruez** [comment]
@keshav-space fix confirmed, thanks!
