### ISSUE TITLE
Add SPDX license expressions to the output

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#597]
Today we only display license expressions and license data using ScanCode LicenseDB keys. We should also display these with an SPDX license expression.

**Comment by AyanSinhaMahapatra** [comment]
Could be done as a part of https://github.com/nexB/scancode.io/issues/569? Since we have new fields for SPDX expressions in packages/resources.

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra perfect!

**Comment by tdruez** [comment]
Following the toolkit v32 upgrade, we now have SPDX version of the license expressions on the model and in the UI/results.
