### ISSUE TITLE
Create a GitHub action to create an SBOM

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode.io#599]
Create a GitHub action using scancode.io:

- use package/dependencies/vulnaribility data from scancode.io
- to output a SPDX/CycloneDX SBOM
- upload this as an artifact created by the action (like artifacts created on tag push/release)

**Comment by asmitrai** [comment]
hey, can you assign me to this? i can do it

**Comment by tdruez** [comment]
New action available at https://github.com/nexB/scancode-action
