### ISSUE TITLE
Add support for RPM-based distros for docker and rootfs images scanpipe

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#6]
There is no easy way to access the RPM database but through librpm and the rpm executable.
The installed RPMs database comes in three formats:

1. *bdb*: a legacy Berkeley DB hash used as a key/value where the value is a binary blob that contains all the RPM data. The format of this blob should be the same as the RPM header format and scancode-toolkit can parse the headers.  This is the format that was/is used in older RH, CentOS, Fedora and most every RPM distros.
2. *sqlite*: a SQLite database where one table is used as a key/value store where the value is a binary blob that contains all the RPM data in the same binary format as in 1. and the RPM header. This is the format that is used in newer RH, CentOS and Fedora versions.
3. *ndb*: a new key/value store that is built-in librpm. This is the format used by newer openSUSE distros

librpm provides support for each of these formats and also contains a built-in read-only handler for the 1. `bdb` format such that librpm can be built without Berkeley DB and still can read an older RPM db (for instance to convert it to a newer format).

It needs to be built with specific flags to enable all these formats (typically a given build of a distro does not nee to support all the formats).

The installed DBs locations are:

Distro             | Path                                    | Format   
------------------ | ----------------------------------- |--------------------------------
CentOS 8       |  `/var/lib/rpm/Packages`     | Berkeley DB (Hash, version 9, native byte-order)
CentOS 5       |  `/var/lib/rpm/Packages`     | Berkeley DB (Hash, version 8, native byte-order)
Fedora 30      |  `/var/lib/rpm/rpmdb.sqlite`  | SQLite 3.x database
Fedora 20      | `/var/lib/rpm/Packages`       | Berkeley DB (Hash, version 9, native byte-order)
openMandriva  |  `/var/lib/rpm/Packages`     | Berkeley DB (Hash, version 10, native byte-order)
RHEL 8          |  `/var/lib/rpm/Packages`     | Berkeley DB (Hash, version 9, native byte-order)
openSUSE 20200528 |  `/usr/lib/sysimage/rpm/Packages.db` | data, but this is the ndb format

In addition on Fedora distros there are files under `/etc/yum.repos.d/*` that contains base and mirror URLs for the repo used to install RPMs. Each file is in .ini format. On openSUSE and SLES, these are under `/etc/zypp/repos.d`

The licenses (when not deleted as in some CentOS Docker images) are found in `/usr/share/licenses/<package name>/<license files>` or `/usr/share/doc/<package name>/<license files>`

 
If using the `rpm` cli, this can create an XML like output:
`./rpm --query --all  --qf '[%{*:xml}\n]' --rcfile=./rpmrc  --dbpath=<path to>/var/lib/rpm > somefile.xml`
The .rcfile option may not be needed, but when using a fresh RPM build this is needed.

The RPM db may need to be rebuilt first when this is a bdb format from an older version than the bdb with which librpm was built.

**Comment by pombredanne** [comment]
To parse simply the XML output of the rpm command
```
>>> import xmltodict
>>> rpm=open('rpm.xml.txt','rb').read()
>>> rpm=rpm.decode('utf-8', errors='ignore')
>>> rpms = ['<rpmHeader>' + val for val in rpm.split('<rpmHeader>') if val]
>>> parsed=[xmltodict.parse(r) for r in rpms]
```
I have also attached that sample XML created with:
`rpm --query --all --qf '[%{*:xml}\n]' --dbpath=<path to RPM DB directory typically some /var/lib/rpm/ > ~/rpm.xml.txt`

[rpm.xml.txt](https://github.com/nexB/scancode.io/files/5769697/rpm.xml.txt)

**Comment by pombredanne** [comment]
Note that for the odd cases where the rpmdb is not in the format that the current rpm tool can analyze, the process could be to rebuild the database, though it is not entirely clear if this may not be missing out some RPMs (if so we may need to either read the RPM db directly OR use multiple older version of the RPM exe)

1. make a copy of the DB and work on that copy since this is destructive
2. Run `rpmdb --rebuilddb --dbpath=<path to RPM DB directory typically some /var/lib/rpm/ where the copy was made> --root=<path to the pseudo root of the filesystem>`

**Comment by chinyeungli** [comment]
@pombredanne I have written a simple parser to parse the above XML file and convert to a JSON file.
See https://github.com/nexB/spats/blob/rpm_xmltodict_parser/src/spats/parse_rpm_db.py
Attached the parsed result: 
[parsed.json.txt](https://github.com/nexB/scancode.io/files/5775279/parsed.json.txt)
There are some logical things that need to be done for 
`Dirindexes`, `Dirnames` and `Fileclass`, `Classdict`
but I don't know what's the desire output that the pipeline need.

Suggestion and feedback are welcome.

**Comment by tdruez** [comment]
@pombredanne running a docker pipeline on a `rpm-centos-latest.tar` image with the latest `6-rpm-support` branch (scancode-toolkit[packages]==21.3.31):

```
collect_installed_rpmdb_xmlish_from_rpmdb_loc: Failed to execute RPM command: /usr/local/lib/python3.9/site-packages/rpm_inspector_rpm/bin/rpm --query --all --qf [%{*:xml}
] --dbpath /var/scancodeio/workspace/projects/rpm-eb756fcb/codebase/50-rpm-centos-latest.tar-extract/cbab9bd72bc8f39dfc72b687ab56cd464589268d2a468ea8104fee89e4ca8b84/var/lib/rpm
/usr/local/lib/python3.9/site-packages/rpm_inspector_rpm/bin/rpm: error while loading shared libraries: libpopt.so.0: cannot open shared object file: No such file or directory
Traceback:
  File "/opt/scancodeio/scanpipe/pipelines/__init__.py", line 95, in execute
    step(self)
  File "/opt/scancodeio/scanpipe/pipelines/docker.py", line 79, in collect_and_create_system_packages
    docker.scan_image_for_system_packages(self.project, image)
  File "/opt/scancodeio/scanpipe/pipes/docker.py", line 122, in scan_image_for_system_packages
    for i, (purl, package, layer) in enumerate(installed_packages):
  File "/usr/local/lib/python3.9/site-packages/container_inspector/image.py", line 329, in get_installed_packages
    for purl, package in layer.get_installed_packages(packages_getter):
  File "/opt/scancodeio/scanpipe/pipes/rpm.py", line 30, in package_getter
    packages = rpm.get_installed_packages(root_dir, detect_licenses=detect_licenses)
  File "/usr/local/lib/python3.9/site-packages/packagedcode/rpm.py", line 163, in get_installed_packages
    xmlish_loc = rpm_installed.collect_installed_rpmdb_xmlish_from_rootfs(root_dir)
  File "/usr/local/lib/python3.9/site-packages/packagedcode/rpm_installed.py", line 401, in collect_installed_rpmdb_xmlish_from_rootfs
    return collect_installed_rpmdb_xmlish_from_rpmdb_loc(rpmdb_loc)
  File "/usr/local/lib/python3.9/site-packages/packagedcode/rpm_installed.py", line 456, in collect_installed_rpmdb_xmlish_from_rpmdb_loc
    raise Exception(msg)
```

**Comment by pombredanne** [comment]
I pushed a new RPM plugin for the toolkit https://pypi.org/project/rpm-inspector-rpm/4.16.1.3.210404/ and two commits:
- https://github.com/nexB/scancode.io/commit/52bbe6a7514149a95f8188cea987007776e0fc97
- https://github.com/nexB/scancode.io/commit/8bc9b4a0fec76a1c12428f7df637428e9343f34c
and this make things work on Linux. I still need to have a few more refinements to also run on macOS with RPM in the path

**Comment by pombredanne** [comment]
I tested locally on a centos: latest docker image with success
