### ISSUE TITLE
[Documentation Error]: Collation error in make postgresdb command

### ISSUE THREAD

**Issue by swastkk** [nexB/scancode.io#604]
Reference-
https://stackoverflow.com/questions/18870775/how-to-change-the-template-database-collection-coding

**Comment by AyanSinhaMahapatra** [comment]
@swastkk we should all the details while adding an issue:

Often we have this error on `make postgresdb`:
```
createdb: error: database creation failed: ERROR:  new collation (en_US.UTF-8) is incompatible with the collation of the template database (en_IN)
```
And to solve this we have to follow this answer specifically: https://stackoverflow.com/a/60396581/8254946 and replace `'zh_CN.UTF-8'` with `'en_US.UTF-8'` in this case.

It could be that this is a bug in the makefile and the `make postgresdb` command can be improved to fix this issue.
Otherwise we need to document this in the installation guide.

**Comment by tdruez** [comment]
@swastkk could you provide the output when running the `make postgresdb` command?

**Comment by swastkk** [comment]
@tdruez actually now my `make postgresdb` is working fine now after the clean re-installation of `scancode.io` and cleaning `postgres`, since @AyanSinhaMahapatra had faced such kind off issue, so he helped in the Status Call and made everything working.
Error was 
```
createdb: error: database creation failed: ERROR:  new collation (en_US.UTF-8) is incompatible with the collation of the template database (en_IN)
```
due to 
https://github.com/nexB/scancode.io/blob/4e5b4dc3392c5f426e949dac146060180fdcd450/Makefile#L39
https://github.com/nexB/scancode.io/blob/4e5b4dc3392c5f426e949dac146060180fdcd450/Makefile#L106

**Comment by tdruez** [comment]
@AyanSinhaMahapatra @swastkk anything else needed here or are we ready to close?

**Comment by AyanSinhaMahapatra** [comment]
@tdruez not sure if this is a bug in the make script, because we are passing the `--lc-collate` argument. But at least we need this to be mentioned in the docs?

**Comment by swastkk** [comment]
I guess we should close this issue now.

**Comment by AyanSinhaMahapatra** [comment]
@swastkk see https://github.com/nexB/scancode.io/issues/604#issuecomment-1434242010

This can still happen while setting up a scancode.io instance for the first time, and we still need to follow these instructions: https://stackoverflow.com/questions/18870775/how-to-change-the-template-database-collection-coding/60396581#60396581 to fix this, so this need to be documented atleast. Or it would be nice if it can be fixed.

**Comment by swastkk** [comment]
> @swastkk see https://github.com/nexB/scancode.io/issues/604#issuecomment-1434242010
> 
> This can still happen while setting up a scancode.io instance for the first time, and we still need to follow these instructions: https://stackoverflow.com/questions/18870775/how-to-change-the-template-database-collection-coding/60396581#60396581 to fix this, so this need to be documented atleast. Or it would be nice if it can be fixed. 

Oh sorry actually I didn't see your above comment, should I change the docs accordingly and make a PR?

**Comment by tdruez** [comment]
Added warning in https://github.com/nexB/scancode.io/commit/c2d8f0d6bd3504cdecfd79748a6192389bf06c1b
