### ISSUE TITLE
Analyze Docker Image (Web UI): No image found error

### ISSUE THREAD

**Issue by aadityasinha-dotcom** [nexB/scancode.io#605]
While putting `https://hub.docker.com/r/alpine/httpie/` as download URL getting no image found error. same goes while giving empty input.

![2023-02-14_093318-](https://user-images.githubusercontent.com/75474786/218636676-ce9be5d7-e6f1-4f4c-bd93-f74c73de32cb.png)

```python
No images found in project input files.

Traceback:
  File "/app/scanpipe/pipelines/__init__.py", line 122, in execute
    step(self)
  File "/app/scanpipe/pipelines/docker.py", line 56, in extract_images
    raise Exception("No images found in project input files.")
```
Reference: https://scancodeio.readthedocs.io/en/latest/tutorial_web_ui_analyze_docker_image.html
Signed-off-by: Aaditya Sinha [aadityasinha009@gmail.com](mailto:aadityasinha009@gmail.com)

**Comment by tdruez** [comment]
@aadityasinha-dotcom `https://hub.docker.com/r/alpine/httpie/` is not a download URL, it lead to a webpage.

From https://scancodeio.readthedocs.io/en/latest/tutorial_web_ui_analyze_docker_image.html#instructions

> Paste the input Docker image’s URL, [docker://alpine/httpie](https://hub.docker.com/r/alpine/httpie/), in the “Download URL” field, which fetches the image from the provided URL.

You want to use the `docker://alpine/httpie` syntax instead.

**Comment by AyanSinhaMahapatra** [comment]
@tdruez this was reported in the community call and we asked him to open a issue for:

If we do not give any inputs and select and execute a pipeline, it starts and fails like mentioned above. @pombredanne said we should not fail here and likely prompt the user for input, and/or implement something common for the CLI/UI usage.

What do you think?
