### ISSUE TITLE
Cannot run `scanpipe` command when running ScanCode.io on Docker

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#616]
I'm running ScanCode.io on Docker and I've enabled authentication. I need to create a user account using the command `scanpipe create-user <username>`, so I can log in. Since I'm using Docker, I have to run the command from ScanCode.io's "web" container, so I run: 

- `docker compose exec -it web scanpipe create-user <username>` 

However, I get the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/scanpipe", line 5, in <module>
    from scancodeio import command_line
ModuleNotFoundError: No module named 'scancodeio'
```

I'm able to create a user account if I run `docker compose exec -it web /app/manage.py create-user <username>`

**Comment by tdruez** [comment]
@JonoYang thanks for reporting this.
The Dockerfile was missing the PYTHONPATH setup.
Also, I've refine the CLI documentation to clarify the ``scanpipe`` command usages through Docker compose.

Could you test the PYTHONPATH fix and review the documentation changes as well? Available at https://github.com/nexB/scancode.io/pull/617
