### ISSUE TITLE
Do not report a package as vulnerable when the version is fixing a vulnerability

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#622]
On a requirements.txt file with:
```
cryptography==38.0.3
```
Run `inspect_manifest` then `find_vulnerabilities`
This package is reported as vulnerable incorrectly.

Same with:
```
django==3.2.16
```

In both cases, these are fixing vulns and these versions are not vulnerable.

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra Yes!

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/pull/797
