### ISSUE TITLE
Remove dead code for the project_tree

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#623]
Using the /tree URL on a project will go 500 and is code that is using a CDN and cannot work offline.
We should remove https://github.com/nexB/scancode.io/blob/main/scanpipe/templates/scanpipe/project_tree.html and the view code behind it

**Comment by sivangbagri** [comment]
Hii I would like to work on this issue Please assign me this issue :)

**Comment by moazzam07** [comment]
@pombredanne should we have to remove this file??
