### ISSUE TITLE
Create a Homepage for presenting Scancode.io

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io#63]
Available at https://scancode.io/

See the https://github.com/nexB/scancode.io/tree/pages branch for progress using GitHub Pages.

**Comment by theCodeKeep** [comment]
Sir, I want to contribute in this project. 
I am new in Open Source, it would be really helpful if you guide me through.

Thanks and Regards

**Comment by tdruez** [comment]
The goal a to create a simple presentation homepage of the ScanCode.io project.

The code should be in HTML/CSS.

The page should list the key features and benefits of the app and also provide all the relevant links to:
- The documentation
- The GitHub repo
- The source
- The releases

@theCodeKeep Sir, feel free to submit a prototype in a branch and we can iterate from there.

**Comment by ThatOneTallKid** [comment]
I also want to contribute to this task

**Comment by tdruez** [comment]
@ThatOneTallKid please do ;)

**Comment by ThatOneTallKid** [comment]
Any specific color schema you want me to follow?

**Comment by tdruez** [comment]
@ThatOneTallKid not in particular, make sure the code is structured in a way to make it easy to make changes to the color scheme.

**Comment by ThatOneTallKid** [comment]
Ok sure sir!

**Comment by gauravgulati15** [comment]
@tdruez Can I contribute to this task if it's not complete?

**Comment by tdruez** [comment]
@gauravgulati15 Yes, see https://github.com/nexB/scancode.io/issues/63#issuecomment-754794624 for layout suggestions.

**Comment by gauravgulati15** [comment]
Okay, will get back to you asap!

**Comment by gauravgulati15** [comment]
@tdruez is there any logo for ScanCode.io or should I just use the nexB logo?

**Comment by gauravgulati15** [comment]
@tdruez I have made the draft home page for ScanCode.io. The GitHub repo link -[HomePage](https://github.com/gauravgulati15/ScanCode.io-HomePage)

**Comment by tdruez** [comment]
@gauravgulati15 There's no logo yet, feel free to put simply ScanCode.io in text as a placeholder for now.
Your link of the draft is not working by the way.

**Comment by gauravgulati15** [comment]
@tdruez  Oh I am sorry for that! I made the repository private by mistake, now its public you can see it!

**Comment by divya814** [comment]
@tdruez Sir, I wish to work for the enhancement of the homepage.

**Comment by tdruez** [comment]
@divya814 sounds good 👍

**Comment by tdruez** [comment]
Suggested by @AyanSinhaMahapatra for ideas : https://www.btw.so/marketing/landing-page-examples

**Comment by tdruez** [comment]
Available at https://nexb.github.io/scancode.io/
