### ISSUE TITLE
Add Copyright Holder information for Packages

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#631]
The JSON and XLSX download files from SCIO do not include Holder data for Packages. I do not see the `holder` field in either file, but we do display a pie-chart for Holders in the SCIO UI which indicates that we probably have the Holder data in the SCIO database but are not including it in the JSON or XLSX downloads for packages. We have the copyright notice and holder data for Resources in the JSON and XLSX download files.

This Issue is separate from Issue #86 which concerns the much bigger issue of how to get better copyright notice data for packages where that data is not available from package metadata.

**Comment by tdruez** [comment]
> The JSON and XLSX download files from SCIO do not include Holder data for Packages.

Holder data is not available for Packages as there's no `holder` field on the DiscoveredPackage model in SCIO, this is inherited from ScanCode-toolkit PackageData model https://github.com/nexB/scancode-toolkit/blob/3021c7442647b029f6118b0ac6eb70e56f166f19/src/packagedcode/models.py#L535

> we do display a pie-chart for Holders in the SCIO UI which indicates that we probably have the Holder data in the SCIO database but are not including it in the JSON or XLSX downloads for packages. 

The `holder` field is available on the CodebaseResource model, thus displayed in the "Codebase Resources" section of the pie-charts and included in the outputs along the resources.

@pombredanne are any changes regarding this planned on the toolkit side?

**Comment by tdruez** [comment]
The `holder` field and value is now available following the toolkit upgrade to v32.

From https://github.com/nexB/scancode-toolkit/blob/develop/CHANGELOG.rst?plain=1#L120

>  The PackageData model now includes a ``holder`` field, which is populated with
  holder data extracted from the copyright field if copyright data is present,
  otherwise it remains empty.
