### ISSUE TITLE
ScanCode sends signal 9 - worker timeout

### ISSUE THREAD

**Issue by RabeeaEgbareia** [nexB/scancode.io#642]
Hi,
I'm facing this issue a lot and it started to be reproduced every run .. 
I have this conf in docker.env

POSTGRES_DB=scancodeio
POSTGRES_USER=scancodeio
POSTGRES_PASSWORD=scancodeio
POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8

SCANCODEIO_DB_HOST=db
SCANCODEIO_REDIS_HOST=redis
SCANCODEIO_ASYNC=True
SCANCODEIO_WORKSPACE_LOCATION=/var/scancodeio/workspace/
SCANCODEIO_REST_API_PAGE_SIZE=5000
SCANCODEIO_PROCESSES=20
SCANCODE_TOOLKIT_CLI_OPTIONS=--timeout 300 --processes 20
SCANCODEIO_LOG_LEVEL=DEBUG

And these are the errors I get (from container logs)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:19)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:21)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:23)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:25)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:27)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:29)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:31)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [16] [CRITICAL] WORKER TIMEOUT (pid:33)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [21] [INFO] Worker exiting (pid: 21)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [25] [INFO] Worker exiting (pid: 25)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [27] [INFO] Worker exiting (pid: 27)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [23] [INFO] Worker exiting (pid: 23)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [31] [INFO] Worker exiting (pid: 31)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [29] [INFO] Worker exiting (pid: 29)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [33] [INFO] Worker exiting (pid: 33)
scancodeio-web-1                  | [2023-03-22 08:27:38 +0000] [19] [INFO] Worker exiting (pid: 19)
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 21 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 27 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 23 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 31 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 29 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 25 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 33 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [35] [INFO] Booting worker with pid: 35
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [37] [INFO] Booting worker with pid: 37
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [16] [WARNING] Worker with pid 19 was terminated due to signal 9
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [39] [INFO] Booting worker with pid: 39
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [41] [INFO] Booting worker with pid: 41
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [43] [INFO] Booting worker with pid: 43
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [45] [INFO] Booting worker with pid: 45
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [47] [INFO] Booting worker with pid: 47
scancodeio-web-1                  | [2023-03-22 08:27:40 +0000] [49] [INFO] Booting worker with pid: 49

Any help ?

**Comment by RabeeaEgbareia** [comment]
@tdruez I got it .. I have 8 GB memory and 6 CPUs. I will try remove this 20 processes configuration and scan again.

![image](https://user-images.githubusercontent.com/128488364/226937459-0b0201ee-6c6c-4390-8db9-86171fbdeab7.png)

**Comment by RabeeaEgbareia** [comment]
@tdruez @AyanSinhaMahapatra 
I re-installed scancode.io again including fresh install of the db .. all the app is new, I still getting this:

INFO scan_for_package_data 26.4% (50403/191231) completed pk=769006
INFO scan_for_package_data 26.4% (50404/191231) completed pk=769004
04:32:04 Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.
04:32:29 Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)
04:32:29 Handling failed execution of job c6c19d9b-3db7-4fde-aec8-4e8fb6eb52d4
04:32:30 Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
04:32:30 Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
04:32:30 Cleaning registries for queue: default
INFO Synchronizing QUEUED and RUNNING Run with their related Jobs...
INFO 1 Run to synchronize:
INFO Job found as failed for RUNNING Run=c6c19d9b-3db7-4fde-aec8-4e8fb6eb52d4. Flagging this Run as FAILED.
04:32:32 *** Listening on default...

**Comment by tdruez** [comment]
Have you tried disabling multiprocessing as suggested in https://github.com/nexB/scancode.io/issues/642#issuecomment-1480069331 ?

**Comment by RabeeaEgbareia** [comment]
@tdruez 
I removed all the scancode.io (including the db) and made fresh install and still getting the issue on mac.

**Comment by tdruez** [comment]
@RabeeaEgbareia Have you tried disabling multiprocessing as suggested in https://github.com/nexB/scancode.io/issues/642#issuecomment-1484893149 ?

https://scancodeio.readthedocs.io/en/latest/scancodeio-settings.html#scancodeio-processes
```
SCANCODEIO_PROCESSES=-1
```

**Comment by RabeeaEgbareia** [comment]
@tdruez 
No. I installed the docker on linux instead of mac and it seems more stable (still failing but with low frequency)
I do not want to disable the multiprocessing, it will make the scan very slow, right ?

**Comment by RabeeaEgbareia** [comment]
@tdruez 
A general question: 
Is there any difference between scanning files using scancode-toolkit directly with cli and scanning using scancode.io pipelines ? ( for license detection )

**Comment by tdruez** [comment]
@RabeeaEgbareia The goal is to debug your issue at that point, thus my suggestion to test without multiprocessing to make sure this is not the source of the problem.
