### ISSUE TITLE
SCIO: Make basic to-from/d2d project

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#659]
I want to start by creating a project with two input archives renamed before upload with a special prefix such as "FROM-"/"TO-" or "TRACE-FROM-"/"TRACE-TO-" or "Input-1-"/"Input-2-"

- The Input-1/FROM archive typically represents the binaries or deployed code
- The Input-2/TO archive typically represents the sources or development code

Then we want to have a pipeline that will
- extract recursively the archives of both trees, such that we know which is 1 and 2
- find a match between the two based on various approaches: exact file matching and path matching
- the pipeline should store this when a file in 1 is mapped to file in 2 with relationship. The relationship may need qualifiers, such as a type of relationship and how this is mapped (such as a path match score, tbd.). SPDX and CDX relationships may be a good inspiration for names and types. https://spdx.github.io/spdx-spec/v2.3/relationships-between-SPDX-elements/
- SCIO should provide some UI to display these mappings and review things that are not mapped.

**Comment by pombredanne** [comment]
As a first test data we could use the binary and source jars in https://repo1.maven.org/maven2/org/apache/flume/flume-ng-node/1.9.0/

**Comment by tdruez** [comment]
https://github.com/nexB/scancode.io/pull/666
