### ISSUE TITLE
Replacement of MakeFile with Ninja

### ISSUE THREAD

**Issue by swastkk** [nexB/scancode.io#664]
Can replace `MakeFile` with `Ninja Build system`

Reason- Speeeed
Reference- https://ninja-build.org/

**Comment by swastkk** [comment]
> @swastkk Which part of using `make` in the context of ScanCode.io is too slow?

Can't say about whether it is slow or fast, but it was a suggestion,
Actually I was using `ninja` in my other project, so was thinking to implement the same here as well, i know `make` has many more features like-
![Screenshot_2023-04-07_13-10-52](https://user-images.githubusercontent.com/81990329/230565158-50a2763b-9ad8-48b3-9704-b470c3dc2bde.jpg)

**Comment by tdruez** [comment]
@swastkk  `make` is generally available by default. `ninja` requires to be installed making the whole ScanCode.io setup more complex for no obvious reasons.
Let's not introduce un-needed dependencies to something as critical as the installation of the app.

**Comment by swastkk** [comment]
> @swastkk `make` is generally available by default. `ninja` requires to be installed making the whole ScanCode.io setup more complex for no obvious reasons. Let's not introduce un-needed dependencies to something as critical as the installation of the app.

Ya, you are right :raised_hands:
Closing this since I got the answer.
