### ISSUE TITLE
SCIO 32.1.0 reports conjunctive rather than disjunctive license expression for slint v1.0.0

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode.io#668]
A recent scan using SCIO v32.1.0 of the code available at https://github.com/slint-ui/slint/archive/refs/tags/v1.0.0.tar.gz reported a declared license expression of `gpl-3.0 AND proprietary-license` even though the notices state that there is actually a choice of licenses.  

from README.md: 
```
## License

Slint is available under either a [proprietary license](LICENSES/LicenseRef-Slint-commercial.md)
or [GNU GPLv3](LICENSES/GPL-3.0-only.txt)

The proprietary license is provided free-of-charge in exchange for (1) consent that we can showcase the application, (2) attribution of Slint in the application and (3) feedback to improve Slint.
Check out our [ambassador program](https://slint-ui.com/ambassador-program.html).
```

from LICENSE.md
```
# Slint License

Slint is available under either a [proprietary license](LICENSES/LicenseRef-Slint-commercial.md)
or [GNU GPLv3](LICENSES/GPL-3.0-only.txt).

Third party licenses listed in the `LICENSES` folder also apply to parts of the product.
```

The either/or construction clearly indicates a disjunctive choice of licenses rather than a conjunctive combination of licenses.  The correct license expression would be: 
`gpl-3.0 OR proprietary-license`

**Comment by tdruez** [comment]
@DennisClark @pombredanne That would be an issue on the ScanCode-toolkit side. SCIO is just storing scan data as returned by the toolkit.

**Comment by DennisClark** [comment]
oops, my mistake.  Opened new issue https://github.com/nexB/scancode-toolkit/issues/3316  for this problem and closing this issue.
