### ISSUE TITLE
Other tarball extensions to be recognized for docker analysis in scanpipe

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode.io#67]
The current code only accept "*.tar.*". However, there may be a case that the docker image tarball ends with `.tgz`
The code should have that cover.

**Comment by tdruez** [comment]
All the default pipelines are now using the extractcode API for the archives extraction. 
Thus, all the extensions supported by extractcode are now supported in ScanCode.io, including `.tgz`.

@chinyeungli please try again and let me know if your `.tgz` is not properly extracted. That would be a bug.
