### ISSUE TITLE
Add PurlDB matching step to Java pipeline

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#674]
When analyzing a whole Java application, an early step in the pipeline is to lookup all the .jar and .war files in the PurlDB with an exact match (like a SHA1)

The output should be to create DiscoveredPackage in the project.

When this takes in the context of the `develop_to_deploy` pipeline, this step should only occur on the "To" side of the codebase.

This does not replace the develop to deploy mapping.

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/666
