### ISSUE TITLE
Create UI to list and download outputs created by a pipeline

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#678]
Today a pipeline can create new outputs in the /outputs sub directory of the workspace but these are only accessible from the command line.
I would like to have a UI that lists these outputs that I can click and download without using the CLI.

**Comment by pombredanne** [comment]
We are for now instead creating a dedicated output in the main UI for attribution #684

**Comment by pombredanne** [comment]
It would be especially useful to get the scancode-toolkit scan from scan_package pipeline as part of #815 so we could fetch the scans completed in the purldb to further determine if there are license detection issues and/or TODO items

**Comment by tdruez** [comment]
@pombredanne Project outputs are now available as a new REST API project action.

**Comment by tdruez** [comment]
@pombredanne Outputs panel added in https://github.com/nexB/scancode.io/pull/928
