### ISSUE TITLE
pyz are not extracted correctly for a basic scan

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#68]
When running a basic scan a .pyz file (which is a zip) is not extracted OK  and therefore not scanned in details
See https://github.com/pypa/get-virtualenv/raw/20.2.2/public/virtualenv.pyz

**Comment by tdruez** [comment]
@pombredanne can you provide more details about the context of "basic scan"?
Are you running a specific Pipeline, the scanner app, calling a specific scan function through Python?

**Comment by tdruez** [comment]
From https://github.com/nexB/scancode.io/issues/67#issuecomment-816590644

> All the default pipelines are now using the extractcode API for the archives extraction.
Thus, all the extensions supported by extractcode are now supported in ScanCode.io, including .pyz.

@pombredanne please try again and let me know if your `.pyz` is not properly extracted. That would be a bug.
