### ISSUE TITLE
Design and create UI to review devel_to_deploy package relationships

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#683]
The volume of relations created with a devel to deploy pipline can be large. We therefore need an efficient UI to focus on possible issues and inconsistencies.

Some directions could include:
- have filters and sorting for each of the displayed columns
- have a pagination to avoid displaying to may rows at once
- have a way to download these results to a spreadsheet
- have a way to hyperlink to the actual source files

Also we are looking at files for now, but eventually id all the files of a package are mapped, it would be interesting and help remove clutter and volume to display packages instead

**Comment by tdruez** [comment]
https://github.com/nexB/scancode.io/pull/666
