### ISSUE TITLE
Add Attribution generation pipeline step

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#684]
I would like to have a step at the end of a pipeline that can generate an attribution documentation using AboutCode toolkit.

The basis could be the packages and/or files found on the To side and/or the From or both. 
I would like to have a link provided in the UI to download the generated attribution and I would like this to be also available later on as an API operation.

**Comment by tdruez** [comment]
@pombredanne 
> pipeline that can generate an attribution documentation using AboutCode toolkit

Can you point me to the documentation (or code) on generating attribution using the Python API?

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/712
