### ISSUE TITLE
Improve the UI for downloading results of Project Packages, Relations, and Resources to XLSX 

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode.io#687]
The download options for a ScanCode.io Project are clearly presented with friendly green buttons, but the download options for the tabular data presented in Project Packages, Relations, and Resources are kind of obscure and not obvious to the user.  It would be a very nice improvement to use the green XLSX button (or similar) in those cases as well. 

<img width="612" alt="project-download-UI" src="https://user-images.githubusercontent.com/4991620/233141019-e9dc4d72-5d43-4918-a5ef-7a88d41930c5.png">

<img width="403" alt="project-packages-download-UI" src="https://user-images.githubusercontent.com/4991620/233141062-a10fc71f-9f74-416a-ab30-dfbe6327ce60.png">

**Comment by tdruez** [comment]
The XLSX export is now presented with friendly green button:
![export](https://user-images.githubusercontent.com/489057/235107163-b922a936-218e-4a0e-a21f-889d7e4d9243.jpg)
