### ISSUE TITLE
In the CodebaseResource admin, I find that I cannot navigate directories consistently at all times

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#69]
Note that this is a simple placeholder  for now. I will add more details later

- Search issue: If I do a search, clicking to select a path segment may not work

- Directories with no direct files but only directories:  if a directory has no files (but only directories) clicking to select a path segment may not work

**Comment by tdruez** [comment]
The admin app was removed in https://github.com/nexB/scancode.io/issues/645
