### ISSUE TITLE
Scans take too long to run

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#70]
When scanning a docker image, it make take forever to complete run.
The key reason is that when we actually scan files, each resource is scanned sequentially in a single process.
This was initially done this way because of some incompatibility between the various libraries we use for tasking and scancode-toolkit joint use of multiprocessing and multithreading.  
We should instead actively use multiprocessing and multithreading to reach scan speeds similar to an equivalent command line run.

For reference, it took about 5 days :| to complete a scan for a mid-size Docker image of about 500MB. In contrast, running a `-clipeu` scan on `-n5` processes from the CLI on the same code completed in a couple hours on the same machine. All that on a fairly underpowered standard laptop with 5 year old specs.

We can do better: we should be able to complete such a scan in a couple hours in scancode.io too.

**Comment by tdruez** [comment]
I've encounter 2 major performance issues that require a closer look:

### 1. License expression normalization:

Running some profiling on the Docker pipeline on a mongo image (from https://github.com/nexB/scancode.io/issues/73)
```
from scanpipe.models import Run
run = Run.objects.get(project__name="PROJECT_NAME")
run.profile(print_results=True)
```

<img width="542" alt="Screenshot 2021-02-16 at 11 40 14 AM" src="https://user-images.githubusercontent.com/489057/108032332-c121ad80-704b-11eb-8597-8bc8e113cb00.png">

Almost 90% of the time is spent in the `collect_and_create_system_packages` step.

Going further and profiling that step execution with the `@profile` step decorator:
<img width="1161" alt="Screenshot 2021-02-16 at 11 42 25 AM" src="https://user-images.githubusercontent.com/489057/108032532-11990b00-704c-11eb-914b-deccaa1df88b.png">

Most of the time is spent in the normalization of license expressions.
We should focus on optimizing this side of the code to get the best performance boost.

### 2. Docker image extraction

We've noticed a huge difference of execution time between the docker and rootfs pipeline.
The issue related to extraction function:
- RootFS: `extractcode.extract.extract_file`
- Docker: `container_inspector.utils.extract_tar (tarfile.extractall)`

For example:
```
$ tar -ztvf layer.tar
drwxr-xr-x  0 0      0           0 May 13  2020 bin/
-rwxr-xr-x  0 0      0     1132800 May 13  2020 bin/[
-rwxr-xr-x  0 0      0           0 May 13  2020 bin/[[ link to bin/[
-rwxr-xr-x  0 0      0           0 May 13  2020 bin/acpid link to bin/[
-rwxr-xr-x  0 0      0           0 May 13  2020 bin/add-shell link to bin/[
...
```

Extracting with `extractcode.extract.extract_file`:
```
-rw-r--r--  1   1132800 May 13  2020 [
-rw-r--r--  1         0 May 13  2020 [[
-rw-r--r--  1         0 May 13  2020 acpid
-rw-r--r--  1         0 May 13  2020 add-shell
...
```

Extracting with `container_inspector.utils.extract_tar`:
```
-rwx------  398  1132800 May 13  2020 [
-rwx------  398  1132800 May 13  2020 [[
-rwx------  398  1132800 May 13  2020 acpid
-rwx------  398  1132800 May 13  2020 add-shell
```

As a result, we end up scanning over and over the same content.
We should review this extraction approach and also think about some scanning result cache (at the project level) in case a file exists at several location within the project.

**Comment by tdruez** [comment]
- Multiprocessing is now enabled by default on the scanning function(package, license, copyright) and is taking advantage of all the available CPUs of the machine running ScanCode.io
- Database queries have been optimized, using `update()` when possible in place of `save()`. Also, `get_or_create()` were removed when possible to cut in half the number or queries required for the CodebaseResource creation.
- Multiple code changes for performance were made on the toolkit side as well.

The Pipeline execution is 3 to 5 times faster on average in latest version 21.4.5 including all the changes.

**Comment by tdruez** [comment]
Some project error started to appear with the addition of multiprocessing, with the error message:`no results to fetch`

```
File "/opt/scancodeio/scanpipe/models.py", line 532, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1417, in execute_sql
    return [self.connection.ops.fetch_returned_insert_columns(cursor, self.returning_params)]
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/operations.py", line 185, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
```

For some reason after an insert, the inserted object cannot be fetched.

See also https://code.djangoproject.com/ticket/20161

**Comment by tdruez** [comment]
See https://github.com/nexB/scancode.io/issues/150 for progress on the `no results to fetch` issue.
