### ISSUE TITLE
When I run a devel to deploy pipeline, treat META-INF specially

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#707]
When I run a devel to deploy pipeline, I would like to treat META-INF specially:
- skip it during the mapping (already done)
- but likely scan it afterwards for details as it contains license and package metadata

The approach to scanning these needs a special procedure as this is typically the "key files", top-level files for a JAR.
@JonoYang ping

**Comment by pombredanne** [comment]
There are cases where we have code in the META-INF such as JavaScript.
While there may need to be skipped in the early parts of a pipeline, "META-INF" is not overall a resource status

**Comment by tdruez** [comment]
> skip it during the mapping (already done)

We are now reverting this  behavior as we do not want to ignore META-INF early in the d2d processes.
We want to favor instead the new `ignored_patterns` setting to provide specific resources to be ignored.
