### ISSUE TITLE
When I create a project to scan with the devel and deploy I would like to avoid renaming inputs

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#708]
When I create a project to scan with the devel and deploy I would like to avoid renaming inputs.
Instead I would like to either:
Upload inputs or add URLs and state which is To and which is From.
In particular URLs cannot be easily prefixed by hand and need today to be downloaded, renamed and uploaded.

**Comment by tdruez** [comment]
For input URLs, we could add support for tagging the inputs using a sort of "prefix":
```
from:https://url1
to:https://url2
```

Now for the uploaded inputs, there's no easy way to flag things using a form `input` type (drag and drop).
We could have multiple `input` fields but I do not like this solution as it only makes sense in the context of this specific pipeline for now.
We could instead have a way to "tag" inputs post upload from the "Inputs" box section in the project details view.

**Comment by pombredanne** [comment]
re: https://github.com/nexB/scancode.io/issues/708#issuecomment-1530913139

This could work OK for a start, and we may evolve this with something similar for uploaded files later.

**Comment by pombredanne** [comment]
And we would need to be able to tag URLs we upload also in the API and command line. Until the alternative would be:
1. fetch the files by hand (say with wget)
2. rename accordingly with a `to-` or `from-` prefix
3. create a project and upload the renamed files

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/1069/
See https://scancodeio.readthedocs.io/en/latest/faq.html#how-to-tag-input-files for the various uses of the tag features.
