### ISSUE TITLE
When I view a file content in the Web UI, I would like to search its text

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#724]
When I view a file content in the Web UI, I would like to search its text, but if I press Ctrl-F there is no search box and I cannot seem to be able to search for the file content

**Comment by tdruez** [comment]
@pombredanne  Search plugging for ace.js added in file viewer, including regex search, case-sensitive search, and whole word search.
Also, you can now toggle the full-screen mode for the viewer.
The UI was also updated to be more compact.

![Screenshot 2023-05-11 at 12 03 09](https://github.com/nexB/scancode.io/assets/489057/b4587757-0642-4a92-bd29-7b31fe57fcd7)
