### ISSUE TITLE
load_inventory pipeline does recognize detected license_expressions from SCTK scan

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#731]
When I run the load_inventory pipeline for an SCTK scan SCIO v32.1.0 does not display the detected license_expression data for packages or resources. 
The scans were run with SCTK v32.0.0.rc4 and I have confirmed that there is license data by using SCWB and by inspecting the JSON file.
I do not see any reference to this issue in the release notes for SCIO v32.2.0.

**Comment by tdruez** [comment]
SCTK v32.0.0.rc4 input requires upgrading to the latest SCIO v33.0.0-dev.
