### ISSUE TITLE
Import an XLSX spreadsheet with the "load_inventory" pipelines

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#735]
The input format of this XLSX should be exactly the same as the SCIO XLSX output format with these additional considerations:

- the tab names that are unknown from SCIO should be ignored
- the column names that are unknown from SCIO in a tab should be ignored
- we only support the current version of SCIO XLSX output

**Comment by tdruez** [comment]
There will be some data loss due to the XLSX format limitation.
Those should be minor, but the ScanCode.io JSON output is preferred to load project data without any loss.

From https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/output.py#L378

```
Convert the value to a string and perform these adaptations:
    - Keep only unique values in lists, preserving ordering.
    - Truncate the "description" field to the first five lines.
    - Truncate any field too long to fit in an XLSX cell and report error.
    - Create a combined license expression for expressions
    - Normalize line endings
    - Truncate the value to a ``maximum_length`` supported by XLSX.
   ```
