### ISSUE TITLE
Clicking on codebase folders does not open the folder

### ISSUE THREAD

**Issue by TG1999** [nexB/scancode.io#744]
![Screenshot from 2023-05-23 10-42-06](https://github.com/nexB/scancode.io/assets/34160672/04bf5f8e-4e99-461f-bd7b-28989f94675e)

**Comment by swastkk** [comment]
I just went through and found that these links were not clickable because no `href` attribute was provided in the link `a` tag.
Here is the code-
```
<nav class="panel is-info">
  <p class="panel-heading py-2 is-size-6">
    Codebase
  </p>
  {% for path in paths %}
    <a class="panel-block">
      <span class="panel-icon">
        <i class="{% if path.is_dir %}fas fa-folder{% else %}far fa-file{% endif %}"></i>
      </span>
      {{ path.name }}
    </a>
  {% endfor %}
</nav>

```
I want to know if there is any logic already written for showing the `codebase` in UI or not?

**Comment by tdruez** [comment]
This browsing feature was not implemented yet. It is now available following the merge of https://github.com/nexB/scancode.io/pull/754
