### ISSUE TITLE
Include project name in project URL and not only UUID

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#745]
A project URL looks like this http://127.0.0.1:8080/project/eb1e3de0-073d-4be7-8f5e-e99165ddea1f/
It would be great to include the project name in the and not only UUID, possibly with a fragment such as http://127.0.0.1:8080/project/eb1e3de0-073d-4be7-8f5e-e99165ddea1f#project%20Foo%20Bar  so something similar that provides some idea of the project id.

**Comment by tdruez** [comment]
Using URL anchor for this purpose is generally a bad idea as it conflicts with the page's internal navigation (and tab system for example).
The proper way would be to use the slug system for project-related URLs.

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/commit/a507af1a7fa3b2e93396ebaf071aea367153f70f
URLs are now using the Project ``slug`` in place of the ``UUID``.
