### ISSUE TITLE
JSON results created from a project does not contain all scancode fields

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#75]
I created a pipeline that takes the JSON representation of the codebase and sends it to a server. I first create a project on my local instance of scanpipe using the `scan_codebase` pipeline, then send the JSON of that codebase to my server.

I see that the `scan_codebase` uses these scancode options:
```
        "--copyright",
        "--email",
        "--info",
        "--license",
        "--license-text",
        "--package",
        "--url",
```
I would expect to be able to have the Resource fields added by these options when I get a JSON of my codebase. This is causing an issue where the task on the server fails because the Resources from the scan that is sent from my instance of scanpipe does not have the `is_archive` field. I think it would be useful to include fields like `is_archive`, `is_binary`, `is_text`, etc. in the scanpipe JSON results.

**Comment by tdruez** [comment]
Moving to the 2021-05 milestone for discussion.

**Comment by tdruez** [comment]
@JonoYang is there a real need for those values on the consumer side, or those are just expected but not used?

**Comment by JonoYang** [comment]
@tdruez In my webapp, I import the JSON results into a VirtualCodebase. One of the functions only processes archives found in the codebase, where I use the `is_archive` field to determine whether or not a file is an archive. I like the idea of having these fields available, even if they are not used all the time. Having these fields on the `CodebaseResource` model would be convenient when I want to filter on `CodebaseResources` that are archives.
