### ISSUE TITLE
UI to go back on a project page is a bit subtle

### ISSUE THREAD

**Issue by TG1999** [nexB/scancode.io#761]
![Screenshot from 2023-06-03 13-39-35](https://github.com/nexB/scancode.io/assets/34160672/5fb36d70-783b-49f9-b751-653e8e77fe66)
It's very difficult to identify how we can go back to `registry.npmjs.org/which/%2D/which%2D2.0.2.tgz` project when opened particular resource, the UI should be bold so it's intuitive to click on this `registry.npmjs.org/which/%2D/which%2D2.0.2.tgz`

**Comment by tdruez** [comment]
@TG1999 What UI would you suggest to improve the header?

**Comment by tdruez** [comment]
Breadcrumb updated in https://github.com/nexB/scancode.io/commit/99130f6a878e17d41e92398a93688dadb7b022a4
