### ISSUE TITLE
Add Create Another New Project button to Create a Project page

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#763]
When you need to create and run many projects, it would be helpful to be able to Create Another New Project button on the Create a Project page. The current workflow is that after you create a project you need to go the main Projects page and click New Project.
If you have a queue of scan projects it would be nice to have an option on the Create a Project screen to effectively stay on this page. So in addition to the Create button we would add one called "Create and New" which would keep you on the Create a Project page to add another new project.
This is similar to options in many apps for: "Save& Close" or "Save & New".
Or something like the "New Issue" button on the top right for GH Issue entry :-)
Or add New Project to the top-level menu?

**Comment by tdruez** [comment]
Added a "New Project" button to the Project details view in https://github.com/nexB/scancode.io/commit/4007681ea659f66611940bdaa18e259deaf6bb87
