### ISSUE TITLE
Change the defaults of running a single project at a time

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#767]
There are several cases when running a single project at a time is not an optimal solution:
- there are long running single threaded steps that are I/O intensive such as extracting and collecting resources
- processing large system package databases in a docker/rootfs is also single threaded

These make running scans sequentially slower.
We must instead enable multiple projects to run in parallel by default. We could be smart to deal with knowing when a step is multiprocessing or not and adjust allocation of CPU cores accordingly, but that's a refinement.

**Comment by tdruez** [comment]
There are multiple ways to handle this:

### 1. Docker compose

Using the `--scale` option with `docker compose up` such as:

```
sudo docker compose up --detach --scale worker=2
```

https://docs.docker.com/engine/reference/commandline/compose_up/#options 

> `--scale`: Scale SERVICE to NUM instances. Overrides the scale setting in the Compose file if present.

Note, you can easily add extra workers by running the command while the services are already running. For example. to add 2 extra workers to the 2 currently running ones:

```
sudo docker compose up --detach --scale worker=4
```

### 2. Supervisor

https://github.com/RandyDeng/rq-docker-supervisor

### 3. RQ Worker Pool (beta)

WorkerPool allows you to run multiple workers in a single CLI command.

https://python-rq.org/docs/workers/#worker-pool

> `WorkerPool` is still in beta, use at your own risk!

**Comment by tdruez** [comment]
Added in the documentation.
