### ISSUE TITLE
Add a group entity for Projects

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#769]
The current usage for the Project is a potential misnomer because it is more a Scan than a Project. We need a way to easily group scan projects without relying on error-prone naming conventions in the project name. From a "human" perspective it would best to redefine Project as a new entity (or label) that that you can apply to multiple scan projects. Adding a simple label/tag feature would probably address the most immediate problem of grouping scans, but we may want a new data entity for longer-term use. The most likely use cases are to group scans for a Product or for an SCA project.

**Comment by DennisClark** [comment]
`Adding a simple label/tag feature would probably address the most immediate problem of grouping scans`
agreed

**Comment by DennisClark** [comment]
I would prefer the label/tag approach rather than creating a new entity

**Comment by tdruez** [comment]
The Project labels were implemented in https://github.com/nexB/scancode.io/commit/2e27fa5fc82b34dd2b3de46101531fc155f9c049
Those can be used to group and filter projects.

![Screenshot 2023-08-29 at 10 03 21](https://github.com/nexB/scancode.io/assets/489057/fe883098-f091-4d76-a66f-a43d3d5959f2)
