### ISSUE TITLE
Add archive_location to the LAYERS worksheet of XLSX output

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#773]
We need to add the archive_location data to the LAYERS worksheet of the standard XLSX output from SCIO for a Docker image.
The use case is when you need to investigate the files inside a Docker image you need the archive_location to identify which folder to open inside the tarball. Without this you need the JSON output to find the archive_location by searching for the extracted_location. 
It should be fine to use a six character abbreviation as we do for image and layer ids.

**Comment by tdruez** [comment]
Added in https://github.com/nexB/scancode.io/commit/a2be1beb54263f3f5fb6778c97b3e3ba7efb55e7
