### ISSUE TITLE
Make the 'Project data' window expandable

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode.io#774]
It would be handy to be able to stretch the lower right-hand corner of the `Project data` window to increase the window's height and display a larger chunk of the data at one go.  Adding a comment in a GH issue (like the one I'm typing in atm) is an example of the suggestion.

**Comment by tdruez** [comment]
Dup of https://github.com/nexB/scancode.io/issues/210

Implemented in https://github.com/nexB/scancode.io/pull/777
Make sure to refresh your browser cache if you do not see the changes after upgrading SCIO to the latest version, as it is a JS-based solution.
