### ISSUE TITLE
Path copied from a resource detail view should NOT contain spaces

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#783]
When I tried to copy/paste the highlighted path below:

![Screenshot_2023-06-21 ScanCode io pkg github weidai11 CRYPTOPP_5_4 - 3way cpp](https://github.com/nexB/scancode.io/assets/675997/39dea42b-ebfd-4eac-8ba7-ad2c5d075a69)

... I get spaces around slashes and the path is not usable.
` cryptopp-CRYPTOPP_5_4 / 3way.cpp `
I would like to select and copy the path and get no added spaces before and insde so th path is valid when I paste it.

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/commit/99130f6a878e17d41e92398a93688dadb7b022a4
