### ISSUE TITLE
License Policy and Compliance Alert not working with scan_codebase but working with scan_package

### ISSUE THREAD

**Issue by prakyathr** [nexB/scancode.io#784]
I am currently testing the functionality of Compliance Alert as it is one of the main requirements for OSS license scanning automation in my Organization. So, I was using the examples provided in the [documentation](https://scancodeio.readthedocs.io/en/latest/tutorial_license_policies.html) using `policies.yml` and `scan_codebase` pipeline with `cuckoo-filter` package to test it out. However, I was never able to get the alerts configured in the policies.yml file.

```shell
license_policies:
  - license_key: mit
    label: Approved License
    compliance_alert: ""
  - license_key: mpl-2.0
    label: Restricted License
    compliance_alert: warning
  - license_key: gpl-3.0
    label: Prohibited License
    compliance_alert: error
  - license_key: cc-by-nc-sa-4.0
    label: Prohibited License
    compliance_alert: error
``` 

![image](https://github.com/nexB/scancode.io/assets/109953234/d63aceed-3c7e-4f6d-bb9b-d964565868a6)
![image](https://github.com/nexB/scancode.io/assets/109953234/a7886cae-5f2c-496b-866e-45ae5faed582)

However, when I use `scan_package` pipeline for the same package, the License policy and Compliance alert is working as expected. 
![image](https://github.com/nexB/scancode.io/assets/109953234/bb305f86-24d4-4d16-9d7d-380b7ba23543)

This is an expected output?

According to the documentation, license policy should be working for `scan_codebase`. 

ScanCode.io: 32.3.0
ScanCode-toolkit: 32.0.4

**Comment by tdruez** [comment]
@prakyathr Thanks for reporting the issue.

The fix https://github.com/nexB/scancode.io/pull/786 has been merged in the `main` branch. 
Could you try again with the latest changes and confirm everything is now working as expected.
Thanks!

**Comment by prakyathr** [comment]
@tdruez It is working now. Thanks for the fix..
![image](https://github.com/nexB/scancode.io/assets/109953234/df9a8fa0-6edc-482c-8584-abfb320c97f5)
