### ISSUE TITLE
Use more informative suffix for CycloneDX SBOM report

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#790]
Currently, the generated cyclonedx SBOM file ends up in `.bom.json`
It should instead be more explicit suffixed such as `.cyclonedx.json`

**Comment by AyanSinhaMahapatra** [comment]
See https://github.com/nexB/scancode.io/issues/785 and https://github.com/nexB/scancode.io/commit/55e738ef4fb2f38f5554ff9929b090bd46daafc0 btw, I thought this was supposed to be `*.cdx.json` as specified in the cyclonedx website.

**Comment by mjherzog** [comment]
Ayan is correct - the format is cdx.json.

**Comment by AyanSinhaMahapatra** [comment]
@tdruez has already added a fix on this then, referenced it above. We can close this IMHO, Thanks!
