### ISSUE TITLE
[Documentation] : Improve Find_Vulnerabilties pipeline docs.

### ISSUE THREAD

**Issue by swastkk** [nexB/scancode.io#794]
I have setup my `scancode.io` project for more than 5 times, but every time I want to use this pipeline `find_vulnerabilties` , i had to face issues with the integration of VulnerableCode with ScanCode.
This explanation is not self-sufficient, there is a need of improvement since after doing the things mentioned there, I was unable to use that pipeline.
Example if I want to apply the changes that are mentioned [here](https://scancodeio.readthedocs.io/en/latest/tutorial_vulnerablecode_integration.html)
got this thing only.
```bash
(scancode.io) [swastik@arch scancode.io]$ make run
bin/python manage.py runserver 8001 --insecure
Invalid line: VULNERABLECODE_URL = "https://public.vulnerablecode.io/"
Invalid line: VULNERABLECODE_API_KEY = "Token <-------------apikey-------------------->"
INFO Synchronizing QUEUED and RUNNING Run with their related Jobs...
INFO No Run to synchronize.
Invalid line: VULNERABLECODE_URL = "https://public.vulnerablecode.io/"
Invalid line: VULNERABLECODE_API_KEY = "Token <-------------apikey-------------------->"
INFO Synchronizing QUEUED and RUNNING Run with their related Jobs...
INFO No Run to synchronize.
INFO Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 30, 2023 - 07:35:42 PM
Django version 4.2.2, using settings 'scancodeio.settings'
Starting development server at http://127.0.0.1:8001/
Quit the server with CONTROL-C.
```

**Comment by tdruez** [comment]
@swastkk try to remove the spaces around the `=` sign such as:
```
VULNERABLECODE_URL="https://public.vulnerablecode.io/"
VULNERABLECODE_API_KEY="<VulnerableCode API key>"
```
Also, do not include the "Token" in the API_KEY variable.

Let me know if that solve your issue and I'll update the documentation accordingly.

**Comment by swastkk** [comment]
> @swastkk try to remove the spaces around the `=` sign such as:
> 
> ```
> VULNERABLECODE_URL="https://public.vulnerablecode.io/"
> VULNERABLECODE_API_KEY="<VulnerableCode API key>"
> ```
> 
> Also, do not include the "Token" in the API_KEY variable.
> 
> Let me know if that solve your issue and I'll update the documentation accordingly.

Yes it worked, thanks a lot!, should I update the documentation or you will?

**Comment by tdruez** [comment]
I will update the docs.

**Comment by tdruez** [comment]
Updated in https://github.com/nexB/scancode.io/commit/f4483a6b647a6eeb2980a35dd5400886d05a8334

**Comment by swastkk** [comment]
> Updated in [f4483a6](https://github.com/nexB/scancode.io/commit/f4483a6b647a6eeb2980a35dd5400886d05a8334)

Minor nit https://github.com/nexB/scancode.io/commit/f4483a6b647a6eeb2980a35dd5400886d05a8334#r120484764
