### ISSUE TITLE
Implement alpha sort in Codebase View

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode.io#795]
When you use the Codebase View for a project using the scan_package or scan_codebase pipeline, the Codebase values are not sorted in any discernible order. They should be sorted in alphanumeric order as they would be sorted in any base filesystem. This makes is extremely difficult to review Codebase content.

This issue is for SCIO 32.3.0

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/commit/94b835cc098bd9ebf53d816eaeb82db35e568c2c
