### ISSUE TITLE
Update project inputs

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode.io#813]
For larger projects, it will be really convenient to have these features:
1. Possible to have multiple to/from archives as inputs and not one each
2. Ability to download the inputs
3. Ability to delete specific inputs (if no pipeline has been executed, otherwise they are frozen?)

**Comment by tdruez** [comment]
@AyanSinhaMahapatra Thanks for the suggestions. Those 3 features are now available in `main`.

**Comment by AyanSinhaMahapatra** [comment]
Thanks for the quick update @tdruez, this would really help in the large d2d projects.
These were suggested by @pombredanne originally though :smile:
