### ISSUE TITLE
System package scan for fedora distro does not work

### ISSUE THREAD

**Issue by philcali** [nexB/scancode.io#831]
I've tried to run a docker and rootfs scan of a fedora base and it does not appear to detect installed rpms.

To replicate, simply spin up a scancode.io portal and start a scan of fedora server with docker://fedora:38. It detects pypi packes but none of the installed rpms.

**Comment by pombredanne** [comment]
@philcali Thanks for the report... that's a great catch!

I was able to reproduce this and this is a bug indeed. At the lowest level, ScanCode toolkit can parse the rpmdb.sqlite format of Fedora 38 correctly... BUT there is a but there is a (stupid copy/paste) bug in https://github.com/nexB/scancode-toolkit/blob/200fb10eb22218c36f68e37f2f9dc86342adaa35/src/packagedcode/rpm.py#L235 where the "rpmdb.sqlite" is expected to have the same type as the older Berkeley DB format... and therefore no scan is taking place there for the system packages in this case.

**Comment by philcali** [comment]
Yep, I wound yup tracing the issue to the same spot yesterday, and have confirmed a fix for it. I can post a cr soon if you haven't already resolved it.

**Comment by philcali** [comment]
Here is the PR: https://github.com/nexB/scancode-toolkit/pull/3479

**Comment by tdruez** [comment]
@philcali PR merged, thanks for your contribution 🚀
