### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by vchhasatia** [nexB/scancode.io#839]
Hello,

I am trying to run scancode.io. I was following steps listed on https://scancodeio.readthedocs.io/en/latest/tutorial_web_ui_analyze_docker_image.html
When I reach Finally, click the “Create” button --> after that I get following error:

Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.

I was wondering if there was a way to check if my installation was working properly or there is some other error. I am using v32.3.0 (v32.0.5rc3) on Amazon Linux 2.

**Comment by tdruez** [comment]
Hi @vchhasatia, can you confirm that you have properly set up the `ALLOWED_HOSTS` and `CSRF_TRUSTED_ORIGINS`  in your .env file, according to your server domain?

From https://scancodeio.readthedocs.io/en/latest/installation.html#run-the-app

> To access a dockerized ScanCode.io app from a remote location, the ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS settings need to be provided in your .env file for example:
> ```
> ALLOWED_HOSTS=.your-domain.com,localhost,127.0.0.1
> CSRF_TRUSTED_ORIGINS=https://*.your-domain.com,http://127.0.0.1:8001
> ```

See also https://docs.djangoproject.com/en/dev/ref/settings/#allowed-hosts and https://docs.djangoproject.com/en/dev/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS

**Comment by tdruez** [comment]
@vchhasatia I'm assuming the proper settings did fix your issue. Please re-open if that's not the case.
