### ISSUE TITLE
If I did not click on "Run the selected pipeline"  when I create a project, how do I start it afterwards in the UI?

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#84]
This is not available from the new UI yet, only from the API.
1. It would be great to allow to launch the pipelines afters
2. by default, the "Run the selected pipeline" checkbox should be checked and an opt-out

**Comment by tdruez** [comment]
- Added "Run Pipeline" button in the Pipeline modal of the Project details view:
<img width="270" alt="Screenshot 2021-02-12 at 8 38 57 AM" src="https://user-images.githubusercontent.com/489057/107731621-e17dff00-6d0f-11eb-9de7-ac4ba8b56b52.png">

- The "Run the selected pipeline" is now selected by default
- The "Add pipeline" feature is now enabled on the Project details view
