### ISSUE TITLE
Cannot find PURL in Package search

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#859]
I have a codebase where the `pkg:maven/com.fasterxml.jackson.core/jackson-core@2.14.0` exists (a simple scan_package using https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.0/jackson-core-2.14.0.jar as an input)
I go to the Packagdes details and I can see the `pkg:maven/com.fasterxml.jackson.core/jackson-core@2.14.0` package.
I copy the PURL `pkg:maven/com.fasterxml.jackson.core/jackson-core@2.14.0` and paste this in the search box, press enter and there is nothing found

**Comment by tdruez** [comment]
The package search was improved to support full PURLs or any segment of a PURL.

For your example, you can now use:
- `pkg:maven/com.fasterxml.jackson.core/jackson-core@2.14.0`
- `maven`
- `com.fasterxml.jackson.core`
- `jackson-core`
- `2.14.0`
