### ISSUE TITLE
Provide source code location (e.g. URL) for detected packages

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#87]
This is more of a scancode-toolkit thing (and possibly a future PackageDB tasks) but this has been reported as a desired feature:
- when a package is detected, I would like to know what is the URL to download the source code
- this would presumably then be used to fetch and scan the corresponding sources.

scancode-toolkit makes a best attempt to infer and craft a download URL for a package and a Package URL for the sources. It does not provide a download URL for the sources. This would be a great addition to support this feature (or this is a lookup/match things with the future PackageDB)

**Comment by tdruez** [comment]
The following URLs are currently available on the discovered packages:

- homepage_url
- download_url
- bug_tracking_url
- code_view_url
- vcs_url
- api_data_url
- repository_homepage_url
- repository_download_url

I'm guessing that the source-related package and scan will be available through the PurlDB package set feature.
