### ISSUE TITLE
When I search for resource path, I want to only list paths that ends with my search

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#871]
When I search for resource path, I want to only list paths that ends with my search.
Today, this is not possible, and if I search for foo.jar, I may get all the foo.jar-extract and more
It would be nice to have a way to force and "ends with" only search as an option.

**Comment by tdruez** [comment]
@pombredanne a new advanced search was implemented. You can refer to the search syntax in the documentation at https://scancodeio.readthedocs.io/en/latest/user-interface.html#search-syntax or from the inline help next to the search box.

> It would be nice to have a way to force and "ends with" only search as an option.

You can use the following search syntax: `name:foo.jar`
