### ISSUE TITLE
Display pipeline-specific extra data in a project.

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#88]
For instance, in a docker pipeline there is interesting information about the layers, OS, distro, etc. We should find a way to surface these in the UI

**Comment by pombredanne** [comment]
Here are two design ideas:
1. a Pipeline subclass can contribute some UI attribute (e.g.something that would handle some form/view) that ends up included in the project UI. The specific methods and attributes contributed by a Pipeline are called/used and included at a well defined location in the project UI (typically before the stats/wheel graphics)
2. a Pipeline can write a specific HTML snippet in a conventional project location. This is being included in the project page.

1. gives maximal flexbility AND allows to have whatever data is displayed queried live from the DB
2. is simpler and may not provide much. It would also be out of sync when the DB evolves, short of rerunning the pipeline


IMHO 1. is a better design. It could be its own plugin entry point too.

**Comment by tdruez** [comment]
I don't like the idea of having UI related logic on the Pipeline classes.
I would suggest a new "template" attribute, that will be used in place of the default one, when provided, to generate that section in the HTML view.
Similar to the rendering of a Django view: template + context, where the context here is the Project.extra_data.
