### ISSUE TITLE
When loading inputs from a scancode JSON scan, always create CodebaseResource.name even if missing

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#890]
When loading inputs from a  ScanCode toolkit JSON scan, we should always create CodebaseResource.name even if missing. A ScanCode toolkit files section can contain only a path and no name. We should craft a name in these cases.

**Comment by pombredanne** [comment]
Same with extension

**Comment by tdruez** [comment]
> A ScanCode toolkit files section can contain only a path and no name. We should craft a name in these cases.

@pombredanne could you provide an example of such input?

**Comment by tdruez** [comment]
@pombredanne thanks for the input.

Although when I use it with the `load_inventory` pipeline, the `name` and `extension` values are properly set for created codebase resources:
![Screenshot 2023-08-23 at 09 21 51](https://github.com/nexB/scancode.io/assets/489057/30828746-f522-4977-badc-f43b337b677a)

This seems to be properly handled in the `VirtualCodebase` and `ScannedResource` objects.

Could you provide more information about the context where you encounter this issue?

**Comment by tdruez** [comment]
@pombredanne ping ^

**Comment by pombredanne** [comment]
Closing as I cannot reproduce for now!
