### ISSUE TITLE
Scancode CLI fails to invoke

### ISSUE THREAD

**Issue by philcali** [nexB/scancode.io#895]
**Describe the bug**

When following the CLI instructions on the README: https://scancodeio.readthedocs.io/en/latest/tutorial_cli_analyze_docker_image.html, Invoking the example `scnapipe` command fails on the latest taq `v32.5.2` with the following reason:

```
Traceback (most recent call last):
  File "/opt/scancodeio/venv/bin/scanpipe", line 5, in <module>
    from scancodeio import command_line
ModuleNotFoundError: No module named 'scancodeio'
```

This appears to be a real issue with the way the scancode library is installed in Docker. When I inspect a running `web` container, I do not see `scancodeio` module installed in the virtual env:

```
app@8556d43e4009:~$ ls -1 /opt/scancodeio/venv/lib/python3.11/site-packages/ | grep scancode
__editable__.scancodeio-32.5.2.pth
__editable___scancodeio_32_5_2_finder.py
scancode
scancode_config.py
scancode_toolkit-32.0.6.dist-info
scancodeio-32.5.2.dist-info
```

I'm not familiar enough with `pip` or `python` to know a quick remedy.

**System configuration**
- Which version of ScanCode.io are you running? `v32.5.2`
- Are you running the app using Docker? Y
- On which OS? `5.15.0-78-generic #85~20.04.1-Ubuntu`
- What inputs are you using? 
```
alias scanpipe="docker compose -f ${PWD}/docker-compose.yml run --volume ~/codedrop/:/codedrop:ro web scanpipe"
scanpipe create-project staticbox
```
- Which pipeline are you running? NA

**To Reproduce**
1. Go to https://scancodeio.readthedocs.io/en/latest/tutorial_cli_analyze_docker_image.html#requirements
2. Follow instructions on a fresh install
3. See error

**Expected behavior**
The CLI version of scancode to be functional.

**Screenshots**

**Comment by tdruez** [comment]
Hi @philcali thanks for reporting.
This issue was addressed and should be fixed with https://github.com/nexB/scancode.io/commit/5dac9e7f69fcafedb6ed8d6f0c7b6d838040f1d9 that is part of the [v32.6.0](https://github.com/nexB/scancode.io/releases/tag/v32.6.0) release, released today.

Could you try again with this latest version and let me know if that solve your issue.

**Comment by philcali** [comment]
I have confirmed that using `v32.6.0` fixed my issue. I'll mark this one was closed.
