### ISSUE TITLE
Add missing namespace to debian packages

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#899]
Scanning docker://r-base:latest  with the docker pipeline there are a few issues:
- we still do not report a proper namespace for packages that would match VCIO
- 5,300+ files are not mapped to their related package (See https://github.com/nexB/scancode.io/issues/567 )
- 800+ files are scanned for license and have none

**Comment by mjherzog** [comment]
To be more specific, the Docker pipeline for SCIO 32.08 generates Debian purls in the format: pkg:deb/name@version.
It should be pkg:deb/debian/name@version

**Comment by AyanSinhaMahapatra** [comment]
Btw, this was fixed by the SCTK PR: which is now merged.
We have the SCTK available and more improvements to support this at https://github.com/nexB/scancode.io/pull/1096 which will close this issue.
