### ISSUE TITLE
Provide minimal Dockerfiles and Docker compose for easy test of a local installation

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#9]
This would be handy to have Dockerfiles and a docker compose way to setup the whole environment at once

**Comment by pombredanne** [comment]
See 
- https://docs.docker.com/compose/django/
- https://realpython.com/django-development-with-docker-compose-and-machine/
- https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

**Comment by pombredanne** [comment]
This needs to be tested and then merged

**Comment by tdruez** [comment]
Available and documented at https://scancodeio.readthedocs.io/en/latest/docker-image.html
