### ISSUE TITLE
Issues in purldb matching step of D2D pipeline

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#903]
There are a few issues I encountered when using the D2D pipeline:

- scancode.io timed out evaluating a large queryset at https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/__init__.py#L185
- A request timed out during the purldb matching step
- We are generating empty directory fingerprints and sending it to purldb during directory matching. This is causing us to match to unrelated packages.

**Comment by tdruez** [comment]
@JonoYang PR merged, thanks! 🚀
