### ISSUE TITLE
When a resource is for a "-extract", I want to navigate easily to the non-extracted resource details

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#918]
When a resource is for a -extract, like for an extracted JAR with a .jar-extract/ suffix I want to navigate easily to the non-extracted .jar resource details. This should work either from the resource list of from the path links diplayed at the top of the Resource details page

**Comment by pombredanne** [comment]
One way would be to have a link to the "-extract" on the "-extract" portion of the path and another link to the ".jar" on that portion of the path.

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/pull/920
