### ISSUE TITLE
Issue with CodebaseResourceQuerySet.paginated

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode.io#929]
I have found an issue with `CodebaseResourceQuerySet.paginated` when debugging an issue in the d2d pipeline at the purldb matching step, where it appears that certain JARs are not being matched. The unmatched JAR in particular is `jgroups-4.1.7.Final.jar`. I put a print statement in the nested for-loop at in `match_purldb_resources` (https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/d2d.py#L604) and I see that `jgroups-4.1.7.Final.jar` is not in any `resources_batch` yielded by `resource_iterator`. If I create a d2d project with only `jgroups-4.1.7.Final.jar`, then we are able to match the JAR against purldb. In my debug branch, I've removed the use of `CodebaseResourceQuerySet.paginated` from `match_purldb_resources` and to just iterate through the resources without batching (https://github.com/nexB/scancode.io/blob/integration-purldb-matching-js-d2d-debug/scanpipe/pipes/d2d.py#L712). I was able to send `jgroups-4.1.7.Final.jar` for matching and get a result back.

I think the issue with `CodebaseResourceQuerySet.paginated` is that it is not returning the remaining CodebaseResources that does not fit the chunk size. In the case above, we had 2300 CodebaseResources to iterate through, but the logging showed that we sent about 1800 SHA1's  to purldb. The 2300 CodebaseResources were processed in batches of 1000, where we sent off around ~850-900 SHA1s during each batch, but during the last batch, no CodebaseResources were sent for the remaining ~300.

**Comment by tdruez** [comment]
Paginator is probably not the right tool for the job.

Let's take a step back, what was the problem with using [`iterator()`](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#iterator) in the first place?

> In contrast, iterator() will read results directly, without doing any caching at the QuerySet level

I would like to get a better understanding of the issues while using `iterator()`, especially since we are using it in many other places, and see how we could use it properly instead of Pagination.

**Comment by JonoYang** [comment]
@tdruez I used the paginator originally as a way to address the comment at https://github.com/nexB/scancode.io/pull/782#discussion_r1286716702, where you suggested to use `chunked` for batch processing of CodebaseResources. `chunked` works on lists, and not querysets. I would have to evaluate the queryset into a list to use it, which can be a problem for large queries, so I decided to try out using the paginator.

**Comment by tdruez** [comment]
@JonoYang fair enough, `chunked` is not meant for queryset iteration. Why not use `.iterator()` then?

**Comment by JonoYang** [comment]
@tdruez I do use `.iterator()` in my new branch: https://github.com/nexB/scancode.io/blob/929-reimplement-purldb-batch-processing/scanpipe/pipes/d2d.py#L624 and it's working out so far.

**Comment by tdruez** [comment]
@JonoYang Can we close this one?

**Comment by JonoYang** [comment]
Closing this issue, now that we do not use `CodebaseResourceQuerySet.paginated` and have removed it.
