### ISSUE TITLE
D2D: Scaned `from` files without detected license expressions should be tagged for review

### ISSUE THREAD

**Issue by keshav-space** [nexB/scancode.io#931]
- [x] Scanned media files (gif/ jpg/ jpeg/ png/ svg/ mp4) without detected license expressions should be tagged as `ignored-media-file`
- [x] Scanned doc files like pdf without detected license expressions should be tagged as `ignored-doc-file`
~~- [ ] Scanned schema files like module-log4j.xml, service.xml, module-hbm.xml, default.xml, web.xml, routes.xml without detected license expressions should be tagged as `ignored-not-interesting`~~
- [x] Rest all other scanned from files without detected license expressions should be tagged as `requires-review`

**Comment by pombredanne** [comment]
>  Scanned schema files like module-log4j.xml, service.xml, module-hbm.xml, default.xml, web.xml, routes.xml without detected license expressions should be tagged as ignored-not-interesting

These should require review too. We want to ensure we have affirmative origin and license on these
