### ISSUE TITLE
D2D: Proper handling of dangling legal files in house-keeping step

### ISSUE THREAD

**Issue by keshav-space** [nexB/scancode.io#933]
In house-keeping step unmatched/unmapped legal files usually end up with too many package matches on purldb which needs proper handling.

Legal files with too many packages match should be scanned for license irrespective of purldb match and must be flagged for review using status `requires-review-dangling-license-file`

**Comment by tdruez** [comment]
@keshav-space is this ready to be closed?

**Comment by keshav-space** [comment]
> @keshav-space is this ready to be closed?

@tdruez Yes!
