### ISSUE TITLE
 When search in the resource lists, I sometimes want to search exactly

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#951]
When search in the resource lists, I want to search exactly or get ranked results.
For instance, if I search for a file named foo.jar I may not want to see foo.jar-extract/ and all the files in this other tree.
Or if I search for extenion:.c I am not want to get .cpp and .cxx.
I say "may", because there are times when the approximate search helps. And FWIW in these cases I would want to see the exact matches to my search come first in the list

**Comment by tdruez** [comment]
@pombredanne Have you tried the exact search? 
- `name=:foo.jar`
- `extenion=:.c`

See the search help:
![Screenshot 2023-09-29 at 19 26 17](https://github.com/nexB/scancode.io/assets/489057/0caae0f6-1b62-47e1-97e7-773f30153664)
