### ISSUE TITLE
Support input as tarball(s) and VM images in root fileystem pipelines

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#96]
To run a root_filesystem pipeline, we need to do this for now:

(thanks to @JonoYang for providing the steps! )

Start from a new project:

1. Create a project by running `scanpipe create-project myproj`
2. Once the project is created, copy the contents of your rootfs tarball to `scancode.io/var/projects/<myproj-id>/codebase`. This directory should look like a rootfs.
3. Add the rootfs pipeline to your project: `scanpipe add-pipeline --project myproj scanpipe/pipelines/root_filesystems.py`
4. Run the pipeline on your project: `scanpipe run --project myproj`

This is not a great UX.  We should support having an input as a tarball or as an image (see https://github.com/nexB/extractcode/issues/16 )

In doing so there is some minor issue to resolve which is to determine where is the root of a rootfs.
1. for now it should be the root of the image or tarball
2. we should later find the actual rootfs root automatically based on the the typical layout of an image format  OR recognizing typically rootfs layouts (e.g. a typial POSIDX fs layout with `/usr/lib`, `/bin`, `/etc`, ... etc.)

**Comment by tdruez** [comment]
Support added in https://github.com/nexB/scancode.io/commit/eb970db09801740783c9c211df92106b7fe27e93
The tarballs are now supported as inputs

**Comment by tdruez** [comment]
Tarballs are now supported by the root_filesystems pipeline.

Also, the command line can be used as follow:
```
scanpipe create-project my_project --input-file location/of/rootfs_tarball.tar --pipeline root_filesystems --execute
```
