### ISSUE TITLE
Ignore patterns should use fnmatch for translation to regex

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#960]
https://github.com/nexB/scancode.io/blob/af5a6d25f30e820f755372687f400c536105e9c4/scanpipe/models.py#L1643-L1652 may be more robust if using `fnmatch.translate`
See https://docs.python.org/3/library/fnmatch.html?highlight=fnmatch#fnmatch.translate

**Comment by tdruez** [comment]
@pombredanne The output of `fnmatch.translate` does not play nice with the Django regex lookup:

```
>>> from scanpipe.models import *
>>> CodebaseResource.objects.filter(path__regex=posix_regex_to_django_regex_lookup("example"))
<CodebaseResourceQuerySet [.........]>
```

```
>>> import fnmatch
>>> CodebaseResource.objects.filter(path__regex=fnmatch.translate("example"))

Traceback (most recent call last):
  File "/Volumes/nexB/repos/scancode.io/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/nexB/repos/scancode.io/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.InvalidRegularExpression: invalid regular expression: invalid embedded option
```

- `posix_regex_to_django_regex_lookup("example")` -> `'^example$'`
- `fnmatch.translate("example")` -> `(?s:example)\\Z`

**Comment by pombredanne** [comment]
ack, closing.... I could not find a library that does this reliably. 
See also https://stackoverflow.com/a/40914206 and https://github.com/facelessuser/wcmatch/issues/209
