### ISSUE TITLE
Cannot view resource details when scanning a single file with "scan_package"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#963]
I am creating a project with a single text file at https://raw.githubusercontent.com/dotnet/dotnet/1969cbaff9ff993fc93357f482ce8dedbc307f06/src/installer/THIRD-PARTY-NOTICES and use the "scan_package" pipeline. The resource is not visible in the resource details, only a "codebase" directory.

**Comment by tdruez** [comment]
> use the "scan_package" pipeline

`scan_package` is meant to scan a package archive. As per the documentation: "Scan a single package archive with ScanCode-toolkit."

I would recommend using the `scan_codebase` pipeline for this single file purpose.
