### ISSUE TITLE
Considering a  file with a single LF is not useful

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#969]
```
$ echo "" > c
$ sha1sum c
adc83b19e793491b1c6ea0fd8b46cd9f32e592fc  c
```
there are many files with just that single LF alright and they should not even be treated seriously in a pipeline and just reported as empty. This could be based on the size being 1 byte for a start.
Otherwise we end up sending things to be matched to the PurlDB for no good reason.
See https://github.com/nexB/purldb/issues/198

**Comment by pombredanne** [comment]
For the deploy_to_devel pipeline we should have a step to ignore empty files from matching.

**Comment by tdruez** [comment]
Instead of looking at the content, I would suggest that we ignore files of size under a few (TBD) Bytes.
