### ISSUE TITLE
Unknown distro errors should be more explicit

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#97]
We want to support and id many distros. For now if we cannot recognize one we get this:
```
Error during scanpipe/pipelines/root_filesystems.py execution:

'NoneType' object has no attribute 'to_dict'

Traceback:
  File "/home/work/scancode.io/scanpipe/pipelines/__init__.py", line 75, in execute
    step(self)
  File "/home/work/scancode.io/scanpipe/pipelines/root_filesystems.py", line 50, in collect_rootfs_information
    rootfs_data["distro"] = rfs.distro.to_dict()
```

We should instead provide at least a better error message:
1. outline the checks that were made (e.g. searching for specific files that were not found)
2. provide a link to doc and request to report a bug

This may be something to implement in https://github.com/nexB/container-inspector/blob/develop/src/container_inspector/distro.py partially

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/scancode.io/commit/eb970db09801740783c9c211df92106b7fe27e93
