### ISSUE TITLE
Add notifications/webhook capabilties

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#98]
When I create a project I may want tobe notified when the scans are complete either through email or some webhook callback.

**Comment by tdruez** [comment]
That "subscription" feature exists in the scanner module, we can re-use it on the scanpipe side.
See:
- https://github.com/nexB/scancode.io/blob/main/scanner/models.py#L386
- https://github.com/nexB/scancode.io/blob/main/scanner/models.py#L412
