### ISSUE TITLE
Cannot link back to main Resources list from the Resources list 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#981]
The breadcrumbs at the top are:

`Projects` > `[name of project]` > `Resources` 

But Resources is not a link and therefore I cannot open a new Resources page. This is also true for Packages, Relations, Dependencies, and Messages.

In each case I would like to be able to get a link back to the main list. Today the only way is to get back to the main project page first which is not convenient.

**Comment by tdruez** [comment]
@pombredanne could you provide the specific URLs/views you are referencing?

**Comment by pombredanne** [comment]
![Screenshot_2023-10-30 ScanCode io antlr-2 7 5-sources - Packages](https://github.com/nexB/scancode.io/assets/675997/8bd5adf5-9be6-4659-aa4e-e418913bd6bd)

This is the Package that's in bold here... and the same on Resources/Deps/Relation

![Screenshot_2023-10-30 ScanCode io Closure-test-d2d-v4 - Resources](https://github.com/nexB/scancode.io/assets/675997/11f71e12-e726-4084-bcba-6cee600a8859) and others 

![Screenshot_2023-10-30 ScanCode io Closure-test-d2d-v4 - Relations](https://github.com/nexB/scancode.io/assets/675997/1c2ff03c-7bcf-42a5-afb1-547cb3dda644)

![Screenshot_2023-10-30 ScanCode io workbench-deps-v1-feature-unittests - Dependencies](https://github.com/nexB/scancode.io/assets/675997/e58dbcbf-ba5f-4656-a8be-89d3a264bda6)

![Screenshot_2023-10-30 ScanCode io test-import - Messages](https://github.com/nexB/scancode.io/assets/675997/194ba3f5-2f06-46c6-9bac-702c5111c4f0)

**Comment by tdruez** [comment]
Implemented in https://github.com/nexB/scancode.io/commit/7da7813e7b9089e33e23e481a83859236f17617b
