### ISSUE TITLE
Running pipeline(s) is NOT obvious

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#997]
If I have a project with pipelines that were NOT started at creation (say from a clone), there is no obvious way to start the pipeline(s): I need to click on each and click on run.

I would like to have a simpler way to run all not started pipelines of my project

**Comment by tdruez** [comment]
> Also you cannot start the develop_2_deploy pipeline from creation of the scan either.

@silverhook could you elaborate on this? It seems that this may needs a new ticker/issue including more information about how to reproduce the problem.

**Comment by tdruez** [comment]
https://github.com/nexB/scancode.io/pull/1046

There's now a single "Run pipelines" button directly available in the Pipelines panel:
![Screenshot 2024-01-11 at 10 42 42](https://github.com/nexB/scancode.io/assets/489057/512a3bb8-cb96-4160-8e17-fcd489670c22)

**Comment by silverhook** [comment]
> > 
> 
> @silverhook could you elaborate on this? It seems that this may needs a new ticker/issue including more information about how to reproduce the problem.

Unless I am missing something (at least when I wrote that comment), a “d2d” scan needed at least two (often three) resources, but when starting the scan initially, you could only add one resource, not several.

**Comment by tdruez** [comment]
From https://scancodeio.readthedocs.io/en/latest/built-in-pipelines.html#deploy-to-develop

```
This pipeline is expecting 2 archive files with "from-" and "to-" filename
    prefixes as inputs:
    - "from-[FILENAME]" archive containing the development source code
    - "to-[FILENAME]" archive containing the deployment compiled code
 ```

I'm not sure what you mean by "you could only add one resource".

**Comment by silverhook** [comment]
> I'm not sure what you mean by "you could only add one resource".

Nevermind, it seems to either be fixed, or I was blind.

I could have sworn that the WebUI only allowed you to upload one resource, before starting the scan, any additional ones I could only add afterwards.

**Comment by tdruez** [comment]
There's no limit to the number of inputs (uploaded file or download URLs) that can be provided at the project creation, or from the "Add inputs" panel. 
The "Add inputs" is not possible after pipelines have started on a project though.
