### ISSUE TITLE
Clicking on the pipeline name freezes the page (on Firefox 112)

### ISSUE THREAD

**Issue by silverhook** [nexB/scancode.io#998]
**Describe the bug**

Lately, whenever I click on a pipeline name in a project, the page freezes and I cannot do anything – mouse cursor does not change on links, scrolling does not work, … – until I reload the page.

**System configuration**

staging instance, v32.7.0-27-g69bc11130

**To Reproduce**
1. Open a scan
2. Click on any of the pipline names
3. Try do anything

This happens to me on Firefox 112. It worked fine before and it still works in Chromium.

**Expected behavior**
It should not freeze, but open the dialog.

**Comment by AyanSinhaMahapatra** [comment]
@silverhook this is the same as https://github.com/nexB/scancode.io/issues/959 btw

**Comment by silverhook** [comment]
Still happens on Firefox 119.0.1 with ScanCode.io v32.7.0-37-gf4fbf03e2 

But I can narrow it down now to (seemingly) just the `deploy_to_develop` pipeline.

If I click on `scan_codebase_packages` or `populate_purldb`, it works as expected.

**Comment by AyanSinhaMahapatra** [comment]
@silverhook can you try copying and pasting the url (without the credentials in them) and see if this still happens? This seemed to fix it for me.

**Comment by silverhook** [comment]
@AyanSinhaMahapatra , sorry for the late reply.

Which URL should I be copying and pasting? On mouse-over on the pipeline name, I do not get a URL at all.

**Comment by AyanSinhaMahapatra** [comment]
@silverhook no worries, I mean here the URL from the browser search bar/url for SCIO (if you access an SCIO instance with the credentials in the URL, the credentials are not shown after you sign in, but they are present somehow. If you copy paste, you're deliberately removing this. )
This url will be something like: https://<path-to>.scancode.io/project/<project-id>/ in contrast to an URL with credentials, which would look like:  https://<userid>:<password>@<path-to>.scancode.io/project/<project-id>/

**Comment by silverhook** [comment]
This worked. Odd.

**Comment by tdruez** [comment]
@silverhook Thanks for reporting this one.
The [fix](https://github.com/nexB/scancode.io/pull/1048) is included in the latest ScanCode.io [release v33.0.0](https://github.com/nexB/scancode.io/releases/tag/v33.0.0)
